Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    flatten:
      Precision:
        result: fixed<16,6>
      Trace: true
    input_1:
      Precision:
        result: fixed<16,6>
      Trace: true
    q_activation:
      Precision:
        result: ufixed<16,0,RND_CONV,SAT>
      Trace: true
    q_activation_1:
      Precision:
        result: ufixed<16,0,RND_CONV,SAT>
      Trace: true
    q_activation_2:
      Precision:
        result: ufixed<16,0,RND_CONV,SAT>
      Trace: true
    q_activation_3:
      Precision:
        result: fixed<8,1,RND_CONV,SAT>
        shift: fixed<16,6>
        slope: fixed<16,6>
      Trace: true
    q_dense:
      Precision:
        bias: fixed<16,1>
        result: fixed<16,6>
        weight: fixed<16,1>
      Trace: true
    q_dense_1:
      Precision:
        bias: fixed<16,1>
        result: fixed<16,6>
        weight: fixed<16,1>
      Trace: true
    q_dense_1_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    q_dense_2:
      Precision:
        bias: fixed<16,1>
        result: fixed<16,6>
        weight: fixed<16,1>
      Trace: true
    q_dense_2_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    q_dense_3:
      Precision:
        bias: fixed<16,1>
        result: fixed<16,6>
        weight: fixed<16,1>
      Trace: true
    q_dense_3_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
    q_dense_linear:
      Precision:
        result: fixed<16,6>
      Trace: true
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'HLSModels/hls4ml_prjParamEst_Region34_5Hit/keras_model.h5'
OutputDir: HLSModels/hls4ml_prjParamEst_Region34_5Hit
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: ParamEst_NN
Stamp: D5C3e3db
Version: 1.0.0
