-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ParamEst_NN_relu_ap_fixed_ap_ufixed_16_0_4_0_0_PARAMEST_NN_relu_config5_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_8_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_9_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_10_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_11_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_12_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_13_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_14_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_15_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_16_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_17_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_18_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_19_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_20_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_21_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_22_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_23_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_24_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_25_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_26_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_27_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_28_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_29_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_30_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_31_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_16 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_17 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_18 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_19 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_20 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_21 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_22 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_23 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_24 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_25 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_26 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_27 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_28 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_29 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_30 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_31 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of ParamEst_NN_relu_ap_fixed_ap_ufixed_16_0_4_0_0_PARAMEST_NN_relu_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_6 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000110";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal tmp_fu_294_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_fu_288_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_fu_282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_fu_310_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_34_fu_338_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_64_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_64_fu_332_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_64_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_64_fu_354_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_s_fu_382_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_65_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_65_fu_376_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_65_fu_370_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_65_fu_398_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_63_fu_426_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_66_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_66_fu_420_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_66_fu_414_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_66_fu_442_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_64_fu_470_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_67_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_67_fu_464_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_67_fu_458_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_67_fu_486_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_65_fu_514_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_68_fu_524_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_68_fu_508_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_68_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_68_fu_530_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_66_fu_558_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_69_fu_568_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_69_fu_552_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_69_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_69_fu_574_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_67_fu_602_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_70_fu_612_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_70_fu_596_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_70_fu_590_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_70_fu_618_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_68_fu_646_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_71_fu_656_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_71_fu_640_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_71_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_71_fu_662_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_69_fu_690_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_72_fu_700_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_72_fu_684_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_72_fu_678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_72_fu_706_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_70_fu_734_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_73_fu_744_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_73_fu_728_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_73_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_73_fu_750_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_71_fu_778_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_74_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_74_fu_772_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_74_fu_766_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_74_fu_794_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_72_fu_822_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_75_fu_832_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_75_fu_816_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_75_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_75_fu_838_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_73_fu_866_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_76_fu_876_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_76_fu_860_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_76_fu_854_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_76_fu_882_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_74_fu_910_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_77_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_77_fu_904_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_77_fu_898_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_77_fu_926_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_75_fu_954_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_78_fu_964_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_78_fu_948_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_78_fu_942_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_78_fu_970_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_76_fu_998_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_79_fu_1008_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_79_fu_992_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_79_fu_986_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_79_fu_1014_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_77_fu_1042_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_80_fu_1052_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_80_fu_1036_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_80_fu_1030_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_80_fu_1058_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_78_fu_1086_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_81_fu_1096_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_81_fu_1080_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_81_fu_1074_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_81_fu_1102_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_79_fu_1130_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_82_fu_1140_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_82_fu_1124_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_82_fu_1118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_82_fu_1146_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_80_fu_1174_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_83_fu_1184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_83_fu_1168_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_83_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_83_fu_1190_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_81_fu_1218_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_84_fu_1228_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_84_fu_1212_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_84_fu_1206_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_84_fu_1234_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_82_fu_1262_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_85_fu_1272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_85_fu_1256_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_85_fu_1250_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_85_fu_1278_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_83_fu_1306_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_86_fu_1316_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_86_fu_1300_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_86_fu_1294_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_86_fu_1322_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_84_fu_1350_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_87_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_87_fu_1344_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_87_fu_1338_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_87_fu_1366_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_85_fu_1394_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_88_fu_1404_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_88_fu_1388_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_88_fu_1382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_88_fu_1410_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_86_fu_1438_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_89_fu_1448_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_89_fu_1432_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_89_fu_1426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_89_fu_1454_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_87_fu_1482_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_90_fu_1492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_90_fu_1476_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_90_fu_1470_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_90_fu_1498_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_88_fu_1526_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_91_fu_1536_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_91_fu_1520_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_91_fu_1514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_91_fu_1542_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_89_fu_1570_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_92_fu_1580_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_92_fu_1564_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_92_fu_1558_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_92_fu_1586_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_90_fu_1614_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_93_fu_1624_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_93_fu_1608_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_93_fu_1602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_93_fu_1630_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_91_fu_1658_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal icmp_ln46_94_fu_1668_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln46_94_fu_1652_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal icmp_ln45_94_fu_1646_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln46_94_fu_1674_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_fu_318_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_64_fu_362_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_65_fu_406_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_66_fu_450_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_67_fu_494_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_68_fu_538_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_69_fu_582_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_70_fu_626_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_71_fu_670_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_72_fu_714_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_73_fu_758_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_74_fu_802_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_75_fu_846_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_76_fu_890_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_77_fu_934_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_78_fu_978_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_79_fu_1022_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_80_fu_1066_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_81_fu_1110_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_82_fu_1154_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_83_fu_1198_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_84_fu_1242_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_85_fu_1286_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_86_fu_1330_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_87_fu_1374_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_88_fu_1418_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_89_fu_1462_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_90_fu_1506_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_91_fu_1550_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_92_fu_1594_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_93_fu_1638_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln45_94_fu_1682_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_ce_reg : STD_LOGIC;


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= select_ln45_fu_318_p3;
    ap_return_1 <= select_ln45_64_fu_362_p3;
    ap_return_10 <= select_ln45_73_fu_758_p3;
    ap_return_11 <= select_ln45_74_fu_802_p3;
    ap_return_12 <= select_ln45_75_fu_846_p3;
    ap_return_13 <= select_ln45_76_fu_890_p3;
    ap_return_14 <= select_ln45_77_fu_934_p3;
    ap_return_15 <= select_ln45_78_fu_978_p3;
    ap_return_16 <= select_ln45_79_fu_1022_p3;
    ap_return_17 <= select_ln45_80_fu_1066_p3;
    ap_return_18 <= select_ln45_81_fu_1110_p3;
    ap_return_19 <= select_ln45_82_fu_1154_p3;
    ap_return_2 <= select_ln45_65_fu_406_p3;
    ap_return_20 <= select_ln45_83_fu_1198_p3;
    ap_return_21 <= select_ln45_84_fu_1242_p3;
    ap_return_22 <= select_ln45_85_fu_1286_p3;
    ap_return_23 <= select_ln45_86_fu_1330_p3;
    ap_return_24 <= select_ln45_87_fu_1374_p3;
    ap_return_25 <= select_ln45_88_fu_1418_p3;
    ap_return_26 <= select_ln45_89_fu_1462_p3;
    ap_return_27 <= select_ln45_90_fu_1506_p3;
    ap_return_28 <= select_ln45_91_fu_1550_p3;
    ap_return_29 <= select_ln45_92_fu_1594_p3;
    ap_return_3 <= select_ln45_66_fu_450_p3;
    ap_return_30 <= select_ln45_93_fu_1638_p3;
    ap_return_31 <= select_ln45_94_fu_1682_p3;
    ap_return_4 <= select_ln45_67_fu_494_p3;
    ap_return_5 <= select_ln45_68_fu_538_p3;
    ap_return_6 <= select_ln45_69_fu_582_p3;
    ap_return_7 <= select_ln45_70_fu_626_p3;
    ap_return_8 <= select_ln45_71_fu_670_p3;
    ap_return_9 <= select_ln45_72_fu_714_p3;
    icmp_ln45_64_fu_326_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_65_fu_370_p2 <= "1" when (signed(data_2_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_66_fu_414_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_67_fu_458_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_68_fu_502_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_69_fu_546_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_70_fu_590_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_71_fu_634_p2 <= "1" when (signed(data_8_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_72_fu_678_p2 <= "1" when (signed(data_9_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_73_fu_722_p2 <= "1" when (signed(data_10_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_74_fu_766_p2 <= "1" when (signed(data_11_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_75_fu_810_p2 <= "1" when (signed(data_12_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_76_fu_854_p2 <= "1" when (signed(data_13_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_77_fu_898_p2 <= "1" when (signed(data_14_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_78_fu_942_p2 <= "1" when (signed(data_15_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_79_fu_986_p2 <= "1" when (signed(data_16_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_80_fu_1030_p2 <= "1" when (signed(data_17_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_81_fu_1074_p2 <= "1" when (signed(data_18_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_82_fu_1118_p2 <= "1" when (signed(data_19_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_83_fu_1162_p2 <= "1" when (signed(data_20_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_84_fu_1206_p2 <= "1" when (signed(data_21_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_85_fu_1250_p2 <= "1" when (signed(data_22_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_86_fu_1294_p2 <= "1" when (signed(data_23_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_87_fu_1338_p2 <= "1" when (signed(data_24_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_88_fu_1382_p2 <= "1" when (signed(data_25_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_89_fu_1426_p2 <= "1" when (signed(data_26_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_90_fu_1470_p2 <= "1" when (signed(data_27_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_91_fu_1514_p2 <= "1" when (signed(data_28_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_92_fu_1558_p2 <= "1" when (signed(data_29_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_93_fu_1602_p2 <= "1" when (signed(data_30_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_94_fu_1646_p2 <= "1" when (signed(data_31_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_282_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln46_64_fu_348_p2 <= "0" when (tmp_34_fu_338_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_65_fu_392_p2 <= "0" when (tmp_s_fu_382_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_66_fu_436_p2 <= "0" when (tmp_63_fu_426_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_67_fu_480_p2 <= "0" when (tmp_64_fu_470_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_68_fu_524_p2 <= "0" when (tmp_65_fu_514_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_69_fu_568_p2 <= "0" when (tmp_66_fu_558_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_70_fu_612_p2 <= "0" when (tmp_67_fu_602_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_71_fu_656_p2 <= "0" when (tmp_68_fu_646_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_72_fu_700_p2 <= "0" when (tmp_69_fu_690_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_73_fu_744_p2 <= "0" when (tmp_70_fu_734_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_74_fu_788_p2 <= "0" when (tmp_71_fu_778_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_75_fu_832_p2 <= "0" when (tmp_72_fu_822_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_76_fu_876_p2 <= "0" when (tmp_73_fu_866_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_77_fu_920_p2 <= "0" when (tmp_74_fu_910_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_78_fu_964_p2 <= "0" when (tmp_75_fu_954_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_79_fu_1008_p2 <= "0" when (tmp_76_fu_998_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_80_fu_1052_p2 <= "0" when (tmp_77_fu_1042_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_81_fu_1096_p2 <= "0" when (tmp_78_fu_1086_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_82_fu_1140_p2 <= "0" when (tmp_79_fu_1130_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_83_fu_1184_p2 <= "0" when (tmp_80_fu_1174_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_84_fu_1228_p2 <= "0" when (tmp_81_fu_1218_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_85_fu_1272_p2 <= "0" when (tmp_82_fu_1262_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_86_fu_1316_p2 <= "0" when (tmp_83_fu_1306_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_87_fu_1360_p2 <= "0" when (tmp_84_fu_1350_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_88_fu_1404_p2 <= "0" when (tmp_85_fu_1394_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_89_fu_1448_p2 <= "0" when (tmp_86_fu_1438_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_90_fu_1492_p2 <= "0" when (tmp_87_fu_1482_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_91_fu_1536_p2 <= "0" when (tmp_88_fu_1526_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_92_fu_1580_p2 <= "0" when (tmp_89_fu_1570_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_93_fu_1624_p2 <= "0" when (tmp_90_fu_1614_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_94_fu_1668_p2 <= "0" when (tmp_91_fu_1658_p4 = ap_const_lv6_0) else "1";
    icmp_ln46_fu_304_p2 <= "0" when (tmp_fu_294_p4 = ap_const_lv6_0) else "1";
    select_ln45_64_fu_362_p3 <= 
        select_ln46_64_fu_354_p3 when (icmp_ln45_64_fu_326_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_65_fu_406_p3 <= 
        select_ln46_65_fu_398_p3 when (icmp_ln45_65_fu_370_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_66_fu_450_p3 <= 
        select_ln46_66_fu_442_p3 when (icmp_ln45_66_fu_414_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_67_fu_494_p3 <= 
        select_ln46_67_fu_486_p3 when (icmp_ln45_67_fu_458_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_68_fu_538_p3 <= 
        select_ln46_68_fu_530_p3 when (icmp_ln45_68_fu_502_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_69_fu_582_p3 <= 
        select_ln46_69_fu_574_p3 when (icmp_ln45_69_fu_546_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_70_fu_626_p3 <= 
        select_ln46_70_fu_618_p3 when (icmp_ln45_70_fu_590_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_71_fu_670_p3 <= 
        select_ln46_71_fu_662_p3 when (icmp_ln45_71_fu_634_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_72_fu_714_p3 <= 
        select_ln46_72_fu_706_p3 when (icmp_ln45_72_fu_678_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_73_fu_758_p3 <= 
        select_ln46_73_fu_750_p3 when (icmp_ln45_73_fu_722_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_74_fu_802_p3 <= 
        select_ln46_74_fu_794_p3 when (icmp_ln45_74_fu_766_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_75_fu_846_p3 <= 
        select_ln46_75_fu_838_p3 when (icmp_ln45_75_fu_810_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_76_fu_890_p3 <= 
        select_ln46_76_fu_882_p3 when (icmp_ln45_76_fu_854_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_77_fu_934_p3 <= 
        select_ln46_77_fu_926_p3 when (icmp_ln45_77_fu_898_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_78_fu_978_p3 <= 
        select_ln46_78_fu_970_p3 when (icmp_ln45_78_fu_942_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_79_fu_1022_p3 <= 
        select_ln46_79_fu_1014_p3 when (icmp_ln45_79_fu_986_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_80_fu_1066_p3 <= 
        select_ln46_80_fu_1058_p3 when (icmp_ln45_80_fu_1030_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_81_fu_1110_p3 <= 
        select_ln46_81_fu_1102_p3 when (icmp_ln45_81_fu_1074_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_82_fu_1154_p3 <= 
        select_ln46_82_fu_1146_p3 when (icmp_ln45_82_fu_1118_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_83_fu_1198_p3 <= 
        select_ln46_83_fu_1190_p3 when (icmp_ln45_83_fu_1162_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_84_fu_1242_p3 <= 
        select_ln46_84_fu_1234_p3 when (icmp_ln45_84_fu_1206_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_85_fu_1286_p3 <= 
        select_ln46_85_fu_1278_p3 when (icmp_ln45_85_fu_1250_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_86_fu_1330_p3 <= 
        select_ln46_86_fu_1322_p3 when (icmp_ln45_86_fu_1294_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_87_fu_1374_p3 <= 
        select_ln46_87_fu_1366_p3 when (icmp_ln45_87_fu_1338_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_88_fu_1418_p3 <= 
        select_ln46_88_fu_1410_p3 when (icmp_ln45_88_fu_1382_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_89_fu_1462_p3 <= 
        select_ln46_89_fu_1454_p3 when (icmp_ln45_89_fu_1426_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_90_fu_1506_p3 <= 
        select_ln46_90_fu_1498_p3 when (icmp_ln45_90_fu_1470_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_91_fu_1550_p3 <= 
        select_ln46_91_fu_1542_p3 when (icmp_ln45_91_fu_1514_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_92_fu_1594_p3 <= 
        select_ln46_92_fu_1586_p3 when (icmp_ln45_92_fu_1558_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_93_fu_1638_p3 <= 
        select_ln46_93_fu_1630_p3 when (icmp_ln45_93_fu_1602_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_94_fu_1682_p3 <= 
        select_ln46_94_fu_1674_p3 when (icmp_ln45_94_fu_1646_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln45_fu_318_p3 <= 
        select_ln46_fu_310_p3 when (icmp_ln45_fu_282_p2(0) = '1') else 
        ap_const_lv16_0;
    select_ln46_64_fu_354_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_64_fu_348_p2(0) = '1') else 
        shl_ln46_64_fu_332_p2;
    select_ln46_65_fu_398_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_65_fu_392_p2(0) = '1') else 
        shl_ln46_65_fu_376_p2;
    select_ln46_66_fu_442_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_66_fu_436_p2(0) = '1') else 
        shl_ln46_66_fu_420_p2;
    select_ln46_67_fu_486_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_67_fu_480_p2(0) = '1') else 
        shl_ln46_67_fu_464_p2;
    select_ln46_68_fu_530_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_68_fu_524_p2(0) = '1') else 
        shl_ln46_68_fu_508_p2;
    select_ln46_69_fu_574_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_69_fu_568_p2(0) = '1') else 
        shl_ln46_69_fu_552_p2;
    select_ln46_70_fu_618_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_70_fu_612_p2(0) = '1') else 
        shl_ln46_70_fu_596_p2;
    select_ln46_71_fu_662_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_71_fu_656_p2(0) = '1') else 
        shl_ln46_71_fu_640_p2;
    select_ln46_72_fu_706_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_72_fu_700_p2(0) = '1') else 
        shl_ln46_72_fu_684_p2;
    select_ln46_73_fu_750_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_73_fu_744_p2(0) = '1') else 
        shl_ln46_73_fu_728_p2;
    select_ln46_74_fu_794_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_74_fu_788_p2(0) = '1') else 
        shl_ln46_74_fu_772_p2;
    select_ln46_75_fu_838_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_75_fu_832_p2(0) = '1') else 
        shl_ln46_75_fu_816_p2;
    select_ln46_76_fu_882_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_76_fu_876_p2(0) = '1') else 
        shl_ln46_76_fu_860_p2;
    select_ln46_77_fu_926_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_77_fu_920_p2(0) = '1') else 
        shl_ln46_77_fu_904_p2;
    select_ln46_78_fu_970_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_78_fu_964_p2(0) = '1') else 
        shl_ln46_78_fu_948_p2;
    select_ln46_79_fu_1014_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_79_fu_1008_p2(0) = '1') else 
        shl_ln46_79_fu_992_p2;
    select_ln46_80_fu_1058_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_80_fu_1052_p2(0) = '1') else 
        shl_ln46_80_fu_1036_p2;
    select_ln46_81_fu_1102_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_81_fu_1096_p2(0) = '1') else 
        shl_ln46_81_fu_1080_p2;
    select_ln46_82_fu_1146_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_82_fu_1140_p2(0) = '1') else 
        shl_ln46_82_fu_1124_p2;
    select_ln46_83_fu_1190_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_83_fu_1184_p2(0) = '1') else 
        shl_ln46_83_fu_1168_p2;
    select_ln46_84_fu_1234_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_84_fu_1228_p2(0) = '1') else 
        shl_ln46_84_fu_1212_p2;
    select_ln46_85_fu_1278_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_85_fu_1272_p2(0) = '1') else 
        shl_ln46_85_fu_1256_p2;
    select_ln46_86_fu_1322_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_86_fu_1316_p2(0) = '1') else 
        shl_ln46_86_fu_1300_p2;
    select_ln46_87_fu_1366_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_87_fu_1360_p2(0) = '1') else 
        shl_ln46_87_fu_1344_p2;
    select_ln46_88_fu_1410_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_88_fu_1404_p2(0) = '1') else 
        shl_ln46_88_fu_1388_p2;
    select_ln46_89_fu_1454_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_89_fu_1448_p2(0) = '1') else 
        shl_ln46_89_fu_1432_p2;
    select_ln46_90_fu_1498_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_90_fu_1492_p2(0) = '1') else 
        shl_ln46_90_fu_1476_p2;
    select_ln46_91_fu_1542_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_91_fu_1536_p2(0) = '1') else 
        shl_ln46_91_fu_1520_p2;
    select_ln46_92_fu_1586_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_92_fu_1580_p2(0) = '1') else 
        shl_ln46_92_fu_1564_p2;
    select_ln46_93_fu_1630_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_93_fu_1624_p2(0) = '1') else 
        shl_ln46_93_fu_1608_p2;
    select_ln46_94_fu_1674_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_94_fu_1668_p2(0) = '1') else 
        shl_ln46_94_fu_1652_p2;
    select_ln46_fu_310_p3 <= 
        ap_const_lv16_FFFF when (icmp_ln46_fu_304_p2(0) = '1') else 
        shl_ln46_fu_288_p2;
    shl_ln46_64_fu_332_p2 <= std_logic_vector(shift_left(unsigned(data_1_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_65_fu_376_p2 <= std_logic_vector(shift_left(unsigned(data_2_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_66_fu_420_p2 <= std_logic_vector(shift_left(unsigned(data_3_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_67_fu_464_p2 <= std_logic_vector(shift_left(unsigned(data_4_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_68_fu_508_p2 <= std_logic_vector(shift_left(unsigned(data_5_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_69_fu_552_p2 <= std_logic_vector(shift_left(unsigned(data_6_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_70_fu_596_p2 <= std_logic_vector(shift_left(unsigned(data_7_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_71_fu_640_p2 <= std_logic_vector(shift_left(unsigned(data_8_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_72_fu_684_p2 <= std_logic_vector(shift_left(unsigned(data_9_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_73_fu_728_p2 <= std_logic_vector(shift_left(unsigned(data_10_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_74_fu_772_p2 <= std_logic_vector(shift_left(unsigned(data_11_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_75_fu_816_p2 <= std_logic_vector(shift_left(unsigned(data_12_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_76_fu_860_p2 <= std_logic_vector(shift_left(unsigned(data_13_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_77_fu_904_p2 <= std_logic_vector(shift_left(unsigned(data_14_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_78_fu_948_p2 <= std_logic_vector(shift_left(unsigned(data_15_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_79_fu_992_p2 <= std_logic_vector(shift_left(unsigned(data_16_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_80_fu_1036_p2 <= std_logic_vector(shift_left(unsigned(data_17_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_81_fu_1080_p2 <= std_logic_vector(shift_left(unsigned(data_18_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_82_fu_1124_p2 <= std_logic_vector(shift_left(unsigned(data_19_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_83_fu_1168_p2 <= std_logic_vector(shift_left(unsigned(data_20_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_84_fu_1212_p2 <= std_logic_vector(shift_left(unsigned(data_21_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_85_fu_1256_p2 <= std_logic_vector(shift_left(unsigned(data_22_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_86_fu_1300_p2 <= std_logic_vector(shift_left(unsigned(data_23_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_87_fu_1344_p2 <= std_logic_vector(shift_left(unsigned(data_24_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_88_fu_1388_p2 <= std_logic_vector(shift_left(unsigned(data_25_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_89_fu_1432_p2 <= std_logic_vector(shift_left(unsigned(data_26_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_90_fu_1476_p2 <= std_logic_vector(shift_left(unsigned(data_27_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_91_fu_1520_p2 <= std_logic_vector(shift_left(unsigned(data_28_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_92_fu_1564_p2 <= std_logic_vector(shift_left(unsigned(data_29_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_93_fu_1608_p2 <= std_logic_vector(shift_left(unsigned(data_30_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_94_fu_1652_p2 <= std_logic_vector(shift_left(unsigned(data_31_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    shl_ln46_fu_288_p2 <= std_logic_vector(shift_left(unsigned(data_0_val),to_integer(unsigned('0' & ap_const_lv16_6(16-1 downto 0)))));
    tmp_34_fu_338_p4 <= data_1_val(15 downto 10);
    tmp_63_fu_426_p4 <= data_3_val(15 downto 10);
    tmp_64_fu_470_p4 <= data_4_val(15 downto 10);
    tmp_65_fu_514_p4 <= data_5_val(15 downto 10);
    tmp_66_fu_558_p4 <= data_6_val(15 downto 10);
    tmp_67_fu_602_p4 <= data_7_val(15 downto 10);
    tmp_68_fu_646_p4 <= data_8_val(15 downto 10);
    tmp_69_fu_690_p4 <= data_9_val(15 downto 10);
    tmp_70_fu_734_p4 <= data_10_val(15 downto 10);
    tmp_71_fu_778_p4 <= data_11_val(15 downto 10);
    tmp_72_fu_822_p4 <= data_12_val(15 downto 10);
    tmp_73_fu_866_p4 <= data_13_val(15 downto 10);
    tmp_74_fu_910_p4 <= data_14_val(15 downto 10);
    tmp_75_fu_954_p4 <= data_15_val(15 downto 10);
    tmp_76_fu_998_p4 <= data_16_val(15 downto 10);
    tmp_77_fu_1042_p4 <= data_17_val(15 downto 10);
    tmp_78_fu_1086_p4 <= data_18_val(15 downto 10);
    tmp_79_fu_1130_p4 <= data_19_val(15 downto 10);
    tmp_80_fu_1174_p4 <= data_20_val(15 downto 10);
    tmp_81_fu_1218_p4 <= data_21_val(15 downto 10);
    tmp_82_fu_1262_p4 <= data_22_val(15 downto 10);
    tmp_83_fu_1306_p4 <= data_23_val(15 downto 10);
    tmp_84_fu_1350_p4 <= data_24_val(15 downto 10);
    tmp_85_fu_1394_p4 <= data_25_val(15 downto 10);
    tmp_86_fu_1438_p4 <= data_26_val(15 downto 10);
    tmp_87_fu_1482_p4 <= data_27_val(15 downto 10);
    tmp_88_fu_1526_p4 <= data_28_val(15 downto 10);
    tmp_89_fu_1570_p4 <= data_29_val(15 downto 10);
    tmp_90_fu_1614_p4 <= data_30_val(15 downto 10);
    tmp_91_fu_1658_p4 <= data_31_val(15 downto 10);
    tmp_fu_294_p4 <= data_0_val(15 downto 10);
    tmp_s_fu_382_p4 <= data_2_val(15 downto 10);
end behav;
