-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity ParamEst_NN_hard_tanh_ap_fixed_ap_fixed_8_1_4_0_0_PARAMEST_NN_hard_tanh_config14_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of ParamEst_NN_hard_tanh_ap_fixed_ap_fixed_8_1_4_0_0_PARAMEST_NN_hard_tanh_config14_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv18_800 : STD_LOGIC_VECTOR (17 downto 0) := "000000100000000000";
    constant ap_const_lv13_800 : STD_LOGIC_VECTOR (12 downto 0) := "0100000000000";
    constant ap_const_lv18_1000 : STD_LOGIC_VECTOR (17 downto 0) := "000001000000000000";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv13_1000 : STD_LOGIC_VECTOR (12 downto 0) := "1000000000000";
    constant ap_const_lv13_0 : STD_LOGIC_VECTOR (12 downto 0) := "0000000000000";
    constant ap_const_lv14_3000 : STD_LOGIC_VECTOR (13 downto 0) := "11000000000000";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_7F : STD_LOGIC_VECTOR (7 downto 0) := "01111111";

attribute shreg_extract : string;
    signal tmp_1_reg_1594 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal tmp_3_fu_226_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1600 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln473_1_fu_250_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln473_1_reg_1605 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_fu_256_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1610 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_264_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1616 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_15_fu_272_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_15_reg_1622 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_4_fu_304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_4_reg_1627 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1632 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_fu_442_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1638 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln473_3_fu_466_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln473_3_reg_1643 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_11_fu_472_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1648 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_fu_480_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1654 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_17_fu_488_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_17_reg_1660 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_10_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_10_reg_1665 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_1670 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_fu_658_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1676 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln473_5_fu_682_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln473_5_reg_1681 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_18_fu_688_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1686 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_fu_696_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1692 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_19_fu_704_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_19_reg_1698 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_16_fu_736_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_16_reg_1703 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1708 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_fu_874_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1714 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln473_7_fu_898_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln473_7_reg_1719 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_25_fu_904_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_1724 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_fu_912_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_reg_1730 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_21_fu_920_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_21_reg_1736 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_22_fu_952_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_22_reg_1741 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_29_reg_1746 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_fu_1090_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_31_reg_1752 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln473_9_fu_1114_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln473_9_reg_1757 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_fu_1120_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_32_reg_1762 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_fu_1128_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_33_reg_1768 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_23_fu_1136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_23_reg_1774 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_28_fu_1168_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_28_reg_1779 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal shl_ln_fu_94_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln468_fu_106_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln468_fu_102_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln_fu_110_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_fu_118_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln469_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_136_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln469_fu_152_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln469_fu_144_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln468_2_fu_124_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_1_fu_158_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln1_fu_166_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln473_fu_174_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln473_6_fu_188_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln473_fu_198_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln473_1_fu_216_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln473_fu_204_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln473_fu_220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_208_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_fu_240_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln473_fu_246_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_6_fu_278_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_5_fu_286_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_25_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_1_fu_298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln468_1_fu_310_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln468_5_fu_322_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln468_1_fu_318_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln468_1_fu_326_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_2_fu_334_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln469_1_fu_346_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_fu_352_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln469_1_fu_368_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln469_1_fu_360_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln468_fu_340_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_3_fu_374_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln473_1_fu_382_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln473_2_fu_390_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln473_9_fu_404_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln473_9_fu_414_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln473_3_fu_432_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln473_2_fu_420_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln473_1_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_3_fu_450_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_fu_424_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_6_fu_456_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln473_1_fu_462_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_13_fu_494_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_14_fu_502_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_26_fu_508_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_7_fu_514_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln468_2_fu_526_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln468_6_fu_538_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln468_2_fu_534_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln468_2_fu_542_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_4_fu_550_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln469_2_fu_562_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_fu_568_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln469_2_fu_584_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln469_2_fu_576_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln468_5_fu_556_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_5_fu_590_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln473_2_fu_598_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln473_4_fu_606_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln473_s_fu_620_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln473_16_fu_630_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln473_5_fu_648_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln473_4_fu_636_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln473_2_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_6_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_fu_640_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_12_fu_672_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln473_2_fu_678_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_20_fu_710_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_21_fu_718_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_27_fu_724_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_13_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln468_3_fu_742_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln468_7_fu_754_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln468_3_fu_750_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln468_3_fu_758_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_6_fu_766_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln469_3_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_fu_784_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln469_3_fu_800_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln469_3_fu_792_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln468_7_fu_772_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_7_fu_806_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln473_3_fu_814_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln473_6_fu_822_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln473_7_fu_836_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln473_25_fu_846_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln473_10_fu_864_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln473_8_fu_852_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln473_3_fu_868_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_9_fu_882_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_856_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_18_fu_888_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln473_3_fu_894_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_27_fu_926_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_28_fu_934_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_28_fu_940_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_19_fu_946_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal shl_ln468_4_fu_958_p3 : STD_LOGIC_VECTOR (16 downto 0);
    signal trunc_ln468_8_fu_970_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal sext_ln468_4_fu_966_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal trunc_ln468_4_fu_974_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_8_fu_982_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal icmp_ln469_4_fu_994_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_28_fu_1000_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln469_4_fu_1016_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln469_4_fu_1008_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal add_ln468_8_fu_988_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal sigmoid_9_fu_1022_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal shl_ln473_4_fu_1030_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal add_ln473_8_fu_1038_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal trunc_ln473_11_fu_1052_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal xor_ln473_30_fu_1062_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln473_13_fu_1080_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln473_12_fu_1068_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln473_4_fu_1084_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_12_fu_1098_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_30_fu_1072_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_24_fu_1104_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln473_4_fu_1110_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_34_fu_1142_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_33_fu_1150_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_29_fu_1156_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_25_fu_1162_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_30_fu_1174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_1_fu_1178_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_4_fu_1184_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_2_fu_1193_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_1_fu_1199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_3_fu_1204_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_2_fu_1188_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_16_fu_1215_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_6_fu_1220_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_3_fu_1209_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_5_fu_1226_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_2_fu_1239_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln473_fu_1231_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln473_31_fu_1252_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_10_fu_1256_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_11_fu_1262_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_7_fu_1271_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_4_fu_1277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_8_fu_1282_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_8_fu_1266_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_18_fu_1293_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_15_fu_1298_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_9_fu_1287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_11_fu_1304_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_5_fu_1317_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln473_3_fu_1309_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln473_32_fu_1330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_19_fu_1334_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_20_fu_1340_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_12_fu_1349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_7_fu_1355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_13_fu_1360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_14_fu_1344_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_20_fu_1371_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_24_fu_1376_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_15_fu_1365_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_17_fu_1382_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_8_fu_1395_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln473_6_fu_1387_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln473_33_fu_1408_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_26_fu_1412_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_27_fu_1418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_17_fu_1427_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_10_fu_1433_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_18_fu_1438_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_20_fu_1422_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_22_fu_1449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_29_fu_1454_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_21_fu_1443_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_23_fu_1460_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_11_fu_1473_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln473_9_fu_1465_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal or_ln473_34_fu_1486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_31_fu_1490_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_32_fu_1496_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_22_fu_1505_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_13_fu_1511_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_23_fu_1516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_26_fu_1500_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_24_fu_1527_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln473_34_fu_1532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_27_fu_1521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln473_29_fu_1538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln473_14_fu_1551_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln473_12_fu_1543_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln473_1_fu_1245_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln473_4_fu_1323_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln473_7_fu_1401_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln473_10_fu_1479_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln473_13_fu_1557_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_ce_reg : STD_LOGIC;
    signal ap_return_0_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_1_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_2_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_3_int_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_return_4_int_reg : STD_LOGIC_VECTOR (7 downto 0);


begin




    ap_ce_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            ap_ce_reg <= ap_ce;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_const_logic_1))) then
                add_ln473_1_reg_1605 <= add_ln473_1_fu_250_p2;
                add_ln473_3_reg_1643 <= add_ln473_3_fu_466_p2;
                add_ln473_5_reg_1681 <= add_ln473_5_fu_682_p2;
                add_ln473_7_reg_1719 <= add_ln473_7_fu_898_p2;
                add_ln473_9_reg_1757 <= add_ln473_9_fu_1114_p2;
                and_ln473_10_reg_1665 <= and_ln473_10_fu_520_p2;
                and_ln473_16_reg_1703 <= and_ln473_16_fu_736_p2;
                and_ln473_22_reg_1741 <= and_ln473_22_fu_952_p2;
                and_ln473_28_reg_1779 <= and_ln473_28_fu_1168_p2;
                and_ln473_4_reg_1627 <= and_ln473_4_fu_304_p2;
                or_ln473_15_reg_1622 <= or_ln473_15_fu_272_p2;
                or_ln473_17_reg_1660 <= or_ln473_17_fu_488_p2;
                or_ln473_19_reg_1698 <= or_ln473_19_fu_704_p2;
                or_ln473_21_reg_1736 <= or_ln473_21_fu_920_p2;
                or_ln473_23_reg_1774 <= or_ln473_23_fu_1136_p2;
                tmp_10_reg_1638 <= sigmoid_3_fu_374_p3(11 downto 11);
                tmp_11_reg_1648 <= add_ln473_3_fu_466_p2(7 downto 7);
                tmp_12_reg_1654 <= add_ln473_2_fu_390_p2(13 downto 13);
                tmp_15_reg_1670 <= add_ln473_4_fu_606_p2(13 downto 13);
                tmp_17_reg_1676 <= sigmoid_5_fu_590_p3(11 downto 11);
                tmp_18_reg_1686 <= add_ln473_5_fu_682_p2(7 downto 7);
                tmp_19_reg_1692 <= add_ln473_4_fu_606_p2(13 downto 13);
                tmp_1_reg_1594 <= add_ln473_fu_174_p2(13 downto 13);
                tmp_22_reg_1708 <= add_ln473_6_fu_822_p2(13 downto 13);
                tmp_24_reg_1714 <= sigmoid_7_fu_806_p3(11 downto 11);
                tmp_25_reg_1724 <= add_ln473_7_fu_898_p2(7 downto 7);
                tmp_26_reg_1730 <= add_ln473_6_fu_822_p2(13 downto 13);
                tmp_29_reg_1746 <= add_ln473_8_fu_1038_p2(13 downto 13);
                tmp_31_reg_1752 <= sigmoid_9_fu_1022_p3(11 downto 11);
                tmp_32_reg_1762 <= add_ln473_9_fu_1114_p2(7 downto 7);
                tmp_33_reg_1768 <= add_ln473_8_fu_1038_p2(13 downto 13);
                tmp_3_reg_1600 <= sigmoid_1_fu_158_p3(11 downto 11);
                tmp_4_reg_1610 <= add_ln473_1_fu_250_p2(7 downto 7);
                tmp_5_reg_1616 <= add_ln473_fu_174_p2(13 downto 13);
                tmp_8_reg_1632 <= add_ln473_2_fu_390_p2(13 downto 13);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_ce_reg)) then
                ap_return_0_int_reg <= select_ln473_1_fu_1245_p3;
                ap_return_1_int_reg <= select_ln473_4_fu_1323_p3;
                ap_return_2_int_reg <= select_ln473_7_fu_1401_p3;
                ap_return_3_int_reg <= select_ln473_10_fu_1479_p3;
                ap_return_4_int_reg <= select_ln473_13_fu_1557_p3;
            end if;
        end if;
    end process;
    add_ln468_2_fu_124_p2 <= std_logic_vector(unsigned(trunc_ln_fu_110_p3) + unsigned(ap_const_lv13_800));
    add_ln468_5_fu_556_p2 <= std_logic_vector(unsigned(trunc_ln468_2_fu_542_p3) + unsigned(ap_const_lv13_800));
    add_ln468_7_fu_772_p2 <= std_logic_vector(unsigned(trunc_ln468_3_fu_758_p3) + unsigned(ap_const_lv13_800));
    add_ln468_8_fu_988_p2 <= std_logic_vector(unsigned(trunc_ln468_4_fu_974_p3) + unsigned(ap_const_lv13_800));
    add_ln468_fu_340_p2 <= std_logic_vector(unsigned(trunc_ln468_1_fu_326_p3) + unsigned(ap_const_lv13_800));
    add_ln473_1_fu_250_p2 <= std_logic_vector(unsigned(xor_ln473_fu_198_p2) + unsigned(zext_ln473_fu_246_p1));
    add_ln473_2_fu_390_p2 <= std_logic_vector(unsigned(shl_ln473_1_fu_382_p3) + unsigned(ap_const_lv14_3000));
    add_ln473_3_fu_466_p2 <= std_logic_vector(unsigned(xor_ln473_9_fu_414_p2) + unsigned(zext_ln473_1_fu_462_p1));
    add_ln473_4_fu_606_p2 <= std_logic_vector(unsigned(shl_ln473_2_fu_598_p3) + unsigned(ap_const_lv14_3000));
    add_ln473_5_fu_682_p2 <= std_logic_vector(unsigned(xor_ln473_16_fu_630_p2) + unsigned(zext_ln473_2_fu_678_p1));
    add_ln473_6_fu_822_p2 <= std_logic_vector(unsigned(shl_ln473_3_fu_814_p3) + unsigned(ap_const_lv14_3000));
    add_ln473_7_fu_898_p2 <= std_logic_vector(unsigned(xor_ln473_25_fu_846_p2) + unsigned(zext_ln473_3_fu_894_p1));
    add_ln473_8_fu_1038_p2 <= std_logic_vector(unsigned(shl_ln473_4_fu_1030_p3) + unsigned(ap_const_lv14_3000));
    add_ln473_9_fu_1114_p2 <= std_logic_vector(unsigned(xor_ln473_30_fu_1062_p2) + unsigned(zext_ln473_4_fu_1110_p1));
    add_ln473_fu_174_p2 <= std_logic_vector(unsigned(shl_ln1_fu_166_p3) + unsigned(ap_const_lv14_3000));
    and_ln473_10_fu_520_p2 <= (tmp_11_fu_472_p3 and and_ln473_7_fu_514_p2);
    and_ln473_11_fu_1304_p2 <= (xor_ln473_15_fu_1298_p2 and tmp_8_reg_1632);
    and_ln473_12_fu_672_p2 <= (tmp_16_fu_640_p3 and or_ln473_6_fu_666_p2);
    and_ln473_13_fu_730_p2 <= (tmp_19_fu_696_p3 and or_ln473_27_fu_724_p2);
    and_ln473_14_fu_1344_p2 <= (xor_ln473_19_fu_1334_p2 and tmp_19_reg_1692);
    and_ln473_15_fu_1365_p2 <= (xor_ln473_13_fu_1360_p2 and or_ln473_7_fu_1355_p2);
    and_ln473_16_fu_736_p2 <= (tmp_18_fu_688_p3 and and_ln473_13_fu_730_p2);
    and_ln473_17_fu_1382_p2 <= (xor_ln473_24_fu_1376_p2 and tmp_15_reg_1670);
    and_ln473_18_fu_888_p2 <= (tmp_23_fu_856_p3 and or_ln473_9_fu_882_p2);
    and_ln473_19_fu_946_p2 <= (tmp_26_fu_912_p3 and or_ln473_28_fu_940_p2);
    and_ln473_1_fu_298_p2 <= (tmp_5_fu_264_p3 and or_ln473_25_fu_292_p2);
    and_ln473_20_fu_1422_p2 <= (xor_ln473_26_fu_1412_p2 and tmp_26_reg_1730);
    and_ln473_21_fu_1443_p2 <= (xor_ln473_18_fu_1438_p2 and or_ln473_10_fu_1433_p2);
    and_ln473_22_fu_952_p2 <= (tmp_25_fu_904_p3 and and_ln473_19_fu_946_p2);
    and_ln473_23_fu_1460_p2 <= (xor_ln473_29_fu_1454_p2 and tmp_22_reg_1708);
    and_ln473_24_fu_1104_p2 <= (tmp_30_fu_1072_p3 and or_ln473_12_fu_1098_p2);
    and_ln473_25_fu_1162_p2 <= (tmp_33_fu_1128_p3 and or_ln473_29_fu_1156_p2);
    and_ln473_26_fu_1500_p2 <= (xor_ln473_31_fu_1490_p2 and tmp_33_reg_1768);
    and_ln473_27_fu_1521_p2 <= (xor_ln473_23_fu_1516_p2 and or_ln473_13_fu_1511_p2);
    and_ln473_28_fu_1168_p2 <= (tmp_32_fu_1120_p3 and and_ln473_25_fu_1162_p2);
    and_ln473_29_fu_1538_p2 <= (xor_ln473_34_fu_1532_p2 and tmp_29_reg_1746);
    and_ln473_2_fu_1188_p2 <= (xor_ln473_1_fu_1178_p2 and tmp_5_reg_1616);
    and_ln473_3_fu_1209_p2 <= (xor_ln473_3_fu_1204_p2 and or_ln473_1_fu_1199_p2);
    and_ln473_4_fu_304_p2 <= (tmp_4_fu_256_p3 and and_ln473_1_fu_298_p2);
    and_ln473_5_fu_1226_p2 <= (xor_ln473_6_fu_1220_p2 and tmp_1_reg_1594);
    and_ln473_6_fu_456_p2 <= (tmp_9_fu_424_p3 and or_ln473_3_fu_450_p2);
    and_ln473_7_fu_514_p2 <= (tmp_12_fu_480_p3 and or_ln473_26_fu_508_p2);
    and_ln473_8_fu_1266_p2 <= (xor_ln473_10_fu_1256_p2 and tmp_12_reg_1654);
    and_ln473_9_fu_1287_p2 <= (xor_ln473_8_fu_1282_p2 and or_ln473_4_fu_1277_p2);
    and_ln473_fu_240_p2 <= (tmp_2_fu_208_p3 and or_ln473_fu_234_p2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_return_0_assign_proc : process(select_ln473_1_fu_1245_p3, ap_ce_reg, ap_return_0_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_0 <= ap_return_0_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_0 <= select_ln473_1_fu_1245_p3;
        else 
            ap_return_0 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_1_assign_proc : process(select_ln473_4_fu_1323_p3, ap_ce_reg, ap_return_1_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_1 <= ap_return_1_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_1 <= select_ln473_4_fu_1323_p3;
        else 
            ap_return_1 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_2_assign_proc : process(select_ln473_7_fu_1401_p3, ap_ce_reg, ap_return_2_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_2 <= ap_return_2_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_2 <= select_ln473_7_fu_1401_p3;
        else 
            ap_return_2 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_3_assign_proc : process(select_ln473_10_fu_1479_p3, ap_ce_reg, ap_return_3_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_3 <= ap_return_3_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_3 <= select_ln473_10_fu_1479_p3;
        else 
            ap_return_3 <= "XXXXXXXX";
        end if; 
    end process;


    ap_return_4_assign_proc : process(select_ln473_13_fu_1557_p3, ap_ce_reg, ap_return_4_int_reg)
    begin
        if ((ap_const_logic_0 = ap_ce_reg)) then 
            ap_return_4 <= ap_return_4_int_reg;
        elsif ((ap_const_logic_1 = ap_ce_reg)) then 
            ap_return_4 <= select_ln473_13_fu_1557_p3;
        else 
            ap_return_4 <= "XXXXXXXX";
        end if; 
    end process;

    icmp_ln469_1_fu_346_p2 <= "1" when (signed(sigmoid_2_fu_334_p2) > signed(ap_const_lv18_1000)) else "0";
    icmp_ln469_2_fu_562_p2 <= "1" when (signed(sigmoid_4_fu_550_p2) > signed(ap_const_lv18_1000)) else "0";
    icmp_ln469_3_fu_778_p2 <= "1" when (signed(sigmoid_6_fu_766_p2) > signed(ap_const_lv18_1000)) else "0";
    icmp_ln469_4_fu_994_p2 <= "1" when (signed(sigmoid_8_fu_982_p2) > signed(ap_const_lv18_1000)) else "0";
    icmp_ln469_fu_130_p2 <= "1" when (signed(sigmoid_fu_118_p2) > signed(ap_const_lv18_1000)) else "0";
    icmp_ln473_1_fu_436_p2 <= "0" when (trunc_ln473_3_fu_432_p1 = ap_const_lv4_0) else "1";
    icmp_ln473_2_fu_652_p2 <= "0" when (trunc_ln473_5_fu_648_p1 = ap_const_lv4_0) else "1";
    icmp_ln473_3_fu_868_p2 <= "0" when (trunc_ln473_10_fu_864_p1 = ap_const_lv4_0) else "1";
    icmp_ln473_4_fu_1084_p2 <= "0" when (trunc_ln473_13_fu_1080_p1 = ap_const_lv4_0) else "1";
    icmp_ln473_fu_220_p2 <= "0" when (trunc_ln473_1_fu_216_p1 = ap_const_lv4_0) else "1";
    or_ln469_1_fu_368_p2 <= (tmp_7_fu_352_p3 or icmp_ln469_1_fu_346_p2);
    or_ln469_2_fu_584_p2 <= (tmp_14_fu_568_p3 or icmp_ln469_2_fu_562_p2);
    or_ln469_3_fu_800_p2 <= (tmp_21_fu_784_p3 or icmp_ln469_3_fu_778_p2);
    or_ln469_4_fu_1016_p2 <= (tmp_28_fu_1000_p3 or icmp_ln469_4_fu_994_p2);
    or_ln469_fu_152_p2 <= (tmp_fu_136_p3 or icmp_ln469_fu_130_p2);
    or_ln473_10_fu_1433_p2 <= (xor_ln473_17_fu_1427_p2 or tmp_25_reg_1724);
    or_ln473_11_fu_1473_p2 <= (and_ln473_23_fu_1460_p2 or and_ln473_21_fu_1443_p2);
    or_ln473_12_fu_1098_p2 <= (trunc_ln473_12_fu_1068_p1 or icmp_ln473_4_fu_1084_p2);
    or_ln473_13_fu_1511_p2 <= (xor_ln473_22_fu_1505_p2 or tmp_32_reg_1762);
    or_ln473_14_fu_1551_p2 <= (and_ln473_29_fu_1538_p2 or and_ln473_27_fu_1521_p2);
    or_ln473_15_fu_272_p2 <= (tmp_4_fu_256_p3 or tmp_3_fu_226_p3);
    or_ln473_16_fu_1215_p2 <= (and_ln473_4_reg_1627 or and_ln473_2_fu_1188_p2);
    or_ln473_17_fu_488_p2 <= (tmp_11_fu_472_p3 or tmp_10_fu_442_p3);
    or_ln473_18_fu_1293_p2 <= (and_ln473_8_fu_1266_p2 or and_ln473_10_reg_1665);
    or_ln473_19_fu_704_p2 <= (tmp_18_fu_688_p3 or tmp_17_fu_658_p3);
    or_ln473_1_fu_1199_p2 <= (xor_ln473_2_fu_1193_p2 or tmp_4_reg_1610);
    or_ln473_20_fu_1371_p2 <= (and_ln473_16_reg_1703 or and_ln473_14_fu_1344_p2);
    or_ln473_21_fu_920_p2 <= (tmp_25_fu_904_p3 or tmp_24_fu_874_p3);
    or_ln473_22_fu_1449_p2 <= (and_ln473_22_reg_1741 or and_ln473_20_fu_1422_p2);
    or_ln473_23_fu_1136_p2 <= (tmp_32_fu_1120_p3 or tmp_31_fu_1090_p3);
    or_ln473_24_fu_1527_p2 <= (and_ln473_28_reg_1779 or and_ln473_26_fu_1500_p2);
    or_ln473_25_fu_292_p2 <= (xor_ln473_5_fu_286_p2 or or_ln473_15_fu_272_p2);
    or_ln473_26_fu_508_p2 <= (xor_ln473_14_fu_502_p2 or or_ln473_17_fu_488_p2);
    or_ln473_27_fu_724_p2 <= (xor_ln473_21_fu_718_p2 or or_ln473_19_fu_704_p2);
    or_ln473_28_fu_940_p2 <= (xor_ln473_28_fu_934_p2 or or_ln473_21_fu_920_p2);
    or_ln473_29_fu_1156_p2 <= (xor_ln473_33_fu_1150_p2 or or_ln473_23_fu_1136_p2);
    or_ln473_2_fu_1239_p2 <= (and_ln473_5_fu_1226_p2 or and_ln473_3_fu_1209_p2);
    or_ln473_30_fu_1174_p2 <= (tmp_4_reg_1610 or tmp_3_reg_1600);
    or_ln473_31_fu_1252_p2 <= (tmp_11_reg_1648 or tmp_10_reg_1638);
    or_ln473_32_fu_1330_p2 <= (tmp_18_reg_1686 or tmp_17_reg_1676);
    or_ln473_33_fu_1408_p2 <= (tmp_25_reg_1724 or tmp_24_reg_1714);
    or_ln473_34_fu_1486_p2 <= (tmp_32_reg_1762 or tmp_31_reg_1752);
    or_ln473_3_fu_450_p2 <= (trunc_ln473_2_fu_420_p1 or icmp_ln473_1_fu_436_p2);
    or_ln473_4_fu_1277_p2 <= (xor_ln473_7_fu_1271_p2 or tmp_11_reg_1648);
    or_ln473_5_fu_1317_p2 <= (and_ln473_9_fu_1287_p2 or and_ln473_11_fu_1304_p2);
    or_ln473_6_fu_666_p2 <= (trunc_ln473_4_fu_636_p1 or icmp_ln473_2_fu_652_p2);
    or_ln473_7_fu_1355_p2 <= (xor_ln473_12_fu_1349_p2 or tmp_18_reg_1686);
    or_ln473_8_fu_1395_p2 <= (and_ln473_17_fu_1382_p2 or and_ln473_15_fu_1365_p2);
    or_ln473_9_fu_882_p2 <= (trunc_ln473_8_fu_852_p1 or icmp_ln473_3_fu_868_p2);
    or_ln473_fu_234_p2 <= (trunc_ln473_fu_204_p1 or icmp_ln473_fu_220_p2);
    select_ln469_1_fu_360_p3 <= 
        ap_const_lv13_1000 when (icmp_ln469_1_fu_346_p2(0) = '1') else 
        ap_const_lv13_0;
    select_ln469_2_fu_576_p3 <= 
        ap_const_lv13_1000 when (icmp_ln469_2_fu_562_p2(0) = '1') else 
        ap_const_lv13_0;
    select_ln469_3_fu_792_p3 <= 
        ap_const_lv13_1000 when (icmp_ln469_3_fu_778_p2(0) = '1') else 
        ap_const_lv13_0;
    select_ln469_4_fu_1008_p3 <= 
        ap_const_lv13_1000 when (icmp_ln469_4_fu_994_p2(0) = '1') else 
        ap_const_lv13_0;
    select_ln469_fu_144_p3 <= 
        ap_const_lv13_1000 when (icmp_ln469_fu_130_p2(0) = '1') else 
        ap_const_lv13_0;
    select_ln473_10_fu_1479_p3 <= 
        select_ln473_9_fu_1465_p3 when (or_ln473_11_fu_1473_p2(0) = '1') else 
        add_ln473_7_reg_1719;
    select_ln473_12_fu_1543_p3 <= 
        ap_const_lv8_7F when (and_ln473_27_fu_1521_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln473_13_fu_1557_p3 <= 
        select_ln473_12_fu_1543_p3 when (or_ln473_14_fu_1551_p2(0) = '1') else 
        add_ln473_9_reg_1757;
    select_ln473_1_fu_1245_p3 <= 
        select_ln473_fu_1231_p3 when (or_ln473_2_fu_1239_p2(0) = '1') else 
        add_ln473_1_reg_1605;
    select_ln473_3_fu_1309_p3 <= 
        ap_const_lv8_7F when (and_ln473_9_fu_1287_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln473_4_fu_1323_p3 <= 
        select_ln473_3_fu_1309_p3 when (or_ln473_5_fu_1317_p2(0) = '1') else 
        add_ln473_3_reg_1643;
    select_ln473_6_fu_1387_p3 <= 
        ap_const_lv8_7F when (and_ln473_15_fu_1365_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln473_7_fu_1401_p3 <= 
        select_ln473_6_fu_1387_p3 when (or_ln473_8_fu_1395_p2(0) = '1') else 
        add_ln473_5_reg_1681;
    select_ln473_9_fu_1465_p3 <= 
        ap_const_lv8_7F when (and_ln473_21_fu_1443_p2(0) = '1') else 
        ap_const_lv8_80;
    select_ln473_fu_1231_p3 <= 
        ap_const_lv8_7F when (and_ln473_3_fu_1209_p2(0) = '1') else 
        ap_const_lv8_80;
        sext_ln468_1_fu_318_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln468_1_fu_310_p3),18));

        sext_ln468_2_fu_534_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln468_2_fu_526_p3),18));

        sext_ln468_3_fu_750_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln468_3_fu_742_p3),18));

        sext_ln468_4_fu_966_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln468_4_fu_958_p3),18));

        sext_ln468_fu_102_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln_fu_94_p3),18));

    shl_ln1_fu_166_p3 <= (sigmoid_1_fu_158_p3 & ap_const_lv1_0);
    shl_ln468_1_fu_310_p3 <= (data_1_val & ap_const_lv1_0);
    shl_ln468_2_fu_526_p3 <= (data_2_val & ap_const_lv1_0);
    shl_ln468_3_fu_742_p3 <= (data_3_val & ap_const_lv1_0);
    shl_ln468_4_fu_958_p3 <= (data_4_val & ap_const_lv1_0);
    shl_ln473_1_fu_382_p3 <= (sigmoid_3_fu_374_p3 & ap_const_lv1_0);
    shl_ln473_2_fu_598_p3 <= (sigmoid_5_fu_590_p3 & ap_const_lv1_0);
    shl_ln473_3_fu_814_p3 <= (sigmoid_7_fu_806_p3 & ap_const_lv1_0);
    shl_ln473_4_fu_1030_p3 <= (sigmoid_9_fu_1022_p3 & ap_const_lv1_0);
    shl_ln_fu_94_p3 <= (data_0_val & ap_const_lv1_0);
    sigmoid_1_fu_158_p3 <= 
        select_ln469_fu_144_p3 when (or_ln469_fu_152_p2(0) = '1') else 
        add_ln468_2_fu_124_p2;
    sigmoid_2_fu_334_p2 <= std_logic_vector(signed(sext_ln468_1_fu_318_p1) + signed(ap_const_lv18_800));
    sigmoid_3_fu_374_p3 <= 
        select_ln469_1_fu_360_p3 when (or_ln469_1_fu_368_p2(0) = '1') else 
        add_ln468_fu_340_p2;
    sigmoid_4_fu_550_p2 <= std_logic_vector(signed(sext_ln468_2_fu_534_p1) + signed(ap_const_lv18_800));
    sigmoid_5_fu_590_p3 <= 
        select_ln469_2_fu_576_p3 when (or_ln469_2_fu_584_p2(0) = '1') else 
        add_ln468_5_fu_556_p2;
    sigmoid_6_fu_766_p2 <= std_logic_vector(signed(sext_ln468_3_fu_750_p1) + signed(ap_const_lv18_800));
    sigmoid_7_fu_806_p3 <= 
        select_ln469_3_fu_792_p3 when (or_ln469_3_fu_800_p2(0) = '1') else 
        add_ln468_7_fu_772_p2;
    sigmoid_8_fu_982_p2 <= std_logic_vector(signed(sext_ln468_4_fu_966_p1) + signed(ap_const_lv18_800));
    sigmoid_9_fu_1022_p3 <= 
        select_ln469_4_fu_1008_p3 when (or_ln469_4_fu_1016_p2(0) = '1') else 
        add_ln468_8_fu_988_p2;
    sigmoid_fu_118_p2 <= std_logic_vector(signed(sext_ln468_fu_102_p1) + signed(ap_const_lv18_800));
    tmp_10_fu_442_p3 <= sigmoid_3_fu_374_p3(11 downto 11);
    tmp_11_fu_472_p3 <= add_ln473_3_fu_466_p2(7 downto 7);
    tmp_12_fu_480_p3 <= add_ln473_2_fu_390_p2(13 downto 13);
    tmp_13_fu_494_p3 <= add_ln473_2_fu_390_p2(13 downto 13);
    tmp_14_fu_568_p3 <= sigmoid_4_fu_550_p2(17 downto 17);
    tmp_16_fu_640_p3 <= sigmoid_5_fu_590_p3(3 downto 3);
    tmp_17_fu_658_p3 <= sigmoid_5_fu_590_p3(11 downto 11);
    tmp_18_fu_688_p3 <= add_ln473_5_fu_682_p2(7 downto 7);
    tmp_19_fu_696_p3 <= add_ln473_4_fu_606_p2(13 downto 13);
    tmp_20_fu_710_p3 <= add_ln473_4_fu_606_p2(13 downto 13);
    tmp_21_fu_784_p3 <= sigmoid_6_fu_766_p2(17 downto 17);
    tmp_23_fu_856_p3 <= sigmoid_7_fu_806_p3(3 downto 3);
    tmp_24_fu_874_p3 <= sigmoid_7_fu_806_p3(11 downto 11);
    tmp_25_fu_904_p3 <= add_ln473_7_fu_898_p2(7 downto 7);
    tmp_26_fu_912_p3 <= add_ln473_6_fu_822_p2(13 downto 13);
    tmp_27_fu_926_p3 <= add_ln473_6_fu_822_p2(13 downto 13);
    tmp_28_fu_1000_p3 <= sigmoid_8_fu_982_p2(17 downto 17);
    tmp_2_fu_208_p3 <= sigmoid_1_fu_158_p3(3 downto 3);
    tmp_30_fu_1072_p3 <= sigmoid_9_fu_1022_p3(3 downto 3);
    tmp_31_fu_1090_p3 <= sigmoid_9_fu_1022_p3(11 downto 11);
    tmp_32_fu_1120_p3 <= add_ln473_9_fu_1114_p2(7 downto 7);
    tmp_33_fu_1128_p3 <= add_ln473_8_fu_1038_p2(13 downto 13);
    tmp_34_fu_1142_p3 <= add_ln473_8_fu_1038_p2(13 downto 13);
    tmp_3_fu_226_p3 <= sigmoid_1_fu_158_p3(11 downto 11);
    tmp_4_fu_256_p3 <= add_ln473_1_fu_250_p2(7 downto 7);
    tmp_5_fu_264_p3 <= add_ln473_fu_174_p2(13 downto 13);
    tmp_6_fu_278_p3 <= add_ln473_fu_174_p2(13 downto 13);
    tmp_7_fu_352_p3 <= sigmoid_2_fu_334_p2(17 downto 17);
    tmp_9_fu_424_p3 <= sigmoid_3_fu_374_p3(3 downto 3);
    tmp_fu_136_p3 <= sigmoid_fu_118_p2(17 downto 17);
    trunc_ln468_1_fu_326_p3 <= (trunc_ln468_5_fu_322_p1 & ap_const_lv1_0);
    trunc_ln468_2_fu_542_p3 <= (trunc_ln468_6_fu_538_p1 & ap_const_lv1_0);
    trunc_ln468_3_fu_758_p3 <= (trunc_ln468_7_fu_754_p1 & ap_const_lv1_0);
    trunc_ln468_4_fu_974_p3 <= (trunc_ln468_8_fu_970_p1 & ap_const_lv1_0);
    trunc_ln468_5_fu_322_p1 <= data_1_val(12 - 1 downto 0);
    trunc_ln468_6_fu_538_p1 <= data_2_val(12 - 1 downto 0);
    trunc_ln468_7_fu_754_p1 <= data_3_val(12 - 1 downto 0);
    trunc_ln468_8_fu_970_p1 <= data_4_val(12 - 1 downto 0);
    trunc_ln468_fu_106_p1 <= data_0_val(12 - 1 downto 0);
    trunc_ln473_10_fu_864_p1 <= add_ln473_6_fu_822_p2(4 - 1 downto 0);
    trunc_ln473_11_fu_1052_p4 <= sigmoid_9_fu_1022_p3(11 downto 4);
    trunc_ln473_12_fu_1068_p1 <= xor_ln473_30_fu_1062_p2(1 - 1 downto 0);
    trunc_ln473_13_fu_1080_p1 <= add_ln473_8_fu_1038_p2(4 - 1 downto 0);
    trunc_ln473_1_fu_216_p1 <= add_ln473_fu_174_p2(4 - 1 downto 0);
    trunc_ln473_2_fu_420_p1 <= xor_ln473_9_fu_414_p2(1 - 1 downto 0);
    trunc_ln473_3_fu_432_p1 <= add_ln473_2_fu_390_p2(4 - 1 downto 0);
    trunc_ln473_4_fu_636_p1 <= xor_ln473_16_fu_630_p2(1 - 1 downto 0);
    trunc_ln473_5_fu_648_p1 <= add_ln473_4_fu_606_p2(4 - 1 downto 0);
    trunc_ln473_6_fu_188_p4 <= sigmoid_1_fu_158_p3(11 downto 4);
    trunc_ln473_7_fu_836_p4 <= sigmoid_7_fu_806_p3(11 downto 4);
    trunc_ln473_8_fu_852_p1 <= xor_ln473_25_fu_846_p2(1 - 1 downto 0);
    trunc_ln473_9_fu_404_p4 <= sigmoid_3_fu_374_p3(11 downto 4);
    trunc_ln473_fu_204_p1 <= xor_ln473_fu_198_p2(1 - 1 downto 0);
    trunc_ln473_s_fu_620_p4 <= sigmoid_5_fu_590_p3(11 downto 4);
    trunc_ln_fu_110_p3 <= (trunc_ln468_fu_106_p1 & ap_const_lv1_0);
    xor_ln473_10_fu_1256_p2 <= (or_ln473_31_fu_1252_p2 xor ap_const_lv1_1);
    xor_ln473_11_fu_1262_p2 <= (tmp_12_reg_1654 xor or_ln473_17_reg_1660);
    xor_ln473_12_fu_1349_p2 <= (xor_ln473_20_fu_1340_p2 xor ap_const_lv1_1);
    xor_ln473_13_fu_1360_p2 <= (tmp_15_reg_1670 xor ap_const_lv1_1);
    xor_ln473_14_fu_502_p2 <= (tmp_13_fu_494_p3 xor ap_const_lv1_1);
    xor_ln473_15_fu_1298_p2 <= (or_ln473_18_fu_1293_p2 xor ap_const_lv1_1);
    xor_ln473_16_fu_630_p2 <= (trunc_ln473_s_fu_620_p4 xor ap_const_lv8_80);
    xor_ln473_17_fu_1427_p2 <= (xor_ln473_27_fu_1418_p2 xor ap_const_lv1_1);
    xor_ln473_18_fu_1438_p2 <= (tmp_22_reg_1708 xor ap_const_lv1_1);
    xor_ln473_19_fu_1334_p2 <= (or_ln473_32_fu_1330_p2 xor ap_const_lv1_1);
    xor_ln473_1_fu_1178_p2 <= (or_ln473_30_fu_1174_p2 xor ap_const_lv1_1);
    xor_ln473_20_fu_1340_p2 <= (tmp_19_reg_1692 xor or_ln473_19_reg_1698);
    xor_ln473_21_fu_718_p2 <= (tmp_20_fu_710_p3 xor ap_const_lv1_1);
    xor_ln473_22_fu_1505_p2 <= (xor_ln473_32_fu_1496_p2 xor ap_const_lv1_1);
    xor_ln473_23_fu_1516_p2 <= (tmp_29_reg_1746 xor ap_const_lv1_1);
    xor_ln473_24_fu_1376_p2 <= (or_ln473_20_fu_1371_p2 xor ap_const_lv1_1);
    xor_ln473_25_fu_846_p2 <= (trunc_ln473_7_fu_836_p4 xor ap_const_lv8_80);
    xor_ln473_26_fu_1412_p2 <= (or_ln473_33_fu_1408_p2 xor ap_const_lv1_1);
    xor_ln473_27_fu_1418_p2 <= (tmp_26_reg_1730 xor or_ln473_21_reg_1736);
    xor_ln473_28_fu_934_p2 <= (tmp_27_fu_926_p3 xor ap_const_lv1_1);
    xor_ln473_29_fu_1454_p2 <= (or_ln473_22_fu_1449_p2 xor ap_const_lv1_1);
    xor_ln473_2_fu_1193_p2 <= (xor_ln473_4_fu_1184_p2 xor ap_const_lv1_1);
    xor_ln473_30_fu_1062_p2 <= (trunc_ln473_11_fu_1052_p4 xor ap_const_lv8_80);
    xor_ln473_31_fu_1490_p2 <= (or_ln473_34_fu_1486_p2 xor ap_const_lv1_1);
    xor_ln473_32_fu_1496_p2 <= (tmp_33_reg_1768 xor or_ln473_23_reg_1774);
    xor_ln473_33_fu_1150_p2 <= (tmp_34_fu_1142_p3 xor ap_const_lv1_1);
    xor_ln473_34_fu_1532_p2 <= (or_ln473_24_fu_1527_p2 xor ap_const_lv1_1);
    xor_ln473_3_fu_1204_p2 <= (tmp_1_reg_1594 xor ap_const_lv1_1);
    xor_ln473_4_fu_1184_p2 <= (tmp_5_reg_1616 xor or_ln473_15_reg_1622);
    xor_ln473_5_fu_286_p2 <= (tmp_6_fu_278_p3 xor ap_const_lv1_1);
    xor_ln473_6_fu_1220_p2 <= (or_ln473_16_fu_1215_p2 xor ap_const_lv1_1);
    xor_ln473_7_fu_1271_p2 <= (xor_ln473_11_fu_1262_p2 xor ap_const_lv1_1);
    xor_ln473_8_fu_1282_p2 <= (tmp_8_reg_1632 xor ap_const_lv1_1);
    xor_ln473_9_fu_414_p2 <= (trunc_ln473_9_fu_404_p4 xor ap_const_lv8_80);
    xor_ln473_fu_198_p2 <= (trunc_ln473_6_fu_188_p4 xor ap_const_lv8_80);
    zext_ln473_1_fu_462_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln473_6_fu_456_p2),8));
    zext_ln473_2_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln473_12_fu_672_p2),8));
    zext_ln473_3_fu_894_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln473_18_fu_888_p2),8));
    zext_ln473_4_fu_1110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln473_24_fu_1104_p2),8));
    zext_ln473_fu_246_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(and_ln473_fu_240_p2),8));
end behav;
