// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_linear_ap_fixed_ap_fixed_16_6_4_0_0_PARAMEST_NN_linear_config13_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;

assign ap_ready = 1'b1;

assign ap_return_0 = data_0_val;

assign ap_return_1 = data_1_val;

assign ap_return_2 = data_2_val;

assign ap_return_3 = data_3_val;

assign ap_return_4 = data_4_val;

endmodule //ParamEst_NN_linear_ap_fixed_ap_fixed_16_6_4_0_0_PARAMEST_NN_linear_config13_s
