// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config18_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;

wire   [23:0] y_fu_82_p3;
wire   [23:0] add_ln54_fu_90_p2;
wire   [22:0] y_1_fu_106_p3;
wire  signed [23:0] sext_ln54_fu_114_p1;
wire   [23:0] add_ln54_1_fu_118_p2;
wire   [22:0] y_2_fu_134_p3;
wire  signed [23:0] sext_ln54_1_fu_142_p1;
wire   [23:0] add_ln54_2_fu_146_p2;
wire   [23:0] y_3_fu_162_p3;
wire   [23:0] add_ln54_3_fu_170_p2;
wire   [23:0] y_4_fu_186_p3;
wire   [23:0] add_ln54_4_fu_194_p2;

assign add_ln54_1_fu_118_p2 = ($signed(sext_ln54_fu_114_p1) + $signed(24'd21960));

assign add_ln54_2_fu_146_p2 = ($signed(sext_ln54_1_fu_142_p1) + $signed(24'd34736));

assign add_ln54_3_fu_170_p2 = (y_3_fu_162_p3 + 24'd256);

assign add_ln54_4_fu_194_p2 = (y_4_fu_186_p3 + 24'd61696);

assign add_ln54_fu_90_p2 = (y_fu_82_p3 + 24'd47616);

assign ap_ready = 1'b1;

assign sext_ln54_1_fu_142_p1 = $signed(y_2_fu_134_p3);

assign sext_ln54_fu_114_p1 = $signed(y_1_fu_106_p3);

assign y_1_fu_106_p3 = {{data_1_val}, {7'd0}};

assign y_2_fu_134_p3 = {{data_2_val}, {7'd0}};

assign y_3_fu_162_p3 = {{data_3_val}, {8'd0}};

assign y_4_fu_186_p3 = {{data_4_val}, {8'd0}};

assign y_fu_82_p3 = {{data_0_val}, {8'd0}};

assign ap_return_0 = {{add_ln54_fu_90_p2[23:8]}};

assign ap_return_1 = {{add_ln54_1_fu_118_p2[23:8]}};

assign ap_return_2 = {{add_ln54_2_fu_146_p2[23:8]}};

assign ap_return_3 = {{add_ln54_3_fu_170_p2[23:8]}};

assign ap_return_4 = {{add_ln54_4_fu_194_p2[23:8]}};

endmodule //ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config18_s
