// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_hard_tanh_ap_fixed_ap_fixed_8_1_4_0_0_PARAMEST_NN_hard_tanh_config14_s (
        ap_clk,
        ap_rst,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
input   ap_ce;

reg[7:0] ap_return_0;
reg[7:0] ap_return_1;
reg[7:0] ap_return_2;
reg[7:0] ap_return_3;
reg[7:0] ap_return_4;

reg   [0:0] tmp_1_reg_1594;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] tmp_3_fu_226_p3;
reg   [0:0] tmp_3_reg_1600;
wire   [7:0] add_ln473_1_fu_250_p2;
reg   [7:0] add_ln473_1_reg_1605;
wire   [0:0] tmp_4_fu_256_p3;
reg   [0:0] tmp_4_reg_1610;
wire   [0:0] tmp_5_fu_264_p3;
reg   [0:0] tmp_5_reg_1616;
wire   [0:0] or_ln473_15_fu_272_p2;
reg   [0:0] or_ln473_15_reg_1622;
wire   [0:0] and_ln473_4_fu_304_p2;
reg   [0:0] and_ln473_4_reg_1627;
reg   [0:0] tmp_8_reg_1632;
wire   [0:0] tmp_10_fu_442_p3;
reg   [0:0] tmp_10_reg_1638;
wire   [7:0] add_ln473_3_fu_466_p2;
reg   [7:0] add_ln473_3_reg_1643;
wire   [0:0] tmp_11_fu_472_p3;
reg   [0:0] tmp_11_reg_1648;
wire   [0:0] tmp_12_fu_480_p3;
reg   [0:0] tmp_12_reg_1654;
wire   [0:0] or_ln473_17_fu_488_p2;
reg   [0:0] or_ln473_17_reg_1660;
wire   [0:0] and_ln473_10_fu_520_p2;
reg   [0:0] and_ln473_10_reg_1665;
reg   [0:0] tmp_15_reg_1670;
wire   [0:0] tmp_17_fu_658_p3;
reg   [0:0] tmp_17_reg_1676;
wire   [7:0] add_ln473_5_fu_682_p2;
reg   [7:0] add_ln473_5_reg_1681;
wire   [0:0] tmp_18_fu_688_p3;
reg   [0:0] tmp_18_reg_1686;
wire   [0:0] tmp_19_fu_696_p3;
reg   [0:0] tmp_19_reg_1692;
wire   [0:0] or_ln473_19_fu_704_p2;
reg   [0:0] or_ln473_19_reg_1698;
wire   [0:0] and_ln473_16_fu_736_p2;
reg   [0:0] and_ln473_16_reg_1703;
reg   [0:0] tmp_22_reg_1708;
wire   [0:0] tmp_24_fu_874_p3;
reg   [0:0] tmp_24_reg_1714;
wire   [7:0] add_ln473_7_fu_898_p2;
reg   [7:0] add_ln473_7_reg_1719;
wire   [0:0] tmp_25_fu_904_p3;
reg   [0:0] tmp_25_reg_1724;
wire   [0:0] tmp_26_fu_912_p3;
reg   [0:0] tmp_26_reg_1730;
wire   [0:0] or_ln473_21_fu_920_p2;
reg   [0:0] or_ln473_21_reg_1736;
wire   [0:0] and_ln473_22_fu_952_p2;
reg   [0:0] and_ln473_22_reg_1741;
reg   [0:0] tmp_29_reg_1746;
wire   [0:0] tmp_31_fu_1090_p3;
reg   [0:0] tmp_31_reg_1752;
wire   [7:0] add_ln473_9_fu_1114_p2;
reg   [7:0] add_ln473_9_reg_1757;
wire   [0:0] tmp_32_fu_1120_p3;
reg   [0:0] tmp_32_reg_1762;
wire   [0:0] tmp_33_fu_1128_p3;
reg   [0:0] tmp_33_reg_1768;
wire   [0:0] or_ln473_23_fu_1136_p2;
reg   [0:0] or_ln473_23_reg_1774;
wire   [0:0] and_ln473_28_fu_1168_p2;
reg   [0:0] and_ln473_28_reg_1779;
wire    ap_block_pp0_stage0;
wire   [16:0] shl_ln_fu_94_p3;
wire   [11:0] trunc_ln468_fu_106_p1;
wire  signed [17:0] sext_ln468_fu_102_p1;
wire   [12:0] trunc_ln_fu_110_p3;
wire   [17:0] sigmoid_fu_118_p2;
wire   [0:0] icmp_ln469_fu_130_p2;
wire   [0:0] tmp_fu_136_p3;
wire   [0:0] or_ln469_fu_152_p2;
wire   [12:0] select_ln469_fu_144_p3;
wire   [12:0] add_ln468_2_fu_124_p2;
wire   [12:0] sigmoid_1_fu_158_p3;
wire   [13:0] shl_ln1_fu_166_p3;
wire   [13:0] add_ln473_fu_174_p2;
wire   [7:0] trunc_ln473_6_fu_188_p4;
wire   [7:0] xor_ln473_fu_198_p2;
wire   [3:0] trunc_ln473_1_fu_216_p1;
wire   [0:0] trunc_ln473_fu_204_p1;
wire   [0:0] icmp_ln473_fu_220_p2;
wire   [0:0] or_ln473_fu_234_p2;
wire   [0:0] tmp_2_fu_208_p3;
wire   [0:0] and_ln473_fu_240_p2;
wire   [7:0] zext_ln473_fu_246_p1;
wire   [0:0] tmp_6_fu_278_p3;
wire   [0:0] xor_ln473_5_fu_286_p2;
wire   [0:0] or_ln473_25_fu_292_p2;
wire   [0:0] and_ln473_1_fu_298_p2;
wire   [16:0] shl_ln468_1_fu_310_p3;
wire   [11:0] trunc_ln468_5_fu_322_p1;
wire  signed [17:0] sext_ln468_1_fu_318_p1;
wire   [12:0] trunc_ln468_1_fu_326_p3;
wire   [17:0] sigmoid_2_fu_334_p2;
wire   [0:0] icmp_ln469_1_fu_346_p2;
wire   [0:0] tmp_7_fu_352_p3;
wire   [0:0] or_ln469_1_fu_368_p2;
wire   [12:0] select_ln469_1_fu_360_p3;
wire   [12:0] add_ln468_fu_340_p2;
wire   [12:0] sigmoid_3_fu_374_p3;
wire   [13:0] shl_ln473_1_fu_382_p3;
wire   [13:0] add_ln473_2_fu_390_p2;
wire   [7:0] trunc_ln473_9_fu_404_p4;
wire   [7:0] xor_ln473_9_fu_414_p2;
wire   [3:0] trunc_ln473_3_fu_432_p1;
wire   [0:0] trunc_ln473_2_fu_420_p1;
wire   [0:0] icmp_ln473_1_fu_436_p2;
wire   [0:0] or_ln473_3_fu_450_p2;
wire   [0:0] tmp_9_fu_424_p3;
wire   [0:0] and_ln473_6_fu_456_p2;
wire   [7:0] zext_ln473_1_fu_462_p1;
wire   [0:0] tmp_13_fu_494_p3;
wire   [0:0] xor_ln473_14_fu_502_p2;
wire   [0:0] or_ln473_26_fu_508_p2;
wire   [0:0] and_ln473_7_fu_514_p2;
wire   [16:0] shl_ln468_2_fu_526_p3;
wire   [11:0] trunc_ln468_6_fu_538_p1;
wire  signed [17:0] sext_ln468_2_fu_534_p1;
wire   [12:0] trunc_ln468_2_fu_542_p3;
wire   [17:0] sigmoid_4_fu_550_p2;
wire   [0:0] icmp_ln469_2_fu_562_p2;
wire   [0:0] tmp_14_fu_568_p3;
wire   [0:0] or_ln469_2_fu_584_p2;
wire   [12:0] select_ln469_2_fu_576_p3;
wire   [12:0] add_ln468_5_fu_556_p2;
wire   [12:0] sigmoid_5_fu_590_p3;
wire   [13:0] shl_ln473_2_fu_598_p3;
wire   [13:0] add_ln473_4_fu_606_p2;
wire   [7:0] trunc_ln473_s_fu_620_p4;
wire   [7:0] xor_ln473_16_fu_630_p2;
wire   [3:0] trunc_ln473_5_fu_648_p1;
wire   [0:0] trunc_ln473_4_fu_636_p1;
wire   [0:0] icmp_ln473_2_fu_652_p2;
wire   [0:0] or_ln473_6_fu_666_p2;
wire   [0:0] tmp_16_fu_640_p3;
wire   [0:0] and_ln473_12_fu_672_p2;
wire   [7:0] zext_ln473_2_fu_678_p1;
wire   [0:0] tmp_20_fu_710_p3;
wire   [0:0] xor_ln473_21_fu_718_p2;
wire   [0:0] or_ln473_27_fu_724_p2;
wire   [0:0] and_ln473_13_fu_730_p2;
wire   [16:0] shl_ln468_3_fu_742_p3;
wire   [11:0] trunc_ln468_7_fu_754_p1;
wire  signed [17:0] sext_ln468_3_fu_750_p1;
wire   [12:0] trunc_ln468_3_fu_758_p3;
wire   [17:0] sigmoid_6_fu_766_p2;
wire   [0:0] icmp_ln469_3_fu_778_p2;
wire   [0:0] tmp_21_fu_784_p3;
wire   [0:0] or_ln469_3_fu_800_p2;
wire   [12:0] select_ln469_3_fu_792_p3;
wire   [12:0] add_ln468_7_fu_772_p2;
wire   [12:0] sigmoid_7_fu_806_p3;
wire   [13:0] shl_ln473_3_fu_814_p3;
wire   [13:0] add_ln473_6_fu_822_p2;
wire   [7:0] trunc_ln473_7_fu_836_p4;
wire   [7:0] xor_ln473_25_fu_846_p2;
wire   [3:0] trunc_ln473_10_fu_864_p1;
wire   [0:0] trunc_ln473_8_fu_852_p1;
wire   [0:0] icmp_ln473_3_fu_868_p2;
wire   [0:0] or_ln473_9_fu_882_p2;
wire   [0:0] tmp_23_fu_856_p3;
wire   [0:0] and_ln473_18_fu_888_p2;
wire   [7:0] zext_ln473_3_fu_894_p1;
wire   [0:0] tmp_27_fu_926_p3;
wire   [0:0] xor_ln473_28_fu_934_p2;
wire   [0:0] or_ln473_28_fu_940_p2;
wire   [0:0] and_ln473_19_fu_946_p2;
wire   [16:0] shl_ln468_4_fu_958_p3;
wire   [11:0] trunc_ln468_8_fu_970_p1;
wire  signed [17:0] sext_ln468_4_fu_966_p1;
wire   [12:0] trunc_ln468_4_fu_974_p3;
wire   [17:0] sigmoid_8_fu_982_p2;
wire   [0:0] icmp_ln469_4_fu_994_p2;
wire   [0:0] tmp_28_fu_1000_p3;
wire   [0:0] or_ln469_4_fu_1016_p2;
wire   [12:0] select_ln469_4_fu_1008_p3;
wire   [12:0] add_ln468_8_fu_988_p2;
wire   [12:0] sigmoid_9_fu_1022_p3;
wire   [13:0] shl_ln473_4_fu_1030_p3;
wire   [13:0] add_ln473_8_fu_1038_p2;
wire   [7:0] trunc_ln473_11_fu_1052_p4;
wire   [7:0] xor_ln473_30_fu_1062_p2;
wire   [3:0] trunc_ln473_13_fu_1080_p1;
wire   [0:0] trunc_ln473_12_fu_1068_p1;
wire   [0:0] icmp_ln473_4_fu_1084_p2;
wire   [0:0] or_ln473_12_fu_1098_p2;
wire   [0:0] tmp_30_fu_1072_p3;
wire   [0:0] and_ln473_24_fu_1104_p2;
wire   [7:0] zext_ln473_4_fu_1110_p1;
wire   [0:0] tmp_34_fu_1142_p3;
wire   [0:0] xor_ln473_33_fu_1150_p2;
wire   [0:0] or_ln473_29_fu_1156_p2;
wire   [0:0] and_ln473_25_fu_1162_p2;
wire   [0:0] or_ln473_30_fu_1174_p2;
wire   [0:0] xor_ln473_1_fu_1178_p2;
wire   [0:0] xor_ln473_4_fu_1184_p2;
wire   [0:0] xor_ln473_2_fu_1193_p2;
wire   [0:0] or_ln473_1_fu_1199_p2;
wire   [0:0] xor_ln473_3_fu_1204_p2;
wire   [0:0] and_ln473_2_fu_1188_p2;
wire   [0:0] or_ln473_16_fu_1215_p2;
wire   [0:0] xor_ln473_6_fu_1220_p2;
wire   [0:0] and_ln473_3_fu_1209_p2;
wire   [0:0] and_ln473_5_fu_1226_p2;
wire   [0:0] or_ln473_2_fu_1239_p2;
wire   [7:0] select_ln473_fu_1231_p3;
wire   [0:0] or_ln473_31_fu_1252_p2;
wire   [0:0] xor_ln473_10_fu_1256_p2;
wire   [0:0] xor_ln473_11_fu_1262_p2;
wire   [0:0] xor_ln473_7_fu_1271_p2;
wire   [0:0] or_ln473_4_fu_1277_p2;
wire   [0:0] xor_ln473_8_fu_1282_p2;
wire   [0:0] and_ln473_8_fu_1266_p2;
wire   [0:0] or_ln473_18_fu_1293_p2;
wire   [0:0] xor_ln473_15_fu_1298_p2;
wire   [0:0] and_ln473_9_fu_1287_p2;
wire   [0:0] and_ln473_11_fu_1304_p2;
wire   [0:0] or_ln473_5_fu_1317_p2;
wire   [7:0] select_ln473_3_fu_1309_p3;
wire   [0:0] or_ln473_32_fu_1330_p2;
wire   [0:0] xor_ln473_19_fu_1334_p2;
wire   [0:0] xor_ln473_20_fu_1340_p2;
wire   [0:0] xor_ln473_12_fu_1349_p2;
wire   [0:0] or_ln473_7_fu_1355_p2;
wire   [0:0] xor_ln473_13_fu_1360_p2;
wire   [0:0] and_ln473_14_fu_1344_p2;
wire   [0:0] or_ln473_20_fu_1371_p2;
wire   [0:0] xor_ln473_24_fu_1376_p2;
wire   [0:0] and_ln473_15_fu_1365_p2;
wire   [0:0] and_ln473_17_fu_1382_p2;
wire   [0:0] or_ln473_8_fu_1395_p2;
wire   [7:0] select_ln473_6_fu_1387_p3;
wire   [0:0] or_ln473_33_fu_1408_p2;
wire   [0:0] xor_ln473_26_fu_1412_p2;
wire   [0:0] xor_ln473_27_fu_1418_p2;
wire   [0:0] xor_ln473_17_fu_1427_p2;
wire   [0:0] or_ln473_10_fu_1433_p2;
wire   [0:0] xor_ln473_18_fu_1438_p2;
wire   [0:0] and_ln473_20_fu_1422_p2;
wire   [0:0] or_ln473_22_fu_1449_p2;
wire   [0:0] xor_ln473_29_fu_1454_p2;
wire   [0:0] and_ln473_21_fu_1443_p2;
wire   [0:0] and_ln473_23_fu_1460_p2;
wire   [0:0] or_ln473_11_fu_1473_p2;
wire   [7:0] select_ln473_9_fu_1465_p3;
wire   [0:0] or_ln473_34_fu_1486_p2;
wire   [0:0] xor_ln473_31_fu_1490_p2;
wire   [0:0] xor_ln473_32_fu_1496_p2;
wire   [0:0] xor_ln473_22_fu_1505_p2;
wire   [0:0] or_ln473_13_fu_1511_p2;
wire   [0:0] xor_ln473_23_fu_1516_p2;
wire   [0:0] and_ln473_26_fu_1500_p2;
wire   [0:0] or_ln473_24_fu_1527_p2;
wire   [0:0] xor_ln473_34_fu_1532_p2;
wire   [0:0] and_ln473_27_fu_1521_p2;
wire   [0:0] and_ln473_29_fu_1538_p2;
wire   [0:0] or_ln473_14_fu_1551_p2;
wire   [7:0] select_ln473_12_fu_1543_p3;
wire   [7:0] select_ln473_1_fu_1245_p3;
wire   [7:0] select_ln473_4_fu_1323_p3;
wire   [7:0] select_ln473_7_fu_1401_p3;
wire   [7:0] select_ln473_10_fu_1479_p3;
wire   [7:0] select_ln473_13_fu_1557_p3;
reg    ap_ce_reg;
reg   [7:0] ap_return_0_int_reg;
reg   [7:0] ap_return_1_int_reg;
reg   [7:0] ap_return_2_int_reg;
reg   [7:0] ap_return_3_int_reg;
reg   [7:0] ap_return_4_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == 1'b1))) begin
        add_ln473_1_reg_1605 <= add_ln473_1_fu_250_p2;
        add_ln473_3_reg_1643 <= add_ln473_3_fu_466_p2;
        add_ln473_5_reg_1681 <= add_ln473_5_fu_682_p2;
        add_ln473_7_reg_1719 <= add_ln473_7_fu_898_p2;
        add_ln473_9_reg_1757 <= add_ln473_9_fu_1114_p2;
        and_ln473_10_reg_1665 <= and_ln473_10_fu_520_p2;
        and_ln473_16_reg_1703 <= and_ln473_16_fu_736_p2;
        and_ln473_22_reg_1741 <= and_ln473_22_fu_952_p2;
        and_ln473_28_reg_1779 <= and_ln473_28_fu_1168_p2;
        and_ln473_4_reg_1627 <= and_ln473_4_fu_304_p2;
        or_ln473_15_reg_1622 <= or_ln473_15_fu_272_p2;
        or_ln473_17_reg_1660 <= or_ln473_17_fu_488_p2;
        or_ln473_19_reg_1698 <= or_ln473_19_fu_704_p2;
        or_ln473_21_reg_1736 <= or_ln473_21_fu_920_p2;
        or_ln473_23_reg_1774 <= or_ln473_23_fu_1136_p2;
        tmp_10_reg_1638 <= sigmoid_3_fu_374_p3[32'd11];
        tmp_11_reg_1648 <= add_ln473_3_fu_466_p2[32'd7];
        tmp_12_reg_1654 <= add_ln473_2_fu_390_p2[32'd13];
        tmp_15_reg_1670 <= add_ln473_4_fu_606_p2[32'd13];
        tmp_17_reg_1676 <= sigmoid_5_fu_590_p3[32'd11];
        tmp_18_reg_1686 <= add_ln473_5_fu_682_p2[32'd7];
        tmp_19_reg_1692 <= add_ln473_4_fu_606_p2[32'd13];
        tmp_1_reg_1594 <= add_ln473_fu_174_p2[32'd13];
        tmp_22_reg_1708 <= add_ln473_6_fu_822_p2[32'd13];
        tmp_24_reg_1714 <= sigmoid_7_fu_806_p3[32'd11];
        tmp_25_reg_1724 <= add_ln473_7_fu_898_p2[32'd7];
        tmp_26_reg_1730 <= add_ln473_6_fu_822_p2[32'd13];
        tmp_29_reg_1746 <= add_ln473_8_fu_1038_p2[32'd13];
        tmp_31_reg_1752 <= sigmoid_9_fu_1022_p3[32'd11];
        tmp_32_reg_1762 <= add_ln473_9_fu_1114_p2[32'd7];
        tmp_33_reg_1768 <= add_ln473_8_fu_1038_p2[32'd13];
        tmp_3_reg_1600 <= sigmoid_1_fu_158_p3[32'd11];
        tmp_4_reg_1610 <= add_ln473_1_fu_250_p2[32'd7];
        tmp_5_reg_1616 <= add_ln473_fu_174_p2[32'd13];
        tmp_8_reg_1632 <= add_ln473_2_fu_390_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_0_int_reg <= select_ln473_1_fu_1245_p3;
        ap_return_1_int_reg <= select_ln473_4_fu_1323_p3;
        ap_return_2_int_reg <= select_ln473_7_fu_1401_p3;
        ap_return_3_int_reg <= select_ln473_10_fu_1479_p3;
        ap_return_4_int_reg <= select_ln473_13_fu_1557_p3;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_0 = ap_return_0_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_0 = select_ln473_1_fu_1245_p3;
    end else begin
        ap_return_0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_1 = ap_return_1_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_1 = select_ln473_4_fu_1323_p3;
    end else begin
        ap_return_1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_2 = ap_return_2_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_2 = select_ln473_7_fu_1401_p3;
    end else begin
        ap_return_2 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_3 = ap_return_3_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_3 = select_ln473_10_fu_1479_p3;
    end else begin
        ap_return_3 = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return_4 = ap_return_4_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return_4 = select_ln473_13_fu_1557_p3;
    end else begin
        ap_return_4 = 'bx;
    end
end

assign add_ln468_2_fu_124_p2 = (trunc_ln_fu_110_p3 + 13'd2048);

assign add_ln468_5_fu_556_p2 = (trunc_ln468_2_fu_542_p3 + 13'd2048);

assign add_ln468_7_fu_772_p2 = (trunc_ln468_3_fu_758_p3 + 13'd2048);

assign add_ln468_8_fu_988_p2 = (trunc_ln468_4_fu_974_p3 + 13'd2048);

assign add_ln468_fu_340_p2 = (trunc_ln468_1_fu_326_p3 + 13'd2048);

assign add_ln473_1_fu_250_p2 = (xor_ln473_fu_198_p2 + zext_ln473_fu_246_p1);

assign add_ln473_2_fu_390_p2 = ($signed(shl_ln473_1_fu_382_p3) + $signed(14'd12288));

assign add_ln473_3_fu_466_p2 = (xor_ln473_9_fu_414_p2 + zext_ln473_1_fu_462_p1);

assign add_ln473_4_fu_606_p2 = ($signed(shl_ln473_2_fu_598_p3) + $signed(14'd12288));

assign add_ln473_5_fu_682_p2 = (xor_ln473_16_fu_630_p2 + zext_ln473_2_fu_678_p1);

assign add_ln473_6_fu_822_p2 = ($signed(shl_ln473_3_fu_814_p3) + $signed(14'd12288));

assign add_ln473_7_fu_898_p2 = (xor_ln473_25_fu_846_p2 + zext_ln473_3_fu_894_p1);

assign add_ln473_8_fu_1038_p2 = ($signed(shl_ln473_4_fu_1030_p3) + $signed(14'd12288));

assign add_ln473_9_fu_1114_p2 = (xor_ln473_30_fu_1062_p2 + zext_ln473_4_fu_1110_p1);

assign add_ln473_fu_174_p2 = ($signed(shl_ln1_fu_166_p3) + $signed(14'd12288));

assign and_ln473_10_fu_520_p2 = (tmp_11_fu_472_p3 & and_ln473_7_fu_514_p2);

assign and_ln473_11_fu_1304_p2 = (xor_ln473_15_fu_1298_p2 & tmp_8_reg_1632);

assign and_ln473_12_fu_672_p2 = (tmp_16_fu_640_p3 & or_ln473_6_fu_666_p2);

assign and_ln473_13_fu_730_p2 = (tmp_19_fu_696_p3 & or_ln473_27_fu_724_p2);

assign and_ln473_14_fu_1344_p2 = (xor_ln473_19_fu_1334_p2 & tmp_19_reg_1692);

assign and_ln473_15_fu_1365_p2 = (xor_ln473_13_fu_1360_p2 & or_ln473_7_fu_1355_p2);

assign and_ln473_16_fu_736_p2 = (tmp_18_fu_688_p3 & and_ln473_13_fu_730_p2);

assign and_ln473_17_fu_1382_p2 = (xor_ln473_24_fu_1376_p2 & tmp_15_reg_1670);

assign and_ln473_18_fu_888_p2 = (tmp_23_fu_856_p3 & or_ln473_9_fu_882_p2);

assign and_ln473_19_fu_946_p2 = (tmp_26_fu_912_p3 & or_ln473_28_fu_940_p2);

assign and_ln473_1_fu_298_p2 = (tmp_5_fu_264_p3 & or_ln473_25_fu_292_p2);

assign and_ln473_20_fu_1422_p2 = (xor_ln473_26_fu_1412_p2 & tmp_26_reg_1730);

assign and_ln473_21_fu_1443_p2 = (xor_ln473_18_fu_1438_p2 & or_ln473_10_fu_1433_p2);

assign and_ln473_22_fu_952_p2 = (tmp_25_fu_904_p3 & and_ln473_19_fu_946_p2);

assign and_ln473_23_fu_1460_p2 = (xor_ln473_29_fu_1454_p2 & tmp_22_reg_1708);

assign and_ln473_24_fu_1104_p2 = (tmp_30_fu_1072_p3 & or_ln473_12_fu_1098_p2);

assign and_ln473_25_fu_1162_p2 = (tmp_33_fu_1128_p3 & or_ln473_29_fu_1156_p2);

assign and_ln473_26_fu_1500_p2 = (xor_ln473_31_fu_1490_p2 & tmp_33_reg_1768);

assign and_ln473_27_fu_1521_p2 = (xor_ln473_23_fu_1516_p2 & or_ln473_13_fu_1511_p2);

assign and_ln473_28_fu_1168_p2 = (tmp_32_fu_1120_p3 & and_ln473_25_fu_1162_p2);

assign and_ln473_29_fu_1538_p2 = (xor_ln473_34_fu_1532_p2 & tmp_29_reg_1746);

assign and_ln473_2_fu_1188_p2 = (xor_ln473_1_fu_1178_p2 & tmp_5_reg_1616);

assign and_ln473_3_fu_1209_p2 = (xor_ln473_3_fu_1204_p2 & or_ln473_1_fu_1199_p2);

assign and_ln473_4_fu_304_p2 = (tmp_4_fu_256_p3 & and_ln473_1_fu_298_p2);

assign and_ln473_5_fu_1226_p2 = (xor_ln473_6_fu_1220_p2 & tmp_1_reg_1594);

assign and_ln473_6_fu_456_p2 = (tmp_9_fu_424_p3 & or_ln473_3_fu_450_p2);

assign and_ln473_7_fu_514_p2 = (tmp_12_fu_480_p3 & or_ln473_26_fu_508_p2);

assign and_ln473_8_fu_1266_p2 = (xor_ln473_10_fu_1256_p2 & tmp_12_reg_1654);

assign and_ln473_9_fu_1287_p2 = (xor_ln473_8_fu_1282_p2 & or_ln473_4_fu_1277_p2);

assign and_ln473_fu_240_p2 = (tmp_2_fu_208_p3 & or_ln473_fu_234_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign icmp_ln469_1_fu_346_p2 = (($signed(sigmoid_2_fu_334_p2) > $signed(18'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln469_2_fu_562_p2 = (($signed(sigmoid_4_fu_550_p2) > $signed(18'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln469_3_fu_778_p2 = (($signed(sigmoid_6_fu_766_p2) > $signed(18'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln469_4_fu_994_p2 = (($signed(sigmoid_8_fu_982_p2) > $signed(18'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln469_fu_130_p2 = (($signed(sigmoid_fu_118_p2) > $signed(18'd4096)) ? 1'b1 : 1'b0);

assign icmp_ln473_1_fu_436_p2 = ((trunc_ln473_3_fu_432_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln473_2_fu_652_p2 = ((trunc_ln473_5_fu_648_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln473_3_fu_868_p2 = ((trunc_ln473_10_fu_864_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln473_4_fu_1084_p2 = ((trunc_ln473_13_fu_1080_p1 != 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln473_fu_220_p2 = ((trunc_ln473_1_fu_216_p1 != 4'd0) ? 1'b1 : 1'b0);

assign or_ln469_1_fu_368_p2 = (tmp_7_fu_352_p3 | icmp_ln469_1_fu_346_p2);

assign or_ln469_2_fu_584_p2 = (tmp_14_fu_568_p3 | icmp_ln469_2_fu_562_p2);

assign or_ln469_3_fu_800_p2 = (tmp_21_fu_784_p3 | icmp_ln469_3_fu_778_p2);

assign or_ln469_4_fu_1016_p2 = (tmp_28_fu_1000_p3 | icmp_ln469_4_fu_994_p2);

assign or_ln469_fu_152_p2 = (tmp_fu_136_p3 | icmp_ln469_fu_130_p2);

assign or_ln473_10_fu_1433_p2 = (xor_ln473_17_fu_1427_p2 | tmp_25_reg_1724);

assign or_ln473_11_fu_1473_p2 = (and_ln473_23_fu_1460_p2 | and_ln473_21_fu_1443_p2);

assign or_ln473_12_fu_1098_p2 = (trunc_ln473_12_fu_1068_p1 | icmp_ln473_4_fu_1084_p2);

assign or_ln473_13_fu_1511_p2 = (xor_ln473_22_fu_1505_p2 | tmp_32_reg_1762);

assign or_ln473_14_fu_1551_p2 = (and_ln473_29_fu_1538_p2 | and_ln473_27_fu_1521_p2);

assign or_ln473_15_fu_272_p2 = (tmp_4_fu_256_p3 | tmp_3_fu_226_p3);

assign or_ln473_16_fu_1215_p2 = (and_ln473_4_reg_1627 | and_ln473_2_fu_1188_p2);

assign or_ln473_17_fu_488_p2 = (tmp_11_fu_472_p3 | tmp_10_fu_442_p3);

assign or_ln473_18_fu_1293_p2 = (and_ln473_8_fu_1266_p2 | and_ln473_10_reg_1665);

assign or_ln473_19_fu_704_p2 = (tmp_18_fu_688_p3 | tmp_17_fu_658_p3);

assign or_ln473_1_fu_1199_p2 = (xor_ln473_2_fu_1193_p2 | tmp_4_reg_1610);

assign or_ln473_20_fu_1371_p2 = (and_ln473_16_reg_1703 | and_ln473_14_fu_1344_p2);

assign or_ln473_21_fu_920_p2 = (tmp_25_fu_904_p3 | tmp_24_fu_874_p3);

assign or_ln473_22_fu_1449_p2 = (and_ln473_22_reg_1741 | and_ln473_20_fu_1422_p2);

assign or_ln473_23_fu_1136_p2 = (tmp_32_fu_1120_p3 | tmp_31_fu_1090_p3);

assign or_ln473_24_fu_1527_p2 = (and_ln473_28_reg_1779 | and_ln473_26_fu_1500_p2);

assign or_ln473_25_fu_292_p2 = (xor_ln473_5_fu_286_p2 | or_ln473_15_fu_272_p2);

assign or_ln473_26_fu_508_p2 = (xor_ln473_14_fu_502_p2 | or_ln473_17_fu_488_p2);

assign or_ln473_27_fu_724_p2 = (xor_ln473_21_fu_718_p2 | or_ln473_19_fu_704_p2);

assign or_ln473_28_fu_940_p2 = (xor_ln473_28_fu_934_p2 | or_ln473_21_fu_920_p2);

assign or_ln473_29_fu_1156_p2 = (xor_ln473_33_fu_1150_p2 | or_ln473_23_fu_1136_p2);

assign or_ln473_2_fu_1239_p2 = (and_ln473_5_fu_1226_p2 | and_ln473_3_fu_1209_p2);

assign or_ln473_30_fu_1174_p2 = (tmp_4_reg_1610 | tmp_3_reg_1600);

assign or_ln473_31_fu_1252_p2 = (tmp_11_reg_1648 | tmp_10_reg_1638);

assign or_ln473_32_fu_1330_p2 = (tmp_18_reg_1686 | tmp_17_reg_1676);

assign or_ln473_33_fu_1408_p2 = (tmp_25_reg_1724 | tmp_24_reg_1714);

assign or_ln473_34_fu_1486_p2 = (tmp_32_reg_1762 | tmp_31_reg_1752);

assign or_ln473_3_fu_450_p2 = (trunc_ln473_2_fu_420_p1 | icmp_ln473_1_fu_436_p2);

assign or_ln473_4_fu_1277_p2 = (xor_ln473_7_fu_1271_p2 | tmp_11_reg_1648);

assign or_ln473_5_fu_1317_p2 = (and_ln473_9_fu_1287_p2 | and_ln473_11_fu_1304_p2);

assign or_ln473_6_fu_666_p2 = (trunc_ln473_4_fu_636_p1 | icmp_ln473_2_fu_652_p2);

assign or_ln473_7_fu_1355_p2 = (xor_ln473_12_fu_1349_p2 | tmp_18_reg_1686);

assign or_ln473_8_fu_1395_p2 = (and_ln473_17_fu_1382_p2 | and_ln473_15_fu_1365_p2);

assign or_ln473_9_fu_882_p2 = (trunc_ln473_8_fu_852_p1 | icmp_ln473_3_fu_868_p2);

assign or_ln473_fu_234_p2 = (trunc_ln473_fu_204_p1 | icmp_ln473_fu_220_p2);

assign select_ln469_1_fu_360_p3 = ((icmp_ln469_1_fu_346_p2[0:0] == 1'b1) ? 13'd4096 : 13'd0);

assign select_ln469_2_fu_576_p3 = ((icmp_ln469_2_fu_562_p2[0:0] == 1'b1) ? 13'd4096 : 13'd0);

assign select_ln469_3_fu_792_p3 = ((icmp_ln469_3_fu_778_p2[0:0] == 1'b1) ? 13'd4096 : 13'd0);

assign select_ln469_4_fu_1008_p3 = ((icmp_ln469_4_fu_994_p2[0:0] == 1'b1) ? 13'd4096 : 13'd0);

assign select_ln469_fu_144_p3 = ((icmp_ln469_fu_130_p2[0:0] == 1'b1) ? 13'd4096 : 13'd0);

assign select_ln473_10_fu_1479_p3 = ((or_ln473_11_fu_1473_p2[0:0] == 1'b1) ? select_ln473_9_fu_1465_p3 : add_ln473_7_reg_1719);

assign select_ln473_12_fu_1543_p3 = ((and_ln473_27_fu_1521_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln473_13_fu_1557_p3 = ((or_ln473_14_fu_1551_p2[0:0] == 1'b1) ? select_ln473_12_fu_1543_p3 : add_ln473_9_reg_1757);

assign select_ln473_1_fu_1245_p3 = ((or_ln473_2_fu_1239_p2[0:0] == 1'b1) ? select_ln473_fu_1231_p3 : add_ln473_1_reg_1605);

assign select_ln473_3_fu_1309_p3 = ((and_ln473_9_fu_1287_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln473_4_fu_1323_p3 = ((or_ln473_5_fu_1317_p2[0:0] == 1'b1) ? select_ln473_3_fu_1309_p3 : add_ln473_3_reg_1643);

assign select_ln473_6_fu_1387_p3 = ((and_ln473_15_fu_1365_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln473_7_fu_1401_p3 = ((or_ln473_8_fu_1395_p2[0:0] == 1'b1) ? select_ln473_6_fu_1387_p3 : add_ln473_5_reg_1681);

assign select_ln473_9_fu_1465_p3 = ((and_ln473_21_fu_1443_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign select_ln473_fu_1231_p3 = ((and_ln473_3_fu_1209_p2[0:0] == 1'b1) ? 8'd127 : 8'd128);

assign sext_ln468_1_fu_318_p1 = $signed(shl_ln468_1_fu_310_p3);

assign sext_ln468_2_fu_534_p1 = $signed(shl_ln468_2_fu_526_p3);

assign sext_ln468_3_fu_750_p1 = $signed(shl_ln468_3_fu_742_p3);

assign sext_ln468_4_fu_966_p1 = $signed(shl_ln468_4_fu_958_p3);

assign sext_ln468_fu_102_p1 = $signed(shl_ln_fu_94_p3);

assign shl_ln1_fu_166_p3 = {{sigmoid_1_fu_158_p3}, {1'd0}};

assign shl_ln468_1_fu_310_p3 = {{data_1_val}, {1'd0}};

assign shl_ln468_2_fu_526_p3 = {{data_2_val}, {1'd0}};

assign shl_ln468_3_fu_742_p3 = {{data_3_val}, {1'd0}};

assign shl_ln468_4_fu_958_p3 = {{data_4_val}, {1'd0}};

assign shl_ln473_1_fu_382_p3 = {{sigmoid_3_fu_374_p3}, {1'd0}};

assign shl_ln473_2_fu_598_p3 = {{sigmoid_5_fu_590_p3}, {1'd0}};

assign shl_ln473_3_fu_814_p3 = {{sigmoid_7_fu_806_p3}, {1'd0}};

assign shl_ln473_4_fu_1030_p3 = {{sigmoid_9_fu_1022_p3}, {1'd0}};

assign shl_ln_fu_94_p3 = {{data_0_val}, {1'd0}};

assign sigmoid_1_fu_158_p3 = ((or_ln469_fu_152_p2[0:0] == 1'b1) ? select_ln469_fu_144_p3 : add_ln468_2_fu_124_p2);

assign sigmoid_2_fu_334_p2 = ($signed(sext_ln468_1_fu_318_p1) + $signed(18'd2048));

assign sigmoid_3_fu_374_p3 = ((or_ln469_1_fu_368_p2[0:0] == 1'b1) ? select_ln469_1_fu_360_p3 : add_ln468_fu_340_p2);

assign sigmoid_4_fu_550_p2 = ($signed(sext_ln468_2_fu_534_p1) + $signed(18'd2048));

assign sigmoid_5_fu_590_p3 = ((or_ln469_2_fu_584_p2[0:0] == 1'b1) ? select_ln469_2_fu_576_p3 : add_ln468_5_fu_556_p2);

assign sigmoid_6_fu_766_p2 = ($signed(sext_ln468_3_fu_750_p1) + $signed(18'd2048));

assign sigmoid_7_fu_806_p3 = ((or_ln469_3_fu_800_p2[0:0] == 1'b1) ? select_ln469_3_fu_792_p3 : add_ln468_7_fu_772_p2);

assign sigmoid_8_fu_982_p2 = ($signed(sext_ln468_4_fu_966_p1) + $signed(18'd2048));

assign sigmoid_9_fu_1022_p3 = ((or_ln469_4_fu_1016_p2[0:0] == 1'b1) ? select_ln469_4_fu_1008_p3 : add_ln468_8_fu_988_p2);

assign sigmoid_fu_118_p2 = ($signed(sext_ln468_fu_102_p1) + $signed(18'd2048));

assign tmp_10_fu_442_p3 = sigmoid_3_fu_374_p3[32'd11];

assign tmp_11_fu_472_p3 = add_ln473_3_fu_466_p2[32'd7];

assign tmp_12_fu_480_p3 = add_ln473_2_fu_390_p2[32'd13];

assign tmp_13_fu_494_p3 = add_ln473_2_fu_390_p2[32'd13];

assign tmp_14_fu_568_p3 = sigmoid_4_fu_550_p2[32'd17];

assign tmp_16_fu_640_p3 = sigmoid_5_fu_590_p3[32'd3];

assign tmp_17_fu_658_p3 = sigmoid_5_fu_590_p3[32'd11];

assign tmp_18_fu_688_p3 = add_ln473_5_fu_682_p2[32'd7];

assign tmp_19_fu_696_p3 = add_ln473_4_fu_606_p2[32'd13];

assign tmp_20_fu_710_p3 = add_ln473_4_fu_606_p2[32'd13];

assign tmp_21_fu_784_p3 = sigmoid_6_fu_766_p2[32'd17];

assign tmp_23_fu_856_p3 = sigmoid_7_fu_806_p3[32'd3];

assign tmp_24_fu_874_p3 = sigmoid_7_fu_806_p3[32'd11];

assign tmp_25_fu_904_p3 = add_ln473_7_fu_898_p2[32'd7];

assign tmp_26_fu_912_p3 = add_ln473_6_fu_822_p2[32'd13];

assign tmp_27_fu_926_p3 = add_ln473_6_fu_822_p2[32'd13];

assign tmp_28_fu_1000_p3 = sigmoid_8_fu_982_p2[32'd17];

assign tmp_2_fu_208_p3 = sigmoid_1_fu_158_p3[32'd3];

assign tmp_30_fu_1072_p3 = sigmoid_9_fu_1022_p3[32'd3];

assign tmp_31_fu_1090_p3 = sigmoid_9_fu_1022_p3[32'd11];

assign tmp_32_fu_1120_p3 = add_ln473_9_fu_1114_p2[32'd7];

assign tmp_33_fu_1128_p3 = add_ln473_8_fu_1038_p2[32'd13];

assign tmp_34_fu_1142_p3 = add_ln473_8_fu_1038_p2[32'd13];

assign tmp_3_fu_226_p3 = sigmoid_1_fu_158_p3[32'd11];

assign tmp_4_fu_256_p3 = add_ln473_1_fu_250_p2[32'd7];

assign tmp_5_fu_264_p3 = add_ln473_fu_174_p2[32'd13];

assign tmp_6_fu_278_p3 = add_ln473_fu_174_p2[32'd13];

assign tmp_7_fu_352_p3 = sigmoid_2_fu_334_p2[32'd17];

assign tmp_9_fu_424_p3 = sigmoid_3_fu_374_p3[32'd3];

assign tmp_fu_136_p3 = sigmoid_fu_118_p2[32'd17];

assign trunc_ln468_1_fu_326_p3 = {{trunc_ln468_5_fu_322_p1}, {1'd0}};

assign trunc_ln468_2_fu_542_p3 = {{trunc_ln468_6_fu_538_p1}, {1'd0}};

assign trunc_ln468_3_fu_758_p3 = {{trunc_ln468_7_fu_754_p1}, {1'd0}};

assign trunc_ln468_4_fu_974_p3 = {{trunc_ln468_8_fu_970_p1}, {1'd0}};

assign trunc_ln468_5_fu_322_p1 = data_1_val[11:0];

assign trunc_ln468_6_fu_538_p1 = data_2_val[11:0];

assign trunc_ln468_7_fu_754_p1 = data_3_val[11:0];

assign trunc_ln468_8_fu_970_p1 = data_4_val[11:0];

assign trunc_ln468_fu_106_p1 = data_0_val[11:0];

assign trunc_ln473_10_fu_864_p1 = add_ln473_6_fu_822_p2[3:0];

assign trunc_ln473_11_fu_1052_p4 = {{sigmoid_9_fu_1022_p3[11:4]}};

assign trunc_ln473_12_fu_1068_p1 = xor_ln473_30_fu_1062_p2[0:0];

assign trunc_ln473_13_fu_1080_p1 = add_ln473_8_fu_1038_p2[3:0];

assign trunc_ln473_1_fu_216_p1 = add_ln473_fu_174_p2[3:0];

assign trunc_ln473_2_fu_420_p1 = xor_ln473_9_fu_414_p2[0:0];

assign trunc_ln473_3_fu_432_p1 = add_ln473_2_fu_390_p2[3:0];

assign trunc_ln473_4_fu_636_p1 = xor_ln473_16_fu_630_p2[0:0];

assign trunc_ln473_5_fu_648_p1 = add_ln473_4_fu_606_p2[3:0];

assign trunc_ln473_6_fu_188_p4 = {{sigmoid_1_fu_158_p3[11:4]}};

assign trunc_ln473_7_fu_836_p4 = {{sigmoid_7_fu_806_p3[11:4]}};

assign trunc_ln473_8_fu_852_p1 = xor_ln473_25_fu_846_p2[0:0];

assign trunc_ln473_9_fu_404_p4 = {{sigmoid_3_fu_374_p3[11:4]}};

assign trunc_ln473_fu_204_p1 = xor_ln473_fu_198_p2[0:0];

assign trunc_ln473_s_fu_620_p4 = {{sigmoid_5_fu_590_p3[11:4]}};

assign trunc_ln_fu_110_p3 = {{trunc_ln468_fu_106_p1}, {1'd0}};

assign xor_ln473_10_fu_1256_p2 = (or_ln473_31_fu_1252_p2 ^ 1'd1);

assign xor_ln473_11_fu_1262_p2 = (tmp_12_reg_1654 ^ or_ln473_17_reg_1660);

assign xor_ln473_12_fu_1349_p2 = (xor_ln473_20_fu_1340_p2 ^ 1'd1);

assign xor_ln473_13_fu_1360_p2 = (tmp_15_reg_1670 ^ 1'd1);

assign xor_ln473_14_fu_502_p2 = (tmp_13_fu_494_p3 ^ 1'd1);

assign xor_ln473_15_fu_1298_p2 = (or_ln473_18_fu_1293_p2 ^ 1'd1);

assign xor_ln473_16_fu_630_p2 = (trunc_ln473_s_fu_620_p4 ^ 8'd128);

assign xor_ln473_17_fu_1427_p2 = (xor_ln473_27_fu_1418_p2 ^ 1'd1);

assign xor_ln473_18_fu_1438_p2 = (tmp_22_reg_1708 ^ 1'd1);

assign xor_ln473_19_fu_1334_p2 = (or_ln473_32_fu_1330_p2 ^ 1'd1);

assign xor_ln473_1_fu_1178_p2 = (or_ln473_30_fu_1174_p2 ^ 1'd1);

assign xor_ln473_20_fu_1340_p2 = (tmp_19_reg_1692 ^ or_ln473_19_reg_1698);

assign xor_ln473_21_fu_718_p2 = (tmp_20_fu_710_p3 ^ 1'd1);

assign xor_ln473_22_fu_1505_p2 = (xor_ln473_32_fu_1496_p2 ^ 1'd1);

assign xor_ln473_23_fu_1516_p2 = (tmp_29_reg_1746 ^ 1'd1);

assign xor_ln473_24_fu_1376_p2 = (or_ln473_20_fu_1371_p2 ^ 1'd1);

assign xor_ln473_25_fu_846_p2 = (trunc_ln473_7_fu_836_p4 ^ 8'd128);

assign xor_ln473_26_fu_1412_p2 = (or_ln473_33_fu_1408_p2 ^ 1'd1);

assign xor_ln473_27_fu_1418_p2 = (tmp_26_reg_1730 ^ or_ln473_21_reg_1736);

assign xor_ln473_28_fu_934_p2 = (tmp_27_fu_926_p3 ^ 1'd1);

assign xor_ln473_29_fu_1454_p2 = (or_ln473_22_fu_1449_p2 ^ 1'd1);

assign xor_ln473_2_fu_1193_p2 = (xor_ln473_4_fu_1184_p2 ^ 1'd1);

assign xor_ln473_30_fu_1062_p2 = (trunc_ln473_11_fu_1052_p4 ^ 8'd128);

assign xor_ln473_31_fu_1490_p2 = (or_ln473_34_fu_1486_p2 ^ 1'd1);

assign xor_ln473_32_fu_1496_p2 = (tmp_33_reg_1768 ^ or_ln473_23_reg_1774);

assign xor_ln473_33_fu_1150_p2 = (tmp_34_fu_1142_p3 ^ 1'd1);

assign xor_ln473_34_fu_1532_p2 = (or_ln473_24_fu_1527_p2 ^ 1'd1);

assign xor_ln473_3_fu_1204_p2 = (tmp_1_reg_1594 ^ 1'd1);

assign xor_ln473_4_fu_1184_p2 = (tmp_5_reg_1616 ^ or_ln473_15_reg_1622);

assign xor_ln473_5_fu_286_p2 = (tmp_6_fu_278_p3 ^ 1'd1);

assign xor_ln473_6_fu_1220_p2 = (or_ln473_16_fu_1215_p2 ^ 1'd1);

assign xor_ln473_7_fu_1271_p2 = (xor_ln473_11_fu_1262_p2 ^ 1'd1);

assign xor_ln473_8_fu_1282_p2 = (tmp_8_reg_1632 ^ 1'd1);

assign xor_ln473_9_fu_414_p2 = (trunc_ln473_9_fu_404_p4 ^ 8'd128);

assign xor_ln473_fu_198_p2 = (trunc_ln473_6_fu_188_p4 ^ 8'd128);

assign zext_ln473_1_fu_462_p1 = and_ln473_6_fu_456_p2;

assign zext_ln473_2_fu_678_p1 = and_ln473_12_fu_672_p2;

assign zext_ln473_3_fu_894_p1 = and_ln473_18_fu_888_p2;

assign zext_ln473_4_fu_1110_p1 = and_ln473_24_fu_1104_p2;

assign zext_ln473_fu_246_p1 = and_ln473_fu_240_p2;

endmodule //ParamEst_NN_hard_tanh_ap_fixed_ap_fixed_8_1_4_0_0_PARAMEST_NN_hard_tanh_config14_s
