// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config15_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [23:0] y_fu_342_p3;
wire   [23:0] add_ln54_fu_350_p2;
wire   [23:0] y_107_fu_366_p3;
wire   [23:0] add_ln54_87_fu_374_p2;
wire   [22:0] y_81_fu_390_p3;
wire  signed [23:0] sext_ln54_19_fu_398_p1;
wire   [23:0] add_ln54_88_fu_402_p2;
wire   [14:0] trunc_ln54_93_fu_418_p4;
wire   [23:0] y_82_fu_432_p3;
wire   [23:0] add_ln54_89_fu_440_p2;
wire   [23:0] y_83_fu_456_p3;
wire   [23:0] add_ln54_90_fu_464_p2;
wire   [23:0] y_84_fu_480_p3;
wire   [23:0] add_ln54_91_fu_488_p2;
wire   [23:0] y_85_fu_504_p3;
wire   [23:0] add_ln54_92_fu_512_p2;
wire   [23:0] y_86_fu_528_p3;
wire   [23:0] add_ln54_93_fu_536_p2;
wire   [23:0] y_87_fu_552_p3;
wire   [23:0] add_ln54_94_fu_560_p2;
wire   [23:0] y_88_fu_576_p3;
wire   [23:0] add_ln54_95_fu_584_p2;
wire   [14:0] trunc_ln54_101_fu_600_p4;
wire   [23:0] y_89_fu_614_p3;
wire   [23:0] add_ln54_96_fu_622_p2;
wire   [23:0] y_90_fu_638_p3;
wire   [23:0] add_ln54_97_fu_646_p2;
wire   [22:0] y_91_fu_662_p3;
wire  signed [23:0] sext_ln54_20_fu_670_p1;
wire   [23:0] add_ln54_98_fu_674_p2;
wire   [23:0] y_92_fu_690_p3;
wire   [23:0] add_ln54_99_fu_698_p2;
wire   [23:0] y_93_fu_714_p3;
wire   [23:0] add_ln54_100_fu_722_p2;
wire   [23:0] y_94_fu_738_p3;
wire   [23:0] add_ln54_101_fu_746_p2;
wire   [23:0] y_95_fu_762_p3;
wire   [23:0] add_ln54_102_fu_770_p2;
wire   [23:0] y_96_fu_786_p3;
wire   [23:0] add_ln54_103_fu_794_p2;
wire   [23:0] y_97_fu_810_p3;
wire   [23:0] add_ln54_104_fu_818_p2;
wire   [23:0] y_98_fu_834_p3;
wire   [23:0] add_ln54_105_fu_842_p2;
wire   [23:0] y_99_fu_858_p3;
wire   [23:0] add_ln54_106_fu_866_p2;
wire   [23:0] y_100_fu_882_p3;
wire   [23:0] add_ln54_107_fu_890_p2;
wire   [14:0] trunc_ln54_114_fu_906_p4;
wire   [23:0] y_101_fu_920_p3;
wire   [23:0] add_ln54_108_fu_928_p2;
wire   [23:0] y_102_fu_944_p3;
wire   [23:0] add_ln54_109_fu_952_p2;
wire   [23:0] y_103_fu_968_p3;
wire   [23:0] add_ln54_110_fu_976_p2;
wire   [23:0] y_104_fu_992_p3;
wire   [23:0] add_ln54_111_fu_1000_p2;
wire   [23:0] y_105_fu_1016_p3;
wire   [23:0] add_ln54_112_fu_1024_p2;
wire  signed [15:0] sext_ln54_fu_428_p1;
wire  signed [15:0] sext_ln54_10_fu_610_p1;
wire  signed [15:0] sext_ln54_11_fu_916_p1;

assign add_ln54_100_fu_722_p2 = (y_93_fu_714_p3 + 24'd1024);

assign add_ln54_101_fu_746_p2 = (y_94_fu_738_p3 + 24'd5632);

assign add_ln54_102_fu_770_p2 = (y_95_fu_762_p3 + 24'd9216);

assign add_ln54_103_fu_794_p2 = (y_96_fu_786_p3 + 24'd1536);

assign add_ln54_104_fu_818_p2 = (y_97_fu_810_p3 + 24'd7424);

assign add_ln54_105_fu_842_p2 = (y_98_fu_834_p3 + 24'd4864);

assign add_ln54_106_fu_866_p2 = ($signed(y_99_fu_858_p3) + $signed(24'd16764672));

assign add_ln54_107_fu_890_p2 = (y_100_fu_882_p3 + 24'd14080);

assign add_ln54_108_fu_928_p2 = (y_101_fu_920_p3 + 24'd7936);

assign add_ln54_109_fu_952_p2 = ($signed(y_102_fu_944_p3) + $signed(24'd16774656));

assign add_ln54_110_fu_976_p2 = (y_103_fu_968_p3 + 24'd13568);

assign add_ln54_111_fu_1000_p2 = (y_104_fu_992_p3 + 24'd18432);

assign add_ln54_112_fu_1024_p2 = ($signed(y_105_fu_1016_p3) + $signed(24'd16772864));

assign add_ln54_87_fu_374_p2 = (y_107_fu_366_p3 + 24'd13568);

assign add_ln54_88_fu_402_p2 = ($signed(sext_ln54_19_fu_398_p1) + $signed(24'd16774144));

assign add_ln54_89_fu_440_p2 = (y_82_fu_432_p3 + 24'd4096);

assign add_ln54_90_fu_464_p2 = (y_83_fu_456_p3 + 24'd16384);

assign add_ln54_91_fu_488_p2 = (y_84_fu_480_p3 + 24'd19968);

assign add_ln54_92_fu_512_p2 = (y_85_fu_504_p3 + 24'd4096);

assign add_ln54_93_fu_536_p2 = (y_86_fu_528_p3 + 24'd4352);

assign add_ln54_94_fu_560_p2 = (y_87_fu_552_p3 + 24'd8448);

assign add_ln54_95_fu_584_p2 = (y_88_fu_576_p3 + 24'd1792);

assign add_ln54_96_fu_622_p2 = ($signed(y_89_fu_614_p3) + $signed(24'd16774400));

assign add_ln54_97_fu_646_p2 = (y_90_fu_638_p3 + 24'd4608);

assign add_ln54_98_fu_674_p2 = ($signed(sext_ln54_20_fu_670_p1) + $signed(24'd9496));

assign add_ln54_99_fu_698_p2 = ($signed(y_92_fu_690_p3) + $signed(24'd16768000));

assign add_ln54_fu_350_p2 = ($signed(y_fu_342_p3) + $signed(24'd16765696));

assign ap_ready = 1'b1;

assign sext_ln54_10_fu_610_p1 = $signed(trunc_ln54_101_fu_600_p4);

assign sext_ln54_11_fu_916_p1 = $signed(trunc_ln54_114_fu_906_p4);

assign sext_ln54_19_fu_398_p1 = $signed(y_81_fu_390_p3);

assign sext_ln54_20_fu_670_p1 = $signed(y_91_fu_662_p3);

assign sext_ln54_fu_428_p1 = $signed(trunc_ln54_93_fu_418_p4);

assign trunc_ln54_101_fu_600_p4 = {{data_13_val[15:1]}};

assign trunc_ln54_114_fu_906_p4 = {{data_26_val[15:1]}};

assign trunc_ln54_93_fu_418_p4 = {{data_4_val[15:1]}};

assign y_100_fu_882_p3 = {{data_25_val}, {8'd0}};

assign y_101_fu_920_p3 = {{data_27_val}, {8'd0}};

assign y_102_fu_944_p3 = {{data_28_val}, {8'd0}};

assign y_103_fu_968_p3 = {{data_29_val}, {8'd0}};

assign y_104_fu_992_p3 = {{data_30_val}, {8'd0}};

assign y_105_fu_1016_p3 = {{data_31_val}, {8'd0}};

assign y_107_fu_366_p3 = {{data_1_val}, {8'd0}};

assign y_81_fu_390_p3 = {{data_2_val}, {7'd0}};

assign y_82_fu_432_p3 = {{data_5_val}, {8'd0}};

assign y_83_fu_456_p3 = {{data_6_val}, {8'd0}};

assign y_84_fu_480_p3 = {{data_7_val}, {8'd0}};

assign y_85_fu_504_p3 = {{data_8_val}, {8'd0}};

assign y_86_fu_528_p3 = {{data_9_val}, {8'd0}};

assign y_87_fu_552_p3 = {{data_10_val}, {8'd0}};

assign y_88_fu_576_p3 = {{data_12_val}, {8'd0}};

assign y_89_fu_614_p3 = {{data_14_val}, {8'd0}};

assign y_90_fu_638_p3 = {{data_15_val}, {8'd0}};

assign y_91_fu_662_p3 = {{data_16_val}, {7'd0}};

assign y_92_fu_690_p3 = {{data_17_val}, {8'd0}};

assign y_93_fu_714_p3 = {{data_18_val}, {8'd0}};

assign y_94_fu_738_p3 = {{data_19_val}, {8'd0}};

assign y_95_fu_762_p3 = {{data_20_val}, {8'd0}};

assign y_96_fu_786_p3 = {{data_21_val}, {8'd0}};

assign y_97_fu_810_p3 = {{data_22_val}, {8'd0}};

assign y_98_fu_834_p3 = {{data_23_val}, {8'd0}};

assign y_99_fu_858_p3 = {{data_24_val}, {8'd0}};

assign y_fu_342_p3 = {{data_0_val}, {8'd0}};

assign ap_return_0 = {{add_ln54_fu_350_p2[23:8]}};

assign ap_return_1 = {{add_ln54_87_fu_374_p2[23:8]}};

assign ap_return_10 = {{add_ln54_94_fu_560_p2[23:8]}};

assign ap_return_11 = data_11_val;

assign ap_return_12 = {{add_ln54_95_fu_584_p2[23:8]}};

assign ap_return_13 = sext_ln54_10_fu_610_p1;

assign ap_return_14 = {{add_ln54_96_fu_622_p2[23:8]}};

assign ap_return_15 = {{add_ln54_97_fu_646_p2[23:8]}};

assign ap_return_16 = {{add_ln54_98_fu_674_p2[23:8]}};

assign ap_return_17 = {{add_ln54_99_fu_698_p2[23:8]}};

assign ap_return_18 = {{add_ln54_100_fu_722_p2[23:8]}};

assign ap_return_19 = {{add_ln54_101_fu_746_p2[23:8]}};

assign ap_return_2 = {{add_ln54_88_fu_402_p2[23:8]}};

assign ap_return_20 = {{add_ln54_102_fu_770_p2[23:8]}};

assign ap_return_21 = {{add_ln54_103_fu_794_p2[23:8]}};

assign ap_return_22 = {{add_ln54_104_fu_818_p2[23:8]}};

assign ap_return_23 = {{add_ln54_105_fu_842_p2[23:8]}};

assign ap_return_24 = {{add_ln54_106_fu_866_p2[23:8]}};

assign ap_return_25 = {{add_ln54_107_fu_890_p2[23:8]}};

assign ap_return_26 = sext_ln54_11_fu_916_p1;

assign ap_return_27 = {{add_ln54_108_fu_928_p2[23:8]}};

assign ap_return_28 = {{add_ln54_109_fu_952_p2[23:8]}};

assign ap_return_29 = {{add_ln54_110_fu_976_p2[23:8]}};

assign ap_return_3 = data_3_val;

assign ap_return_30 = {{add_ln54_111_fu_1000_p2[23:8]}};

assign ap_return_31 = {{add_ln54_112_fu_1024_p2[23:8]}};

assign ap_return_4 = sext_ln54_fu_428_p1;

assign ap_return_5 = {{add_ln54_89_fu_440_p2[23:8]}};

assign ap_return_6 = {{add_ln54_90_fu_464_p2[23:8]}};

assign ap_return_7 = {{add_ln54_91_fu_488_p2[23:8]}};

assign ap_return_8 = {{add_ln54_92_fu_512_p2[23:8]}};

assign ap_return_9 = {{add_ln54_93_fu_536_p2[23:8]}};

endmodule //ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config15_s
