// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_relu_ap_fixed_ap_ufixed_16_0_4_0_0_PARAMEST_NN_relu_config5_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;

wire   [5:0] tmp_fu_294_p4;
wire   [0:0] icmp_ln46_fu_304_p2;
wire   [15:0] shl_ln46_fu_288_p2;
wire   [0:0] icmp_ln45_fu_282_p2;
wire   [15:0] select_ln46_fu_310_p3;
wire   [5:0] tmp_34_fu_338_p4;
wire   [0:0] icmp_ln46_64_fu_348_p2;
wire   [15:0] shl_ln46_64_fu_332_p2;
wire   [0:0] icmp_ln45_64_fu_326_p2;
wire   [15:0] select_ln46_64_fu_354_p3;
wire   [5:0] tmp_s_fu_382_p4;
wire   [0:0] icmp_ln46_65_fu_392_p2;
wire   [15:0] shl_ln46_65_fu_376_p2;
wire   [0:0] icmp_ln45_65_fu_370_p2;
wire   [15:0] select_ln46_65_fu_398_p3;
wire   [5:0] tmp_63_fu_426_p4;
wire   [0:0] icmp_ln46_66_fu_436_p2;
wire   [15:0] shl_ln46_66_fu_420_p2;
wire   [0:0] icmp_ln45_66_fu_414_p2;
wire   [15:0] select_ln46_66_fu_442_p3;
wire   [5:0] tmp_64_fu_470_p4;
wire   [0:0] icmp_ln46_67_fu_480_p2;
wire   [15:0] shl_ln46_67_fu_464_p2;
wire   [0:0] icmp_ln45_67_fu_458_p2;
wire   [15:0] select_ln46_67_fu_486_p3;
wire   [5:0] tmp_65_fu_514_p4;
wire   [0:0] icmp_ln46_68_fu_524_p2;
wire   [15:0] shl_ln46_68_fu_508_p2;
wire   [0:0] icmp_ln45_68_fu_502_p2;
wire   [15:0] select_ln46_68_fu_530_p3;
wire   [5:0] tmp_66_fu_558_p4;
wire   [0:0] icmp_ln46_69_fu_568_p2;
wire   [15:0] shl_ln46_69_fu_552_p2;
wire   [0:0] icmp_ln45_69_fu_546_p2;
wire   [15:0] select_ln46_69_fu_574_p3;
wire   [5:0] tmp_67_fu_602_p4;
wire   [0:0] icmp_ln46_70_fu_612_p2;
wire   [15:0] shl_ln46_70_fu_596_p2;
wire   [0:0] icmp_ln45_70_fu_590_p2;
wire   [15:0] select_ln46_70_fu_618_p3;
wire   [5:0] tmp_68_fu_646_p4;
wire   [0:0] icmp_ln46_71_fu_656_p2;
wire   [15:0] shl_ln46_71_fu_640_p2;
wire   [0:0] icmp_ln45_71_fu_634_p2;
wire   [15:0] select_ln46_71_fu_662_p3;
wire   [5:0] tmp_69_fu_690_p4;
wire   [0:0] icmp_ln46_72_fu_700_p2;
wire   [15:0] shl_ln46_72_fu_684_p2;
wire   [0:0] icmp_ln45_72_fu_678_p2;
wire   [15:0] select_ln46_72_fu_706_p3;
wire   [5:0] tmp_70_fu_734_p4;
wire   [0:0] icmp_ln46_73_fu_744_p2;
wire   [15:0] shl_ln46_73_fu_728_p2;
wire   [0:0] icmp_ln45_73_fu_722_p2;
wire   [15:0] select_ln46_73_fu_750_p3;
wire   [5:0] tmp_71_fu_778_p4;
wire   [0:0] icmp_ln46_74_fu_788_p2;
wire   [15:0] shl_ln46_74_fu_772_p2;
wire   [0:0] icmp_ln45_74_fu_766_p2;
wire   [15:0] select_ln46_74_fu_794_p3;
wire   [5:0] tmp_72_fu_822_p4;
wire   [0:0] icmp_ln46_75_fu_832_p2;
wire   [15:0] shl_ln46_75_fu_816_p2;
wire   [0:0] icmp_ln45_75_fu_810_p2;
wire   [15:0] select_ln46_75_fu_838_p3;
wire   [5:0] tmp_73_fu_866_p4;
wire   [0:0] icmp_ln46_76_fu_876_p2;
wire   [15:0] shl_ln46_76_fu_860_p2;
wire   [0:0] icmp_ln45_76_fu_854_p2;
wire   [15:0] select_ln46_76_fu_882_p3;
wire   [5:0] tmp_74_fu_910_p4;
wire   [0:0] icmp_ln46_77_fu_920_p2;
wire   [15:0] shl_ln46_77_fu_904_p2;
wire   [0:0] icmp_ln45_77_fu_898_p2;
wire   [15:0] select_ln46_77_fu_926_p3;
wire   [5:0] tmp_75_fu_954_p4;
wire   [0:0] icmp_ln46_78_fu_964_p2;
wire   [15:0] shl_ln46_78_fu_948_p2;
wire   [0:0] icmp_ln45_78_fu_942_p2;
wire   [15:0] select_ln46_78_fu_970_p3;
wire   [5:0] tmp_76_fu_998_p4;
wire   [0:0] icmp_ln46_79_fu_1008_p2;
wire   [15:0] shl_ln46_79_fu_992_p2;
wire   [0:0] icmp_ln45_79_fu_986_p2;
wire   [15:0] select_ln46_79_fu_1014_p3;
wire   [5:0] tmp_77_fu_1042_p4;
wire   [0:0] icmp_ln46_80_fu_1052_p2;
wire   [15:0] shl_ln46_80_fu_1036_p2;
wire   [0:0] icmp_ln45_80_fu_1030_p2;
wire   [15:0] select_ln46_80_fu_1058_p3;
wire   [5:0] tmp_78_fu_1086_p4;
wire   [0:0] icmp_ln46_81_fu_1096_p2;
wire   [15:0] shl_ln46_81_fu_1080_p2;
wire   [0:0] icmp_ln45_81_fu_1074_p2;
wire   [15:0] select_ln46_81_fu_1102_p3;
wire   [5:0] tmp_79_fu_1130_p4;
wire   [0:0] icmp_ln46_82_fu_1140_p2;
wire   [15:0] shl_ln46_82_fu_1124_p2;
wire   [0:0] icmp_ln45_82_fu_1118_p2;
wire   [15:0] select_ln46_82_fu_1146_p3;
wire   [5:0] tmp_80_fu_1174_p4;
wire   [0:0] icmp_ln46_83_fu_1184_p2;
wire   [15:0] shl_ln46_83_fu_1168_p2;
wire   [0:0] icmp_ln45_83_fu_1162_p2;
wire   [15:0] select_ln46_83_fu_1190_p3;
wire   [5:0] tmp_81_fu_1218_p4;
wire   [0:0] icmp_ln46_84_fu_1228_p2;
wire   [15:0] shl_ln46_84_fu_1212_p2;
wire   [0:0] icmp_ln45_84_fu_1206_p2;
wire   [15:0] select_ln46_84_fu_1234_p3;
wire   [5:0] tmp_82_fu_1262_p4;
wire   [0:0] icmp_ln46_85_fu_1272_p2;
wire   [15:0] shl_ln46_85_fu_1256_p2;
wire   [0:0] icmp_ln45_85_fu_1250_p2;
wire   [15:0] select_ln46_85_fu_1278_p3;
wire   [5:0] tmp_83_fu_1306_p4;
wire   [0:0] icmp_ln46_86_fu_1316_p2;
wire   [15:0] shl_ln46_86_fu_1300_p2;
wire   [0:0] icmp_ln45_86_fu_1294_p2;
wire   [15:0] select_ln46_86_fu_1322_p3;
wire   [5:0] tmp_84_fu_1350_p4;
wire   [0:0] icmp_ln46_87_fu_1360_p2;
wire   [15:0] shl_ln46_87_fu_1344_p2;
wire   [0:0] icmp_ln45_87_fu_1338_p2;
wire   [15:0] select_ln46_87_fu_1366_p3;
wire   [5:0] tmp_85_fu_1394_p4;
wire   [0:0] icmp_ln46_88_fu_1404_p2;
wire   [15:0] shl_ln46_88_fu_1388_p2;
wire   [0:0] icmp_ln45_88_fu_1382_p2;
wire   [15:0] select_ln46_88_fu_1410_p3;
wire   [5:0] tmp_86_fu_1438_p4;
wire   [0:0] icmp_ln46_89_fu_1448_p2;
wire   [15:0] shl_ln46_89_fu_1432_p2;
wire   [0:0] icmp_ln45_89_fu_1426_p2;
wire   [15:0] select_ln46_89_fu_1454_p3;
wire   [5:0] tmp_87_fu_1482_p4;
wire   [0:0] icmp_ln46_90_fu_1492_p2;
wire   [15:0] shl_ln46_90_fu_1476_p2;
wire   [0:0] icmp_ln45_90_fu_1470_p2;
wire   [15:0] select_ln46_90_fu_1498_p3;
wire   [5:0] tmp_88_fu_1526_p4;
wire   [0:0] icmp_ln46_91_fu_1536_p2;
wire   [15:0] shl_ln46_91_fu_1520_p2;
wire   [0:0] icmp_ln45_91_fu_1514_p2;
wire   [15:0] select_ln46_91_fu_1542_p3;
wire   [5:0] tmp_89_fu_1570_p4;
wire   [0:0] icmp_ln46_92_fu_1580_p2;
wire   [15:0] shl_ln46_92_fu_1564_p2;
wire   [0:0] icmp_ln45_92_fu_1558_p2;
wire   [15:0] select_ln46_92_fu_1586_p3;
wire   [5:0] tmp_90_fu_1614_p4;
wire   [0:0] icmp_ln46_93_fu_1624_p2;
wire   [15:0] shl_ln46_93_fu_1608_p2;
wire   [0:0] icmp_ln45_93_fu_1602_p2;
wire   [15:0] select_ln46_93_fu_1630_p3;
wire   [5:0] tmp_91_fu_1658_p4;
wire   [0:0] icmp_ln46_94_fu_1668_p2;
wire   [15:0] shl_ln46_94_fu_1652_p2;
wire   [0:0] icmp_ln45_94_fu_1646_p2;
wire   [15:0] select_ln46_94_fu_1674_p3;
wire   [15:0] select_ln45_fu_318_p3;
wire   [15:0] select_ln45_64_fu_362_p3;
wire   [15:0] select_ln45_65_fu_406_p3;
wire   [15:0] select_ln45_66_fu_450_p3;
wire   [15:0] select_ln45_67_fu_494_p3;
wire   [15:0] select_ln45_68_fu_538_p3;
wire   [15:0] select_ln45_69_fu_582_p3;
wire   [15:0] select_ln45_70_fu_626_p3;
wire   [15:0] select_ln45_71_fu_670_p3;
wire   [15:0] select_ln45_72_fu_714_p3;
wire   [15:0] select_ln45_73_fu_758_p3;
wire   [15:0] select_ln45_74_fu_802_p3;
wire   [15:0] select_ln45_75_fu_846_p3;
wire   [15:0] select_ln45_76_fu_890_p3;
wire   [15:0] select_ln45_77_fu_934_p3;
wire   [15:0] select_ln45_78_fu_978_p3;
wire   [15:0] select_ln45_79_fu_1022_p3;
wire   [15:0] select_ln45_80_fu_1066_p3;
wire   [15:0] select_ln45_81_fu_1110_p3;
wire   [15:0] select_ln45_82_fu_1154_p3;
wire   [15:0] select_ln45_83_fu_1198_p3;
wire   [15:0] select_ln45_84_fu_1242_p3;
wire   [15:0] select_ln45_85_fu_1286_p3;
wire   [15:0] select_ln45_86_fu_1330_p3;
wire   [15:0] select_ln45_87_fu_1374_p3;
wire   [15:0] select_ln45_88_fu_1418_p3;
wire   [15:0] select_ln45_89_fu_1462_p3;
wire   [15:0] select_ln45_90_fu_1506_p3;
wire   [15:0] select_ln45_91_fu_1550_p3;
wire   [15:0] select_ln45_92_fu_1594_p3;
wire   [15:0] select_ln45_93_fu_1638_p3;
wire   [15:0] select_ln45_94_fu_1682_p3;
wire    ap_ce_reg;

assign ap_ready = 1'b1;

assign icmp_ln46_64_fu_348_p2 = ((tmp_34_fu_338_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_65_fu_392_p2 = ((tmp_s_fu_382_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_66_fu_436_p2 = ((tmp_63_fu_426_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_67_fu_480_p2 = ((tmp_64_fu_470_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_68_fu_524_p2 = ((tmp_65_fu_514_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_69_fu_568_p2 = ((tmp_66_fu_558_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_70_fu_612_p2 = ((tmp_67_fu_602_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_71_fu_656_p2 = ((tmp_68_fu_646_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_72_fu_700_p2 = ((tmp_69_fu_690_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_73_fu_744_p2 = ((tmp_70_fu_734_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_74_fu_788_p2 = ((tmp_71_fu_778_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_75_fu_832_p2 = ((tmp_72_fu_822_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_76_fu_876_p2 = ((tmp_73_fu_866_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_77_fu_920_p2 = ((tmp_74_fu_910_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_78_fu_964_p2 = ((tmp_75_fu_954_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_79_fu_1008_p2 = ((tmp_76_fu_998_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_80_fu_1052_p2 = ((tmp_77_fu_1042_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_81_fu_1096_p2 = ((tmp_78_fu_1086_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_82_fu_1140_p2 = ((tmp_79_fu_1130_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_83_fu_1184_p2 = ((tmp_80_fu_1174_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_84_fu_1228_p2 = ((tmp_81_fu_1218_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_85_fu_1272_p2 = ((tmp_82_fu_1262_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_86_fu_1316_p2 = ((tmp_83_fu_1306_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_87_fu_1360_p2 = ((tmp_84_fu_1350_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_88_fu_1404_p2 = ((tmp_85_fu_1394_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_89_fu_1448_p2 = ((tmp_86_fu_1438_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_90_fu_1492_p2 = ((tmp_87_fu_1482_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_91_fu_1536_p2 = ((tmp_88_fu_1526_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_92_fu_1580_p2 = ((tmp_89_fu_1570_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_93_fu_1624_p2 = ((tmp_90_fu_1614_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_94_fu_1668_p2 = ((tmp_91_fu_1658_p4 != 6'd0) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_304_p2 = ((tmp_fu_294_p4 != 6'd0) ? 1'b1 : 1'b0);

assign select_ln45_64_fu_362_p3 = ((icmp_ln45_64_fu_326_p2[0:0] == 1'b1) ? select_ln46_64_fu_354_p3 : 16'd0);

assign select_ln45_65_fu_406_p3 = ((icmp_ln45_65_fu_370_p2[0:0] == 1'b1) ? select_ln46_65_fu_398_p3 : 16'd0);

assign select_ln45_66_fu_450_p3 = ((icmp_ln45_66_fu_414_p2[0:0] == 1'b1) ? select_ln46_66_fu_442_p3 : 16'd0);

assign select_ln45_67_fu_494_p3 = ((icmp_ln45_67_fu_458_p2[0:0] == 1'b1) ? select_ln46_67_fu_486_p3 : 16'd0);

assign select_ln45_68_fu_538_p3 = ((icmp_ln45_68_fu_502_p2[0:0] == 1'b1) ? select_ln46_68_fu_530_p3 : 16'd0);

assign select_ln45_69_fu_582_p3 = ((icmp_ln45_69_fu_546_p2[0:0] == 1'b1) ? select_ln46_69_fu_574_p3 : 16'd0);

assign select_ln45_70_fu_626_p3 = ((icmp_ln45_70_fu_590_p2[0:0] == 1'b1) ? select_ln46_70_fu_618_p3 : 16'd0);

assign select_ln45_71_fu_670_p3 = ((icmp_ln45_71_fu_634_p2[0:0] == 1'b1) ? select_ln46_71_fu_662_p3 : 16'd0);

assign select_ln45_72_fu_714_p3 = ((icmp_ln45_72_fu_678_p2[0:0] == 1'b1) ? select_ln46_72_fu_706_p3 : 16'd0);

assign select_ln45_73_fu_758_p3 = ((icmp_ln45_73_fu_722_p2[0:0] == 1'b1) ? select_ln46_73_fu_750_p3 : 16'd0);

assign select_ln45_74_fu_802_p3 = ((icmp_ln45_74_fu_766_p2[0:0] == 1'b1) ? select_ln46_74_fu_794_p3 : 16'd0);

assign select_ln45_75_fu_846_p3 = ((icmp_ln45_75_fu_810_p2[0:0] == 1'b1) ? select_ln46_75_fu_838_p3 : 16'd0);

assign select_ln45_76_fu_890_p3 = ((icmp_ln45_76_fu_854_p2[0:0] == 1'b1) ? select_ln46_76_fu_882_p3 : 16'd0);

assign select_ln45_77_fu_934_p3 = ((icmp_ln45_77_fu_898_p2[0:0] == 1'b1) ? select_ln46_77_fu_926_p3 : 16'd0);

assign select_ln45_78_fu_978_p3 = ((icmp_ln45_78_fu_942_p2[0:0] == 1'b1) ? select_ln46_78_fu_970_p3 : 16'd0);

assign select_ln45_79_fu_1022_p3 = ((icmp_ln45_79_fu_986_p2[0:0] == 1'b1) ? select_ln46_79_fu_1014_p3 : 16'd0);

assign select_ln45_80_fu_1066_p3 = ((icmp_ln45_80_fu_1030_p2[0:0] == 1'b1) ? select_ln46_80_fu_1058_p3 : 16'd0);

assign select_ln45_81_fu_1110_p3 = ((icmp_ln45_81_fu_1074_p2[0:0] == 1'b1) ? select_ln46_81_fu_1102_p3 : 16'd0);

assign select_ln45_82_fu_1154_p3 = ((icmp_ln45_82_fu_1118_p2[0:0] == 1'b1) ? select_ln46_82_fu_1146_p3 : 16'd0);

assign select_ln45_83_fu_1198_p3 = ((icmp_ln45_83_fu_1162_p2[0:0] == 1'b1) ? select_ln46_83_fu_1190_p3 : 16'd0);

assign select_ln45_84_fu_1242_p3 = ((icmp_ln45_84_fu_1206_p2[0:0] == 1'b1) ? select_ln46_84_fu_1234_p3 : 16'd0);

assign select_ln45_85_fu_1286_p3 = ((icmp_ln45_85_fu_1250_p2[0:0] == 1'b1) ? select_ln46_85_fu_1278_p3 : 16'd0);

assign select_ln45_86_fu_1330_p3 = ((icmp_ln45_86_fu_1294_p2[0:0] == 1'b1) ? select_ln46_86_fu_1322_p3 : 16'd0);

assign select_ln45_87_fu_1374_p3 = ((icmp_ln45_87_fu_1338_p2[0:0] == 1'b1) ? select_ln46_87_fu_1366_p3 : 16'd0);

assign select_ln45_88_fu_1418_p3 = ((icmp_ln45_88_fu_1382_p2[0:0] == 1'b1) ? select_ln46_88_fu_1410_p3 : 16'd0);

assign select_ln45_89_fu_1462_p3 = ((icmp_ln45_89_fu_1426_p2[0:0] == 1'b1) ? select_ln46_89_fu_1454_p3 : 16'd0);

assign select_ln45_90_fu_1506_p3 = ((icmp_ln45_90_fu_1470_p2[0:0] == 1'b1) ? select_ln46_90_fu_1498_p3 : 16'd0);

assign select_ln45_91_fu_1550_p3 = ((icmp_ln45_91_fu_1514_p2[0:0] == 1'b1) ? select_ln46_91_fu_1542_p3 : 16'd0);

assign select_ln45_92_fu_1594_p3 = ((icmp_ln45_92_fu_1558_p2[0:0] == 1'b1) ? select_ln46_92_fu_1586_p3 : 16'd0);

assign select_ln45_93_fu_1638_p3 = ((icmp_ln45_93_fu_1602_p2[0:0] == 1'b1) ? select_ln46_93_fu_1630_p3 : 16'd0);

assign select_ln45_94_fu_1682_p3 = ((icmp_ln45_94_fu_1646_p2[0:0] == 1'b1) ? select_ln46_94_fu_1674_p3 : 16'd0);

assign select_ln45_fu_318_p3 = ((icmp_ln45_fu_282_p2[0:0] == 1'b1) ? select_ln46_fu_310_p3 : 16'd0);

assign select_ln46_64_fu_354_p3 = ((icmp_ln46_64_fu_348_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_64_fu_332_p2);

assign select_ln46_65_fu_398_p3 = ((icmp_ln46_65_fu_392_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_65_fu_376_p2);

assign select_ln46_66_fu_442_p3 = ((icmp_ln46_66_fu_436_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_66_fu_420_p2);

assign select_ln46_67_fu_486_p3 = ((icmp_ln46_67_fu_480_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_67_fu_464_p2);

assign select_ln46_68_fu_530_p3 = ((icmp_ln46_68_fu_524_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_68_fu_508_p2);

assign select_ln46_69_fu_574_p3 = ((icmp_ln46_69_fu_568_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_69_fu_552_p2);

assign select_ln46_70_fu_618_p3 = ((icmp_ln46_70_fu_612_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_70_fu_596_p2);

assign select_ln46_71_fu_662_p3 = ((icmp_ln46_71_fu_656_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_71_fu_640_p2);

assign select_ln46_72_fu_706_p3 = ((icmp_ln46_72_fu_700_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_72_fu_684_p2);

assign select_ln46_73_fu_750_p3 = ((icmp_ln46_73_fu_744_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_73_fu_728_p2);

assign select_ln46_74_fu_794_p3 = ((icmp_ln46_74_fu_788_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_74_fu_772_p2);

assign select_ln46_75_fu_838_p3 = ((icmp_ln46_75_fu_832_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_75_fu_816_p2);

assign select_ln46_76_fu_882_p3 = ((icmp_ln46_76_fu_876_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_76_fu_860_p2);

assign select_ln46_77_fu_926_p3 = ((icmp_ln46_77_fu_920_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_77_fu_904_p2);

assign select_ln46_78_fu_970_p3 = ((icmp_ln46_78_fu_964_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_78_fu_948_p2);

assign select_ln46_79_fu_1014_p3 = ((icmp_ln46_79_fu_1008_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_79_fu_992_p2);

assign select_ln46_80_fu_1058_p3 = ((icmp_ln46_80_fu_1052_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_80_fu_1036_p2);

assign select_ln46_81_fu_1102_p3 = ((icmp_ln46_81_fu_1096_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_81_fu_1080_p2);

assign select_ln46_82_fu_1146_p3 = ((icmp_ln46_82_fu_1140_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_82_fu_1124_p2);

assign select_ln46_83_fu_1190_p3 = ((icmp_ln46_83_fu_1184_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_83_fu_1168_p2);

assign select_ln46_84_fu_1234_p3 = ((icmp_ln46_84_fu_1228_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_84_fu_1212_p2);

assign select_ln46_85_fu_1278_p3 = ((icmp_ln46_85_fu_1272_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_85_fu_1256_p2);

assign select_ln46_86_fu_1322_p3 = ((icmp_ln46_86_fu_1316_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_86_fu_1300_p2);

assign select_ln46_87_fu_1366_p3 = ((icmp_ln46_87_fu_1360_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_87_fu_1344_p2);

assign select_ln46_88_fu_1410_p3 = ((icmp_ln46_88_fu_1404_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_88_fu_1388_p2);

assign select_ln46_89_fu_1454_p3 = ((icmp_ln46_89_fu_1448_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_89_fu_1432_p2);

assign select_ln46_90_fu_1498_p3 = ((icmp_ln46_90_fu_1492_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_90_fu_1476_p2);

assign select_ln46_91_fu_1542_p3 = ((icmp_ln46_91_fu_1536_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_91_fu_1520_p2);

assign select_ln46_92_fu_1586_p3 = ((icmp_ln46_92_fu_1580_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_92_fu_1564_p2);

assign select_ln46_93_fu_1630_p3 = ((icmp_ln46_93_fu_1624_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_93_fu_1608_p2);

assign select_ln46_94_fu_1674_p3 = ((icmp_ln46_94_fu_1668_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_94_fu_1652_p2);

assign select_ln46_fu_310_p3 = ((icmp_ln46_fu_304_p2[0:0] == 1'b1) ? 16'd65535 : shl_ln46_fu_288_p2);

assign shl_ln46_64_fu_332_p2 = data_1_val << 16'd6;

assign shl_ln46_65_fu_376_p2 = data_2_val << 16'd6;

assign shl_ln46_66_fu_420_p2 = data_3_val << 16'd6;

assign shl_ln46_67_fu_464_p2 = data_4_val << 16'd6;

assign shl_ln46_68_fu_508_p2 = data_5_val << 16'd6;

assign shl_ln46_69_fu_552_p2 = data_6_val << 16'd6;

assign shl_ln46_70_fu_596_p2 = data_7_val << 16'd6;

assign shl_ln46_71_fu_640_p2 = data_8_val << 16'd6;

assign shl_ln46_72_fu_684_p2 = data_9_val << 16'd6;

assign shl_ln46_73_fu_728_p2 = data_10_val << 16'd6;

assign shl_ln46_74_fu_772_p2 = data_11_val << 16'd6;

assign shl_ln46_75_fu_816_p2 = data_12_val << 16'd6;

assign shl_ln46_76_fu_860_p2 = data_13_val << 16'd6;

assign shl_ln46_77_fu_904_p2 = data_14_val << 16'd6;

assign shl_ln46_78_fu_948_p2 = data_15_val << 16'd6;

assign shl_ln46_79_fu_992_p2 = data_16_val << 16'd6;

assign shl_ln46_80_fu_1036_p2 = data_17_val << 16'd6;

assign shl_ln46_81_fu_1080_p2 = data_18_val << 16'd6;

assign shl_ln46_82_fu_1124_p2 = data_19_val << 16'd6;

assign shl_ln46_83_fu_1168_p2 = data_20_val << 16'd6;

assign shl_ln46_84_fu_1212_p2 = data_21_val << 16'd6;

assign shl_ln46_85_fu_1256_p2 = data_22_val << 16'd6;

assign shl_ln46_86_fu_1300_p2 = data_23_val << 16'd6;

assign shl_ln46_87_fu_1344_p2 = data_24_val << 16'd6;

assign shl_ln46_88_fu_1388_p2 = data_25_val << 16'd6;

assign shl_ln46_89_fu_1432_p2 = data_26_val << 16'd6;

assign shl_ln46_90_fu_1476_p2 = data_27_val << 16'd6;

assign shl_ln46_91_fu_1520_p2 = data_28_val << 16'd6;

assign shl_ln46_92_fu_1564_p2 = data_29_val << 16'd6;

assign shl_ln46_93_fu_1608_p2 = data_30_val << 16'd6;

assign shl_ln46_94_fu_1652_p2 = data_31_val << 16'd6;

assign shl_ln46_fu_288_p2 = data_0_val << 16'd6;

assign tmp_34_fu_338_p4 = {{data_1_val[15:10]}};

assign tmp_63_fu_426_p4 = {{data_3_val[15:10]}};

assign tmp_64_fu_470_p4 = {{data_4_val[15:10]}};

assign tmp_65_fu_514_p4 = {{data_5_val[15:10]}};

assign tmp_66_fu_558_p4 = {{data_6_val[15:10]}};

assign tmp_67_fu_602_p4 = {{data_7_val[15:10]}};

assign tmp_68_fu_646_p4 = {{data_8_val[15:10]}};

assign tmp_69_fu_690_p4 = {{data_9_val[15:10]}};

assign tmp_70_fu_734_p4 = {{data_10_val[15:10]}};

assign tmp_71_fu_778_p4 = {{data_11_val[15:10]}};

assign tmp_72_fu_822_p4 = {{data_12_val[15:10]}};

assign tmp_73_fu_866_p4 = {{data_13_val[15:10]}};

assign tmp_74_fu_910_p4 = {{data_14_val[15:10]}};

assign tmp_75_fu_954_p4 = {{data_15_val[15:10]}};

assign tmp_76_fu_998_p4 = {{data_16_val[15:10]}};

assign tmp_77_fu_1042_p4 = {{data_17_val[15:10]}};

assign tmp_78_fu_1086_p4 = {{data_18_val[15:10]}};

assign tmp_79_fu_1130_p4 = {{data_19_val[15:10]}};

assign tmp_80_fu_1174_p4 = {{data_20_val[15:10]}};

assign tmp_81_fu_1218_p4 = {{data_21_val[15:10]}};

assign tmp_82_fu_1262_p4 = {{data_22_val[15:10]}};

assign tmp_83_fu_1306_p4 = {{data_23_val[15:10]}};

assign tmp_84_fu_1350_p4 = {{data_24_val[15:10]}};

assign tmp_85_fu_1394_p4 = {{data_25_val[15:10]}};

assign tmp_86_fu_1438_p4 = {{data_26_val[15:10]}};

assign tmp_87_fu_1482_p4 = {{data_27_val[15:10]}};

assign tmp_88_fu_1526_p4 = {{data_28_val[15:10]}};

assign tmp_89_fu_1570_p4 = {{data_29_val[15:10]}};

assign tmp_90_fu_1614_p4 = {{data_30_val[15:10]}};

assign tmp_91_fu_1658_p4 = {{data_31_val[15:10]}};

assign tmp_fu_294_p4 = {{data_0_val[15:10]}};

assign tmp_s_fu_382_p4 = {{data_2_val[15:10]}};

assign ap_return_0 = select_ln45_fu_318_p3;

assign ap_return_1 = select_ln45_64_fu_362_p3;

assign ap_return_10 = select_ln45_73_fu_758_p3;

assign ap_return_11 = select_ln45_74_fu_802_p3;

assign ap_return_12 = select_ln45_75_fu_846_p3;

assign ap_return_13 = select_ln45_76_fu_890_p3;

assign ap_return_14 = select_ln45_77_fu_934_p3;

assign ap_return_15 = select_ln45_78_fu_978_p3;

assign ap_return_16 = select_ln45_79_fu_1022_p3;

assign ap_return_17 = select_ln45_80_fu_1066_p3;

assign ap_return_18 = select_ln45_81_fu_1110_p3;

assign ap_return_19 = select_ln45_82_fu_1154_p3;

assign ap_return_2 = select_ln45_65_fu_406_p3;

assign ap_return_20 = select_ln45_83_fu_1198_p3;

assign ap_return_21 = select_ln45_84_fu_1242_p3;

assign ap_return_22 = select_ln45_85_fu_1286_p3;

assign ap_return_23 = select_ln45_86_fu_1330_p3;

assign ap_return_24 = select_ln45_87_fu_1374_p3;

assign ap_return_25 = select_ln45_88_fu_1418_p3;

assign ap_return_26 = select_ln45_89_fu_1462_p3;

assign ap_return_27 = select_ln45_90_fu_1506_p3;

assign ap_return_28 = select_ln45_91_fu_1550_p3;

assign ap_return_29 = select_ln45_92_fu_1594_p3;

assign ap_return_3 = select_ln45_66_fu_450_p3;

assign ap_return_30 = select_ln45_93_fu_1638_p3;

assign ap_return_31 = select_ln45_94_fu_1682_p3;

assign ap_return_4 = select_ln45_67_fu_494_p3;

assign ap_return_5 = select_ln45_68_fu_538_p3;

assign ap_return_6 = select_ln45_69_fu_582_p3;

assign ap_return_7 = select_ln45_70_fu_626_p3;

assign ap_return_8 = select_ln45_71_fu_670_p3;

assign ap_return_9 = select_ln45_72_fu_714_p3;

assign icmp_ln45_64_fu_326_p2 = (($signed(data_1_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_65_fu_370_p2 = (($signed(data_2_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_66_fu_414_p2 = (($signed(data_3_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_67_fu_458_p2 = (($signed(data_4_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_68_fu_502_p2 = (($signed(data_5_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_69_fu_546_p2 = (($signed(data_6_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_70_fu_590_p2 = (($signed(data_7_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_71_fu_634_p2 = (($signed(data_8_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_72_fu_678_p2 = (($signed(data_9_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_73_fu_722_p2 = (($signed(data_10_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_74_fu_766_p2 = (($signed(data_11_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_75_fu_810_p2 = (($signed(data_12_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_76_fu_854_p2 = (($signed(data_13_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_77_fu_898_p2 = (($signed(data_14_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_78_fu_942_p2 = (($signed(data_15_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_79_fu_986_p2 = (($signed(data_16_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_80_fu_1030_p2 = (($signed(data_17_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_81_fu_1074_p2 = (($signed(data_18_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_82_fu_1118_p2 = (($signed(data_19_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_83_fu_1162_p2 = (($signed(data_20_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_84_fu_1206_p2 = (($signed(data_21_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_85_fu_1250_p2 = (($signed(data_22_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_86_fu_1294_p2 = (($signed(data_23_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_87_fu_1338_p2 = (($signed(data_24_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_88_fu_1382_p2 = (($signed(data_25_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_89_fu_1426_p2 = (($signed(data_26_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_90_fu_1470_p2 = (($signed(data_27_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_91_fu_1514_p2 = (($signed(data_28_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_92_fu_1558_p2 = (($signed(data_29_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_93_fu_1602_p2 = (($signed(data_30_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_94_fu_1646_p2 = (($signed(data_31_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

assign icmp_ln45_fu_282_p2 = (($signed(data_0_val) > $signed(16'd0)) ? 1'b1 : 1'b0);

endmodule //ParamEst_NN_relu_ap_fixed_ap_ufixed_16_0_4_0_0_PARAMEST_NN_relu_config5_s
