// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config17_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;

wire   [24:0] y_fu_344_p3;
wire   [24:0] add_ln54_fu_352_p2;
wire   [14:0] trunc_ln54_5_fu_368_p4;
wire   [24:0] y_5_fu_382_p3;
wire   [24:0] add_ln54_5_fu_390_p2;
wire   [24:0] y_6_fu_406_p3;
wire   [24:0] add_ln54_6_fu_414_p2;
wire   [24:0] y_7_fu_430_p3;
wire   [24:0] add_ln54_7_fu_438_p2;
wire   [24:0] y_8_fu_454_p3;
wire   [24:0] add_ln54_8_fu_462_p2;
wire   [23:0] y_9_fu_478_p3;
wire  signed [24:0] sext_ln54_3_fu_486_p1;
wire   [24:0] add_ln54_9_fu_490_p2;
wire   [24:0] y_28_fu_506_p3;
wire   [24:0] add_ln54_10_fu_514_p2;
wire   [23:0] y_1_fu_530_p3;
wire  signed [24:0] sext_ln54_4_fu_538_p1;
wire   [24:0] add_ln54_11_fu_542_p2;
wire   [24:0] y_2_fu_558_p3;
wire   [24:0] add_ln54_12_fu_566_p2;
wire   [24:0] y_3_fu_582_p3;
wire   [24:0] add_ln54_13_fu_590_p2;
wire   [24:0] y_4_fu_606_p3;
wire   [24:0] add_ln54_14_fu_614_p2;
wire   [24:0] y_10_fu_630_p3;
wire   [24:0] add_ln54_15_fu_638_p2;
wire   [24:0] y_11_fu_654_p3;
wire   [24:0] add_ln54_16_fu_662_p2;
wire   [24:0] y_12_fu_678_p3;
wire   [24:0] add_ln54_17_fu_686_p2;
wire   [24:0] y_13_fu_702_p3;
wire   [24:0] add_ln54_18_fu_710_p2;
wire   [14:0] trunc_ln54_15_fu_726_p4;
wire   [23:0] y_14_fu_740_p3;
wire  signed [24:0] sext_ln54_5_fu_748_p1;
wire   [24:0] add_ln54_19_fu_752_p2;
wire   [24:0] y_15_fu_768_p3;
wire   [24:0] add_ln54_20_fu_776_p2;
wire   [24:0] y_16_fu_792_p3;
wire   [24:0] add_ln54_21_fu_800_p2;
wire   [14:0] trunc_ln54_19_fu_816_p4;
wire   [24:0] y_17_fu_830_p3;
wire   [24:0] add_ln54_22_fu_838_p2;
wire   [23:0] y_18_fu_854_p3;
wire  signed [24:0] sext_ln54_6_fu_862_p1;
wire   [24:0] add_ln54_23_fu_866_p2;
wire   [23:0] y_19_fu_882_p3;
wire  signed [24:0] sext_ln54_7_fu_890_p1;
wire   [24:0] add_ln54_24_fu_894_p2;
wire   [24:0] y_20_fu_910_p3;
wire   [24:0] add_ln54_25_fu_918_p2;
wire   [24:0] y_21_fu_934_p3;
wire   [24:0] add_ln54_26_fu_942_p2;
wire   [24:0] y_22_fu_958_p3;
wire   [24:0] add_ln54_27_fu_966_p2;
wire   [24:0] y_23_fu_982_p3;
wire   [24:0] add_ln54_28_fu_990_p2;
wire   [23:0] y_24_fu_1006_p3;
wire  signed [24:0] sext_ln54_8_fu_1014_p1;
wire   [24:0] add_ln54_29_fu_1018_p2;
wire   [24:0] y_25_fu_1034_p3;
wire   [24:0] add_ln54_30_fu_1042_p2;
wire   [22:0] y_26_fu_1058_p3;
wire  signed [23:0] sext_ln85_fu_1066_p1;
wire   [23:0] add_ln54_31_fu_1070_p2;
wire   [14:0] trunc_ln54_29_fu_1076_p4;
wire  signed [15:0] sext_ln54_fu_378_p1;
wire  signed [15:0] sext_ln54_1_fu_736_p1;
wire  signed [15:0] sext_ln54_2_fu_826_p1;
wire  signed [15:0] sext_ln54_9_fu_1086_p1;

assign add_ln54_10_fu_514_p2 = (y_28_fu_506_p3 + 25'd67584);

assign add_ln54_11_fu_542_p2 = ($signed(sext_ln54_4_fu_538_p1) + $signed(25'd33549504));

assign add_ln54_12_fu_566_p2 = (y_2_fu_558_p3 + 25'd33280);

assign add_ln54_13_fu_590_p2 = (y_3_fu_582_p3 + 25'd29184);

assign add_ln54_14_fu_614_p2 = (y_4_fu_606_p3 + 25'd18432);

assign add_ln54_15_fu_638_p2 = (y_10_fu_630_p3 + 25'd126976);

assign add_ln54_16_fu_662_p2 = ($signed(y_11_fu_654_p3) + $signed(25'd33518592));

assign add_ln54_17_fu_686_p2 = (y_12_fu_678_p3 + 25'd104960);

assign add_ln54_18_fu_710_p2 = (y_13_fu_702_p3 + 25'd46592);

assign add_ln54_19_fu_752_p2 = ($signed(sext_ln54_5_fu_748_p1) + $signed(25'd33548624));

assign add_ln54_20_fu_776_p2 = (y_15_fu_768_p3 + 25'd71168);

assign add_ln54_21_fu_800_p2 = (y_16_fu_792_p3 + 25'd26624);

assign add_ln54_22_fu_838_p2 = ($signed(y_17_fu_830_p3) + $signed(25'd33544704));

assign add_ln54_23_fu_866_p2 = ($signed(sext_ln54_6_fu_862_p1) + $signed(25'd60944));

assign add_ln54_24_fu_894_p2 = ($signed(sext_ln54_7_fu_890_p1) + $signed(25'd33544624));

assign add_ln54_25_fu_918_p2 = (y_20_fu_910_p3 + 25'd31232);

assign add_ln54_26_fu_942_p2 = ($signed(y_21_fu_934_p3) + $signed(25'd33526272));

assign add_ln54_27_fu_966_p2 = ($signed(y_22_fu_958_p3) + $signed(25'd33532416));

assign add_ln54_28_fu_990_p2 = (y_23_fu_982_p3 + 25'd4096);

assign add_ln54_29_fu_1018_p2 = ($signed(sext_ln54_8_fu_1014_p1) + $signed(25'd33546432));

assign add_ln54_30_fu_1042_p2 = (y_25_fu_1034_p3 + 25'd29184);

assign add_ln54_31_fu_1070_p2 = ($signed(sext_ln85_fu_1066_p1) + $signed(24'd16771104));

assign add_ln54_5_fu_390_p2 = (y_5_fu_382_p3 + 25'd15360);

assign add_ln54_6_fu_414_p2 = (y_6_fu_406_p3 + 25'd12800);

assign add_ln54_7_fu_438_p2 = (y_7_fu_430_p3 + 25'd39424);

assign add_ln54_8_fu_462_p2 = (y_8_fu_454_p3 + 25'd18944);

assign add_ln54_9_fu_490_p2 = ($signed(sext_ln54_3_fu_486_p1) + $signed(25'd33549744));

assign add_ln54_fu_352_p2 = (y_fu_344_p3 + 25'd15360);

assign ap_ready = 1'b1;

assign sext_ln54_1_fu_736_p1 = $signed(trunc_ln54_15_fu_726_p4);

assign sext_ln54_2_fu_826_p1 = $signed(trunc_ln54_19_fu_816_p4);

assign sext_ln54_3_fu_486_p1 = $signed(y_9_fu_478_p3);

assign sext_ln54_4_fu_538_p1 = $signed(y_1_fu_530_p3);

assign sext_ln54_5_fu_748_p1 = $signed(y_14_fu_740_p3);

assign sext_ln54_6_fu_862_p1 = $signed(y_18_fu_854_p3);

assign sext_ln54_7_fu_890_p1 = $signed(y_19_fu_882_p3);

assign sext_ln54_8_fu_1014_p1 = $signed(y_24_fu_1006_p3);

assign sext_ln54_9_fu_1086_p1 = $signed(trunc_ln54_29_fu_1076_p4);

assign sext_ln54_fu_378_p1 = $signed(trunc_ln54_5_fu_368_p4);

assign sext_ln85_fu_1066_p1 = $signed(y_26_fu_1058_p3);

assign trunc_ln54_15_fu_726_p4 = {{data_17_val[15:1]}};

assign trunc_ln54_19_fu_816_p4 = {{data_21_val[15:1]}};

assign trunc_ln54_29_fu_1076_p4 = {{add_ln54_31_fu_1070_p2[23:9]}};

assign trunc_ln54_5_fu_368_p4 = {{data_1_val[15:1]}};

assign y_10_fu_630_p3 = {{data_13_val}, {9'd0}};

assign y_11_fu_654_p3 = {{data_14_val}, {9'd0}};

assign y_12_fu_678_p3 = {{data_15_val}, {9'd0}};

assign y_13_fu_702_p3 = {{data_16_val}, {9'd0}};

assign y_14_fu_740_p3 = {{data_18_val}, {8'd0}};

assign y_15_fu_768_p3 = {{data_19_val}, {9'd0}};

assign y_16_fu_792_p3 = {{data_20_val}, {9'd0}};

assign y_17_fu_830_p3 = {{data_22_val}, {9'd0}};

assign y_18_fu_854_p3 = {{data_23_val}, {8'd0}};

assign y_19_fu_882_p3 = {{data_24_val}, {8'd0}};

assign y_1_fu_530_p3 = {{data_8_val}, {8'd0}};

assign y_20_fu_910_p3 = {{data_25_val}, {9'd0}};

assign y_21_fu_934_p3 = {{data_26_val}, {9'd0}};

assign y_22_fu_958_p3 = {{data_27_val}, {9'd0}};

assign y_23_fu_982_p3 = {{data_28_val}, {9'd0}};

assign y_24_fu_1006_p3 = {{data_29_val}, {8'd0}};

assign y_25_fu_1034_p3 = {{data_30_val}, {9'd0}};

assign y_26_fu_1058_p3 = {{data_31_val}, {7'd0}};

assign y_28_fu_506_p3 = {{data_7_val}, {9'd0}};

assign y_2_fu_558_p3 = {{data_9_val}, {9'd0}};

assign y_3_fu_582_p3 = {{data_10_val}, {9'd0}};

assign y_4_fu_606_p3 = {{data_12_val}, {9'd0}};

assign y_5_fu_382_p3 = {{data_2_val}, {9'd0}};

assign y_6_fu_406_p3 = {{data_3_val}, {9'd0}};

assign y_7_fu_430_p3 = {{data_4_val}, {9'd0}};

assign y_8_fu_454_p3 = {{data_5_val}, {9'd0}};

assign y_9_fu_478_p3 = {{data_6_val}, {8'd0}};

assign y_fu_344_p3 = {{data_0_val}, {9'd0}};

assign ap_return_0 = {{add_ln54_fu_352_p2[24:9]}};

assign ap_return_1 = sext_ln54_fu_378_p1;

assign ap_return_10 = {{add_ln54_13_fu_590_p2[24:9]}};

assign ap_return_11 = {{add_ln54_14_fu_614_p2[24:9]}};

assign ap_return_12 = {{add_ln54_15_fu_638_p2[24:9]}};

assign ap_return_13 = {{add_ln54_16_fu_662_p2[24:9]}};

assign ap_return_14 = {{add_ln54_17_fu_686_p2[24:9]}};

assign ap_return_15 = {{add_ln54_18_fu_710_p2[24:9]}};

assign ap_return_16 = sext_ln54_1_fu_736_p1;

assign ap_return_17 = {{add_ln54_19_fu_752_p2[24:9]}};

assign ap_return_18 = {{add_ln54_20_fu_776_p2[24:9]}};

assign ap_return_19 = {{add_ln54_21_fu_800_p2[24:9]}};

assign ap_return_2 = {{add_ln54_5_fu_390_p2[24:9]}};

assign ap_return_20 = sext_ln54_2_fu_826_p1;

assign ap_return_21 = {{add_ln54_22_fu_838_p2[24:9]}};

assign ap_return_22 = {{add_ln54_23_fu_866_p2[24:9]}};

assign ap_return_23 = {{add_ln54_24_fu_894_p2[24:9]}};

assign ap_return_24 = {{add_ln54_25_fu_918_p2[24:9]}};

assign ap_return_25 = {{add_ln54_26_fu_942_p2[24:9]}};

assign ap_return_26 = {{add_ln54_27_fu_966_p2[24:9]}};

assign ap_return_27 = {{add_ln54_28_fu_990_p2[24:9]}};

assign ap_return_28 = {{add_ln54_29_fu_1018_p2[24:9]}};

assign ap_return_29 = {{add_ln54_30_fu_1042_p2[24:9]}};

assign ap_return_3 = {{add_ln54_6_fu_414_p2[24:9]}};

assign ap_return_30 = sext_ln54_9_fu_1086_p1;

assign ap_return_4 = {{add_ln54_7_fu_438_p2[24:9]}};

assign ap_return_5 = {{add_ln54_8_fu_462_p2[24:9]}};

assign ap_return_6 = {{add_ln54_9_fu_490_p2[24:9]}};

assign ap_return_7 = {{add_ln54_10_fu_514_p2[24:9]}};

assign ap_return_8 = {{add_ln54_11_fu_542_p2[24:9]}};

assign ap_return_9 = {{add_ln54_12_fu_566_p2[24:9]}};

endmodule //ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config17_s
