// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config16_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        data_6_val,
        data_7_val,
        data_8_val,
        data_9_val,
        data_10_val,
        data_11_val,
        data_12_val,
        data_13_val,
        data_14_val,
        data_15_val,
        data_16_val,
        data_17_val,
        data_18_val,
        data_19_val,
        data_20_val,
        data_21_val,
        data_22_val,
        data_23_val,
        data_24_val,
        data_25_val,
        data_26_val,
        data_27_val,
        data_28_val,
        data_29_val,
        data_30_val,
        data_31_val,
        data_32_val,
        data_33_val,
        data_34_val,
        data_35_val,
        data_36_val,
        data_37_val,
        data_38_val,
        data_39_val,
        data_40_val,
        data_41_val,
        data_42_val,
        data_43_val,
        data_44_val,
        data_45_val,
        data_46_val,
        data_47_val,
        data_48_val,
        data_49_val,
        data_50_val,
        data_51_val,
        data_52_val,
        data_53_val,
        data_54_val,
        data_55_val,
        data_56_val,
        data_57_val,
        data_58_val,
        data_59_val,
        data_60_val,
        data_61_val,
        data_62_val,
        data_63_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24,
        ap_return_25,
        ap_return_26,
        ap_return_27,
        ap_return_28,
        ap_return_29,
        ap_return_30,
        ap_return_31,
        ap_return_32,
        ap_return_33,
        ap_return_34,
        ap_return_35,
        ap_return_36,
        ap_return_37,
        ap_return_38,
        ap_return_39,
        ap_return_40,
        ap_return_41,
        ap_return_42,
        ap_return_43,
        ap_return_44,
        ap_return_45,
        ap_return_46,
        ap_return_47,
        ap_return_48,
        ap_return_49,
        ap_return_50,
        ap_return_51,
        ap_return_52,
        ap_return_53,
        ap_return_54,
        ap_return_55,
        ap_return_56,
        ap_return_57,
        ap_return_58,
        ap_return_59,
        ap_return_60,
        ap_return_61,
        ap_return_62,
        ap_return_63
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
input  [15:0] data_6_val;
input  [15:0] data_7_val;
input  [15:0] data_8_val;
input  [15:0] data_9_val;
input  [15:0] data_10_val;
input  [15:0] data_11_val;
input  [15:0] data_12_val;
input  [15:0] data_13_val;
input  [15:0] data_14_val;
input  [15:0] data_15_val;
input  [15:0] data_16_val;
input  [15:0] data_17_val;
input  [15:0] data_18_val;
input  [15:0] data_19_val;
input  [15:0] data_20_val;
input  [15:0] data_21_val;
input  [15:0] data_22_val;
input  [15:0] data_23_val;
input  [15:0] data_24_val;
input  [15:0] data_25_val;
input  [15:0] data_26_val;
input  [15:0] data_27_val;
input  [15:0] data_28_val;
input  [15:0] data_29_val;
input  [15:0] data_30_val;
input  [15:0] data_31_val;
input  [15:0] data_32_val;
input  [15:0] data_33_val;
input  [15:0] data_34_val;
input  [15:0] data_35_val;
input  [15:0] data_36_val;
input  [15:0] data_37_val;
input  [15:0] data_38_val;
input  [15:0] data_39_val;
input  [15:0] data_40_val;
input  [15:0] data_41_val;
input  [15:0] data_42_val;
input  [15:0] data_43_val;
input  [15:0] data_44_val;
input  [15:0] data_45_val;
input  [15:0] data_46_val;
input  [15:0] data_47_val;
input  [15:0] data_48_val;
input  [15:0] data_49_val;
input  [15:0] data_50_val;
input  [15:0] data_51_val;
input  [15:0] data_52_val;
input  [15:0] data_53_val;
input  [15:0] data_54_val;
input  [15:0] data_55_val;
input  [15:0] data_56_val;
input  [15:0] data_57_val;
input  [15:0] data_58_val;
input  [15:0] data_59_val;
input  [15:0] data_60_val;
input  [15:0] data_61_val;
input  [15:0] data_62_val;
input  [15:0] data_63_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;
output  [15:0] ap_return_10;
output  [15:0] ap_return_11;
output  [15:0] ap_return_12;
output  [15:0] ap_return_13;
output  [15:0] ap_return_14;
output  [15:0] ap_return_15;
output  [15:0] ap_return_16;
output  [15:0] ap_return_17;
output  [15:0] ap_return_18;
output  [15:0] ap_return_19;
output  [15:0] ap_return_20;
output  [15:0] ap_return_21;
output  [15:0] ap_return_22;
output  [15:0] ap_return_23;
output  [15:0] ap_return_24;
output  [15:0] ap_return_25;
output  [15:0] ap_return_26;
output  [15:0] ap_return_27;
output  [15:0] ap_return_28;
output  [15:0] ap_return_29;
output  [15:0] ap_return_30;
output  [15:0] ap_return_31;
output  [15:0] ap_return_32;
output  [15:0] ap_return_33;
output  [15:0] ap_return_34;
output  [15:0] ap_return_35;
output  [15:0] ap_return_36;
output  [15:0] ap_return_37;
output  [15:0] ap_return_38;
output  [15:0] ap_return_39;
output  [15:0] ap_return_40;
output  [15:0] ap_return_41;
output  [15:0] ap_return_42;
output  [15:0] ap_return_43;
output  [15:0] ap_return_44;
output  [15:0] ap_return_45;
output  [15:0] ap_return_46;
output  [15:0] ap_return_47;
output  [15:0] ap_return_48;
output  [15:0] ap_return_49;
output  [15:0] ap_return_50;
output  [15:0] ap_return_51;
output  [15:0] ap_return_52;
output  [15:0] ap_return_53;
output  [15:0] ap_return_54;
output  [15:0] ap_return_55;
output  [15:0] ap_return_56;
output  [15:0] ap_return_57;
output  [15:0] ap_return_58;
output  [15:0] ap_return_59;
output  [15:0] ap_return_60;
output  [15:0] ap_return_61;
output  [15:0] ap_return_62;
output  [15:0] ap_return_63;

wire   [23:0] y_fu_648_p3;
wire   [23:0] add_ln54_fu_656_p2;
wire   [23:0] y_82_fu_672_p3;
wire   [23:0] add_ln54_32_fu_680_p2;
wire   [23:0] y_27_fu_696_p3;
wire   [23:0] add_ln54_33_fu_704_p2;
wire   [23:0] y_28_fu_720_p3;
wire   [23:0] add_ln54_34_fu_728_p2;
wire   [23:0] y_29_fu_744_p3;
wire   [23:0] add_ln54_35_fu_752_p2;
wire   [23:0] y_30_fu_768_p3;
wire   [23:0] add_ln54_36_fu_776_p2;
wire   [23:0] y_31_fu_792_p3;
wire   [23:0] add_ln54_37_fu_800_p2;
wire   [23:0] y_32_fu_816_p3;
wire   [23:0] add_ln54_38_fu_824_p2;
wire   [22:0] y_33_fu_840_p3;
wire  signed [23:0] sext_ln54_10_fu_848_p1;
wire   [23:0] add_ln54_39_fu_852_p2;
wire   [23:0] y_34_fu_868_p3;
wire   [23:0] add_ln54_40_fu_876_p2;
wire   [23:0] y_35_fu_892_p3;
wire   [23:0] add_ln54_41_fu_900_p2;
wire   [23:0] y_36_fu_916_p3;
wire   [23:0] add_ln54_42_fu_924_p2;
wire   [14:0] trunc_ln54_40_fu_940_p4;
wire   [22:0] y_37_fu_954_p3;
wire  signed [23:0] sext_ln54_11_fu_962_p1;
wire   [23:0] add_ln54_43_fu_966_p2;
wire   [23:0] y_38_fu_982_p3;
wire   [23:0] add_ln54_44_fu_990_p2;
wire   [23:0] y_39_fu_1006_p3;
wire   [23:0] add_ln54_45_fu_1014_p2;
wire   [23:0] y_40_fu_1030_p3;
wire   [23:0] add_ln54_46_fu_1038_p2;
wire   [23:0] y_41_fu_1054_p3;
wire   [23:0] add_ln54_47_fu_1062_p2;
wire   [23:0] y_42_fu_1078_p3;
wire   [23:0] add_ln54_48_fu_1086_p2;
wire   [23:0] y_43_fu_1102_p3;
wire   [23:0] add_ln54_49_fu_1110_p2;
wire   [23:0] y_44_fu_1126_p3;
wire   [23:0] add_ln54_50_fu_1134_p2;
wire   [23:0] y_45_fu_1150_p3;
wire   [23:0] add_ln54_51_fu_1158_p2;
wire   [23:0] y_46_fu_1174_p3;
wire   [23:0] add_ln54_52_fu_1182_p2;
wire   [14:0] trunc_ln54_51_fu_1198_p4;
wire   [23:0] y_47_fu_1212_p3;
wire   [23:0] add_ln54_53_fu_1220_p2;
wire   [23:0] y_48_fu_1236_p3;
wire   [23:0] add_ln54_54_fu_1244_p2;
wire   [23:0] y_49_fu_1260_p3;
wire   [23:0] add_ln54_55_fu_1268_p2;
wire   [23:0] y_50_fu_1284_p3;
wire   [23:0] add_ln54_56_fu_1292_p2;
wire   [23:0] y_51_fu_1308_p3;
wire   [23:0] add_ln54_57_fu_1316_p2;
wire   [23:0] y_52_fu_1332_p3;
wire   [23:0] add_ln54_58_fu_1340_p2;
wire   [23:0] y_53_fu_1356_p3;
wire   [23:0] add_ln54_59_fu_1364_p2;
wire   [23:0] y_54_fu_1380_p3;
wire   [23:0] add_ln54_60_fu_1388_p2;
wire   [23:0] y_55_fu_1404_p3;
wire   [23:0] add_ln54_61_fu_1412_p2;
wire   [23:0] y_56_fu_1428_p3;
wire   [23:0] add_ln54_62_fu_1436_p2;
wire   [23:0] y_57_fu_1452_p3;
wire   [23:0] add_ln54_63_fu_1460_p2;
wire   [22:0] y_58_fu_1476_p3;
wire  signed [23:0] sext_ln54_12_fu_1484_p1;
wire   [23:0] add_ln54_64_fu_1488_p2;
wire   [23:0] y_59_fu_1504_p3;
wire   [23:0] add_ln54_65_fu_1512_p2;
wire   [14:0] trunc_ln54_65_fu_1528_p4;
wire   [23:0] y_60_fu_1542_p3;
wire   [23:0] add_ln54_66_fu_1550_p2;
wire   [23:0] y_61_fu_1566_p3;
wire   [23:0] add_ln54_67_fu_1574_p2;
wire   [23:0] y_62_fu_1590_p3;
wire   [23:0] add_ln54_68_fu_1598_p2;
wire   [22:0] y_63_fu_1614_p3;
wire  signed [23:0] sext_ln54_13_fu_1622_p1;
wire   [23:0] add_ln54_69_fu_1626_p2;
wire   [14:0] trunc_ln54_70_fu_1642_p4;
wire   [22:0] y_64_fu_1656_p3;
wire  signed [23:0] sext_ln54_14_fu_1664_p1;
wire   [23:0] add_ln54_70_fu_1668_p2;
wire   [14:0] trunc_ln54_72_fu_1684_p4;
wire   [14:0] trunc_ln54_73_fu_1698_p4;
wire   [14:0] trunc_ln54_74_fu_1712_p4;
wire   [23:0] y_65_fu_1726_p3;
wire   [23:0] add_ln54_71_fu_1734_p2;
wire   [23:0] y_66_fu_1750_p3;
wire   [23:0] add_ln54_72_fu_1758_p2;
wire   [23:0] y_67_fu_1774_p3;
wire   [23:0] add_ln54_73_fu_1782_p2;
wire   [23:0] y_68_fu_1798_p3;
wire   [23:0] add_ln54_74_fu_1806_p2;
wire   [22:0] y_69_fu_1822_p3;
wire  signed [23:0] sext_ln54_15_fu_1830_p1;
wire   [23:0] add_ln54_75_fu_1834_p2;
wire   [23:0] y_70_fu_1850_p3;
wire   [23:0] add_ln54_76_fu_1858_p2;
wire   [14:0] trunc_ln54_81_fu_1874_p4;
wire   [23:0] y_71_fu_1888_p3;
wire   [23:0] add_ln54_77_fu_1896_p2;
wire   [23:0] y_72_fu_1912_p3;
wire   [23:0] add_ln54_78_fu_1920_p2;
wire   [22:0] y_73_fu_1936_p3;
wire  signed [23:0] sext_ln54_16_fu_1944_p1;
wire   [23:0] add_ln54_79_fu_1948_p2;
wire   [22:0] y_74_fu_1964_p3;
wire  signed [23:0] sext_ln54_17_fu_1972_p1;
wire   [23:0] add_ln54_80_fu_1976_p2;
wire   [23:0] y_75_fu_1992_p3;
wire   [23:0] add_ln54_81_fu_2000_p2;
wire   [23:0] y_76_fu_2016_p3;
wire   [23:0] add_ln54_82_fu_2024_p2;
wire   [23:0] y_77_fu_2040_p3;
wire   [23:0] add_ln54_83_fu_2048_p2;
wire   [23:0] y_78_fu_2064_p3;
wire   [23:0] add_ln54_84_fu_2072_p2;
wire   [22:0] y_79_fu_2088_p3;
wire  signed [23:0] sext_ln54_18_fu_2096_p1;
wire   [23:0] add_ln54_85_fu_2100_p2;
wire   [23:0] y_80_fu_2116_p3;
wire   [23:0] add_ln54_86_fu_2124_p2;
wire  signed [15:0] sext_ln54_fu_950_p1;
wire  signed [15:0] sext_ln54_3_fu_1208_p1;
wire  signed [15:0] sext_ln54_4_fu_1538_p1;
wire  signed [15:0] sext_ln54_5_fu_1652_p1;
wire  signed [15:0] sext_ln54_6_fu_1694_p1;
wire  signed [15:0] sext_ln54_7_fu_1708_p1;
wire  signed [15:0] sext_ln54_8_fu_1722_p1;
wire  signed [15:0] sext_ln54_9_fu_1884_p1;

assign add_ln54_32_fu_680_p2 = (y_82_fu_672_p3 + 24'd3328);

assign add_ln54_33_fu_704_p2 = (y_27_fu_696_p3 + 24'd2304);

assign add_ln54_34_fu_728_p2 = (y_28_fu_720_p3 + 24'd6400);

assign add_ln54_35_fu_752_p2 = ($signed(y_29_fu_744_p3) + $signed(24'd16773376));

assign add_ln54_36_fu_776_p2 = (y_30_fu_768_p3 + 24'd13568);

assign add_ln54_37_fu_800_p2 = (y_31_fu_792_p3 + 24'd14848);

assign add_ln54_38_fu_824_p2 = (y_32_fu_816_p3 + 24'd10496);

assign add_ln54_39_fu_852_p2 = ($signed(sext_ln54_10_fu_848_p1) + $signed(24'd5664));

assign add_ln54_40_fu_876_p2 = (y_34_fu_868_p3 + 24'd16640);

assign add_ln54_41_fu_900_p2 = (y_35_fu_892_p3 + 24'd23040);

assign add_ln54_42_fu_924_p2 = (y_36_fu_916_p3 + 24'd10752);

assign add_ln54_43_fu_966_p2 = ($signed(sext_ln54_11_fu_962_p1) + $signed(24'd16769752));

assign add_ln54_44_fu_990_p2 = (y_38_fu_982_p3 + 24'd5888);

assign add_ln54_45_fu_1014_p2 = (y_39_fu_1006_p3 + 24'd12800);

assign add_ln54_46_fu_1038_p2 = (y_40_fu_1030_p3 + 24'd21504);

assign add_ln54_47_fu_1062_p2 = (y_41_fu_1054_p3 + 24'd4608);

assign add_ln54_48_fu_1086_p2 = ($signed(y_42_fu_1078_p3) + $signed(24'd16773888));

assign add_ln54_49_fu_1110_p2 = (y_43_fu_1102_p3 + 24'd23808);

assign add_ln54_50_fu_1134_p2 = (y_44_fu_1126_p3 + 24'd3584);

assign add_ln54_51_fu_1158_p2 = (y_45_fu_1150_p3 + 24'd15104);

assign add_ln54_52_fu_1182_p2 = (y_46_fu_1174_p3 + 24'd11776);

assign add_ln54_53_fu_1220_p2 = ($signed(y_47_fu_1212_p3) + $signed(24'd16772608));

assign add_ln54_54_fu_1244_p2 = ($signed(y_48_fu_1236_p3) + $signed(24'd16773120));

assign add_ln54_55_fu_1268_p2 = ($signed(y_49_fu_1260_p3) + $signed(24'd16771840));

assign add_ln54_56_fu_1292_p2 = (y_50_fu_1284_p3 + 24'd3328);

assign add_ln54_57_fu_1316_p2 = (y_51_fu_1308_p3 + 24'd8704);

assign add_ln54_58_fu_1340_p2 = (y_52_fu_1332_p3 + 24'd9728);

assign add_ln54_59_fu_1364_p2 = (y_53_fu_1356_p3 + 24'd19712);

assign add_ln54_60_fu_1388_p2 = (y_54_fu_1380_p3 + 24'd12544);

assign add_ln54_61_fu_1412_p2 = (y_55_fu_1404_p3 + 24'd15360);

assign add_ln54_62_fu_1436_p2 = (y_56_fu_1428_p3 + 24'd5632);

assign add_ln54_63_fu_1460_p2 = ($signed(y_57_fu_1452_p3) + $signed(24'd16748288));

assign add_ln54_64_fu_1488_p2 = ($signed(sext_ln54_12_fu_1484_p1) + $signed(24'd16767416));

assign add_ln54_65_fu_1512_p2 = (y_59_fu_1504_p3 + 24'd2304);

assign add_ln54_66_fu_1550_p2 = (y_60_fu_1542_p3 + 24'd14592);

assign add_ln54_67_fu_1574_p2 = (y_61_fu_1566_p3 + 24'd9472);

assign add_ln54_68_fu_1598_p2 = ($signed(y_62_fu_1590_p3) + $signed(24'd16766208));

assign add_ln54_69_fu_1626_p2 = ($signed(sext_ln54_13_fu_1622_p1) + $signed(24'd16769016));

assign add_ln54_70_fu_1668_p2 = ($signed(sext_ln54_14_fu_1664_p1) + $signed(24'd16774048));

assign add_ln54_71_fu_1734_p2 = (y_65_fu_1726_p3 + 24'd40704);

assign add_ln54_72_fu_1758_p2 = ($signed(y_66_fu_1750_p3) + $signed(24'd16773120));

assign add_ln54_73_fu_1782_p2 = (y_67_fu_1774_p3 + 24'd7680);

assign add_ln54_74_fu_1806_p2 = (y_68_fu_1798_p3 + 24'd33024);

assign add_ln54_75_fu_1834_p2 = ($signed(sext_ln54_15_fu_1830_p1) + $signed(24'd16775176));

assign add_ln54_76_fu_1858_p2 = ($signed(y_70_fu_1850_p3) + $signed(24'd16776960));

assign add_ln54_77_fu_1896_p2 = (y_71_fu_1888_p3 + 24'd23040);

assign add_ln54_78_fu_1920_p2 = ($signed(y_72_fu_1912_p3) + $signed(24'd16776448));

assign add_ln54_79_fu_1948_p2 = ($signed(sext_ln54_16_fu_1944_p1) + $signed(24'd16769784));

assign add_ln54_80_fu_1976_p2 = ($signed(sext_ln54_17_fu_1972_p1) + $signed(24'd16773584));

assign add_ln54_81_fu_2000_p2 = ($signed(y_75_fu_1992_p3) + $signed(24'd16770560));

assign add_ln54_82_fu_2024_p2 = ($signed(y_76_fu_2016_p3) + $signed(24'd16767232));

assign add_ln54_83_fu_2048_p2 = ($signed(y_77_fu_2040_p3) + $signed(24'd16771328));

assign add_ln54_84_fu_2072_p2 = (y_78_fu_2064_p3 + 24'd12544);

assign add_ln54_85_fu_2100_p2 = ($signed(sext_ln54_18_fu_2096_p1) + $signed(24'd16756728));

assign add_ln54_86_fu_2124_p2 = ($signed(y_80_fu_2116_p3) + $signed(24'd16770304));

assign add_ln54_fu_656_p2 = (y_fu_648_p3 + 24'd9472);

assign ap_ready = 1'b1;

assign sext_ln54_10_fu_848_p1 = $signed(y_33_fu_840_p3);

assign sext_ln54_11_fu_962_p1 = $signed(y_37_fu_954_p3);

assign sext_ln54_12_fu_1484_p1 = $signed(y_58_fu_1476_p3);

assign sext_ln54_13_fu_1622_p1 = $signed(y_63_fu_1614_p3);

assign sext_ln54_14_fu_1664_p1 = $signed(y_64_fu_1656_p3);

assign sext_ln54_15_fu_1830_p1 = $signed(y_69_fu_1822_p3);

assign sext_ln54_16_fu_1944_p1 = $signed(y_73_fu_1936_p3);

assign sext_ln54_17_fu_1972_p1 = $signed(y_74_fu_1964_p3);

assign sext_ln54_18_fu_2096_p1 = $signed(y_79_fu_2088_p3);

assign sext_ln54_3_fu_1208_p1 = $signed(trunc_ln54_51_fu_1198_p4);

assign sext_ln54_4_fu_1538_p1 = $signed(trunc_ln54_65_fu_1528_p4);

assign sext_ln54_5_fu_1652_p1 = $signed(trunc_ln54_70_fu_1642_p4);

assign sext_ln54_6_fu_1694_p1 = $signed(trunc_ln54_72_fu_1684_p4);

assign sext_ln54_7_fu_1708_p1 = $signed(trunc_ln54_73_fu_1698_p4);

assign sext_ln54_8_fu_1722_p1 = $signed(trunc_ln54_74_fu_1712_p4);

assign sext_ln54_9_fu_1884_p1 = $signed(trunc_ln54_81_fu_1874_p4);

assign sext_ln54_fu_950_p1 = $signed(trunc_ln54_40_fu_940_p4);

assign trunc_ln54_40_fu_940_p4 = {{data_12_val[15:1]}};

assign trunc_ln54_51_fu_1198_p4 = {{data_23_val[15:1]}};

assign trunc_ln54_65_fu_1528_p4 = {{data_37_val[15:1]}};

assign trunc_ln54_70_fu_1642_p4 = {{data_42_val[15:1]}};

assign trunc_ln54_72_fu_1684_p4 = {{data_44_val[15:1]}};

assign trunc_ln54_73_fu_1698_p4 = {{data_45_val[15:1]}};

assign trunc_ln54_74_fu_1712_p4 = {{data_46_val[15:1]}};

assign trunc_ln54_81_fu_1874_p4 = {{data_53_val[15:1]}};

assign y_27_fu_696_p3 = {{data_2_val}, {8'd0}};

assign y_28_fu_720_p3 = {{data_3_val}, {8'd0}};

assign y_29_fu_744_p3 = {{data_4_val}, {8'd0}};

assign y_30_fu_768_p3 = {{data_5_val}, {8'd0}};

assign y_31_fu_792_p3 = {{data_6_val}, {8'd0}};

assign y_32_fu_816_p3 = {{data_7_val}, {8'd0}};

assign y_33_fu_840_p3 = {{data_8_val}, {7'd0}};

assign y_34_fu_868_p3 = {{data_9_val}, {8'd0}};

assign y_35_fu_892_p3 = {{data_10_val}, {8'd0}};

assign y_36_fu_916_p3 = {{data_11_val}, {8'd0}};

assign y_37_fu_954_p3 = {{data_13_val}, {7'd0}};

assign y_38_fu_982_p3 = {{data_14_val}, {8'd0}};

assign y_39_fu_1006_p3 = {{data_15_val}, {8'd0}};

assign y_40_fu_1030_p3 = {{data_16_val}, {8'd0}};

assign y_41_fu_1054_p3 = {{data_17_val}, {8'd0}};

assign y_42_fu_1078_p3 = {{data_18_val}, {8'd0}};

assign y_43_fu_1102_p3 = {{data_19_val}, {8'd0}};

assign y_44_fu_1126_p3 = {{data_20_val}, {8'd0}};

assign y_45_fu_1150_p3 = {{data_21_val}, {8'd0}};

assign y_46_fu_1174_p3 = {{data_22_val}, {8'd0}};

assign y_47_fu_1212_p3 = {{data_24_val}, {8'd0}};

assign y_48_fu_1236_p3 = {{data_25_val}, {8'd0}};

assign y_49_fu_1260_p3 = {{data_26_val}, {8'd0}};

assign y_50_fu_1284_p3 = {{data_27_val}, {8'd0}};

assign y_51_fu_1308_p3 = {{data_28_val}, {8'd0}};

assign y_52_fu_1332_p3 = {{data_29_val}, {8'd0}};

assign y_53_fu_1356_p3 = {{data_30_val}, {8'd0}};

assign y_54_fu_1380_p3 = {{data_31_val}, {8'd0}};

assign y_55_fu_1404_p3 = {{data_32_val}, {8'd0}};

assign y_56_fu_1428_p3 = {{data_33_val}, {8'd0}};

assign y_57_fu_1452_p3 = {{data_34_val}, {8'd0}};

assign y_58_fu_1476_p3 = {{data_35_val}, {7'd0}};

assign y_59_fu_1504_p3 = {{data_36_val}, {8'd0}};

assign y_60_fu_1542_p3 = {{data_38_val}, {8'd0}};

assign y_61_fu_1566_p3 = {{data_39_val}, {8'd0}};

assign y_62_fu_1590_p3 = {{data_40_val}, {8'd0}};

assign y_63_fu_1614_p3 = {{data_41_val}, {7'd0}};

assign y_64_fu_1656_p3 = {{data_43_val}, {7'd0}};

assign y_65_fu_1726_p3 = {{data_47_val}, {8'd0}};

assign y_66_fu_1750_p3 = {{data_48_val}, {8'd0}};

assign y_67_fu_1774_p3 = {{data_49_val}, {8'd0}};

assign y_68_fu_1798_p3 = {{data_50_val}, {8'd0}};

assign y_69_fu_1822_p3 = {{data_51_val}, {7'd0}};

assign y_70_fu_1850_p3 = {{data_52_val}, {8'd0}};

assign y_71_fu_1888_p3 = {{data_54_val}, {8'd0}};

assign y_72_fu_1912_p3 = {{data_55_val}, {8'd0}};

assign y_73_fu_1936_p3 = {{data_56_val}, {7'd0}};

assign y_74_fu_1964_p3 = {{data_57_val}, {7'd0}};

assign y_75_fu_1992_p3 = {{data_58_val}, {8'd0}};

assign y_76_fu_2016_p3 = {{data_59_val}, {8'd0}};

assign y_77_fu_2040_p3 = {{data_60_val}, {8'd0}};

assign y_78_fu_2064_p3 = {{data_61_val}, {8'd0}};

assign y_79_fu_2088_p3 = {{data_62_val}, {7'd0}};

assign y_80_fu_2116_p3 = {{data_63_val}, {8'd0}};

assign y_82_fu_672_p3 = {{data_1_val}, {8'd0}};

assign y_fu_648_p3 = {{data_0_val}, {8'd0}};

assign ap_return_0 = {{add_ln54_fu_656_p2[23:8]}};

assign ap_return_1 = {{add_ln54_32_fu_680_p2[23:8]}};

assign ap_return_10 = {{add_ln54_41_fu_900_p2[23:8]}};

assign ap_return_11 = {{add_ln54_42_fu_924_p2[23:8]}};

assign ap_return_12 = sext_ln54_fu_950_p1;

assign ap_return_13 = {{add_ln54_43_fu_966_p2[23:8]}};

assign ap_return_14 = {{add_ln54_44_fu_990_p2[23:8]}};

assign ap_return_15 = {{add_ln54_45_fu_1014_p2[23:8]}};

assign ap_return_16 = {{add_ln54_46_fu_1038_p2[23:8]}};

assign ap_return_17 = {{add_ln54_47_fu_1062_p2[23:8]}};

assign ap_return_18 = {{add_ln54_48_fu_1086_p2[23:8]}};

assign ap_return_19 = {{add_ln54_49_fu_1110_p2[23:8]}};

assign ap_return_2 = {{add_ln54_33_fu_704_p2[23:8]}};

assign ap_return_20 = {{add_ln54_50_fu_1134_p2[23:8]}};

assign ap_return_21 = {{add_ln54_51_fu_1158_p2[23:8]}};

assign ap_return_22 = {{add_ln54_52_fu_1182_p2[23:8]}};

assign ap_return_23 = sext_ln54_3_fu_1208_p1;

assign ap_return_24 = {{add_ln54_53_fu_1220_p2[23:8]}};

assign ap_return_25 = {{add_ln54_54_fu_1244_p2[23:8]}};

assign ap_return_26 = {{add_ln54_55_fu_1268_p2[23:8]}};

assign ap_return_27 = {{add_ln54_56_fu_1292_p2[23:8]}};

assign ap_return_28 = {{add_ln54_57_fu_1316_p2[23:8]}};

assign ap_return_29 = {{add_ln54_58_fu_1340_p2[23:8]}};

assign ap_return_3 = {{add_ln54_34_fu_728_p2[23:8]}};

assign ap_return_30 = {{add_ln54_59_fu_1364_p2[23:8]}};

assign ap_return_31 = {{add_ln54_60_fu_1388_p2[23:8]}};

assign ap_return_32 = {{add_ln54_61_fu_1412_p2[23:8]}};

assign ap_return_33 = {{add_ln54_62_fu_1436_p2[23:8]}};

assign ap_return_34 = {{add_ln54_63_fu_1460_p2[23:8]}};

assign ap_return_35 = {{add_ln54_64_fu_1488_p2[23:8]}};

assign ap_return_36 = {{add_ln54_65_fu_1512_p2[23:8]}};

assign ap_return_37 = sext_ln54_4_fu_1538_p1;

assign ap_return_38 = {{add_ln54_66_fu_1550_p2[23:8]}};

assign ap_return_39 = {{add_ln54_67_fu_1574_p2[23:8]}};

assign ap_return_4 = {{add_ln54_35_fu_752_p2[23:8]}};

assign ap_return_40 = {{add_ln54_68_fu_1598_p2[23:8]}};

assign ap_return_41 = {{add_ln54_69_fu_1626_p2[23:8]}};

assign ap_return_42 = sext_ln54_5_fu_1652_p1;

assign ap_return_43 = {{add_ln54_70_fu_1668_p2[23:8]}};

assign ap_return_44 = sext_ln54_6_fu_1694_p1;

assign ap_return_45 = sext_ln54_7_fu_1708_p1;

assign ap_return_46 = sext_ln54_8_fu_1722_p1;

assign ap_return_47 = {{add_ln54_71_fu_1734_p2[23:8]}};

assign ap_return_48 = {{add_ln54_72_fu_1758_p2[23:8]}};

assign ap_return_49 = {{add_ln54_73_fu_1782_p2[23:8]}};

assign ap_return_5 = {{add_ln54_36_fu_776_p2[23:8]}};

assign ap_return_50 = {{add_ln54_74_fu_1806_p2[23:8]}};

assign ap_return_51 = {{add_ln54_75_fu_1834_p2[23:8]}};

assign ap_return_52 = {{add_ln54_76_fu_1858_p2[23:8]}};

assign ap_return_53 = sext_ln54_9_fu_1884_p1;

assign ap_return_54 = {{add_ln54_77_fu_1896_p2[23:8]}};

assign ap_return_55 = {{add_ln54_78_fu_1920_p2[23:8]}};

assign ap_return_56 = {{add_ln54_79_fu_1948_p2[23:8]}};

assign ap_return_57 = {{add_ln54_80_fu_1976_p2[23:8]}};

assign ap_return_58 = {{add_ln54_81_fu_2000_p2[23:8]}};

assign ap_return_59 = {{add_ln54_82_fu_2024_p2[23:8]}};

assign ap_return_6 = {{add_ln54_37_fu_800_p2[23:8]}};

assign ap_return_60 = {{add_ln54_83_fu_2048_p2[23:8]}};

assign ap_return_61 = {{add_ln54_84_fu_2072_p2[23:8]}};

assign ap_return_62 = {{add_ln54_85_fu_2100_p2[23:8]}};

assign ap_return_63 = {{add_ln54_86_fu_2124_p2[23:8]}};

assign ap_return_7 = {{add_ln54_38_fu_824_p2[23:8]}};

assign ap_return_8 = {{add_ln54_39_fu_852_p2[23:8]}};

assign ap_return_9 = {{add_ln54_40_fu_876_p2[23:8]}};

endmodule //ParamEst_NN_normalize_ap_fixed_ap_fixed_16_6_5_3_0_PARAMEST_NN_config16_s
